In [1]:
import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from variables_inicio import *
from utils_sql import *

In [ ]:
# import pyodbc

# conn = pyodbc.connect(
#     "DRIVER={ODBC Driver 17 for SQL Server};"
#     "SERVER=tu_servidor;"
#     "DATABASE=CRONOX;"
#     "UID=tu_usuario;"
#     "PWD=tu_password;"
# )

# cursor = conn.cursor()

# # Ejecutar el stored procedure
# cursor.execute("EXEC dbo.SP_Generador_CENCOSUD_SAE")

# # Confirmar cambios (MUY IMPORTANTE)
# conn.commit()

# cursor.close()
# conn.close()

# print("Stored Procedure ejecutado correctamente")

In [2]:
query = "SELECT * FROM CRONOX.dbo.borrar_df_cencosud_pp_01"
df_cen=get_data_sql(query, params_sa)

# query = "SELECT * FROM CRONOX.dbo.Llave_Financiera_Efe_Neg"
# df_efe_neg=get_data_sql(query, params_sa)

# query = "SELECT * FROM CRONOX.dbo.Llave_Financiera_Efe"
# df_efe_consumo=get_data_sql(query, params_sa)

In [65]:
orden_01=df_efe_consumo.columns.to_list

In [50]:
df_dnio=pd.read_excel("C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\dni_1.xlsx",header=0)
df_inventario=pd.read_excel("C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\Inventario_marzo2026 v2.xlsx",header=0)

In [ ]:
df_dnio['']

In [51]:
df_inventario=df_inventario.merge(df_dnio,on='NUM_DOC',how='left')

In [ ]:
df_inventario = pd.read_excel(
    "C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\Inventario_marzo2026 v2.xlsx",
    header=0,
    dtype=str
)

In [53]:
df_inventario['NUM_DOC'] = (
    df_inventario['NUM_DOC']
    .astype(str)      # convertir a texto
    .str.zfill(8)     # rellenar con ceros a la izquierda
    .str[-8:]         # tomar los últimos 8 caracteres
)
df_inventario['FECHA_VISITA_UG'] = df_inventario['FECHA_VISITA_UG'].fillna(df_inventario['fecha'])

In [55]:
df_inventario.head()

,NUM_DOC,nombre_cliente,FECHA_VISITA_UG,OFERTA_CREDICASH,OFERTA_ELECTRO,OFERTA_MOTO,fecha
0,30411854,WILBER ANGEL SEGUNDO CARBAJAL RAMIREZ,2025-10-11,2500.0,NaN,NaN,NaN
1,00021872,BENITO QUILLE MAMANI,2025-12-30,2500.0,NaN,NaN,2025-12-30
2,23159681,BONIFACIO CACERES BORDA,2025-12-18,2500.0,NaN,NaN,2025-12-18
3,00047880,DOMINGO BERNABE EVARISTO QUISPE CERRON,2025-10-07,2500.0,NaN,NaN,2025-10-07
4,42247757,AYDE JESUS QUISPE COCA,2026-01-06,2500.0,NaN,NaN,2026-01-06

In [30]:
df_inventario.to_csv(
    "C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\Inventario_marzo2026 v03.csv",
    sep=';',
    index=False,
    date_format='%Y-%m-%d'
)

In [54]:
df_inventario.to_csv("C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\Inventario_marzo2026 v04.csv",sep=';')

In [56]:
df_inventario.to_csv(
    "C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\Inventario_marzo2026 v05.csv",
    sep=';',
    index=False
)

In [58]:
import pandas as pd

ruta = "C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\Inventario_marzo2026 v10.xlsx"

with pd.ExcelWriter(ruta, engine="xlsxwriter") as writer:
    df_inventario.to_excel(writer, index=False, sheet_name="inventario")

    workbook  = writer.book
    worksheet = writer.sheets["inventario"]

    # formato texto (para DNI)
    format_text = workbook.add_format({'num_format': '@'})
    
    # formato fecha
    format_date = workbook.add_format({'num_format': 'yyyy-mm-dd'})

    # aplicar formato
    worksheet.set_column('A:A', 15, format_text)   # NUM_DOC
    worksheet.set_column('C:C', 15, format_date)   # FECHA_VISITA_UG

In [58]:
df_uno.columns = (
    df_uno.columns
    .str.strip()
    .str.upper()
    .str.replace("Á","A")
    .str.replace("É","E")
    .str.replace("Í","I")
    .str.replace("Ó","O")
    .str.replace("Ú","U")
)

In [59]:
df_uno['PHONE NUMBER'] = df_uno['NUMERO'].astype(str)

In [60]:
df_uno=df_uno[['DNI', 'NOMBRE', 'PHONE NUMBER']]

In [61]:
df_uno=df_uno.merge(df_efe_consumo, left_on='PHONE NUMBER', right_on='PHONE NUMBER', how='left')

In [ ]:
Index(['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER', 'Order_Numero', 'Oferta', 'Tip_Prioridad', 'MARCA_2025',
       'NOMCOMERCIAL', 'Perfil_ic', 'tipocliente', 'TIPOINGRESO', 'ASIGNACION',
       'LINEA_FT', 'LINEA_HS_RS', 'LINEA_HS_PLUS', 'LINEA_FULL', 'MARCA',
       'TIP_TELF', 'PROVEEDOR', 'PERFIL', 'SEGMENTO', 'SCORE', 'TASA',
       'RANGO_TASA', 'ZONA', 'Tipo_Telf', 'Fecha_Llam', 'Hora_Llamada',
       'FECHA_ENVIO', 'RETIRO', 'Mejor_Estado_Telefono',
       'Mejor_Sub_Estado_Telefono', 'Mejor_Descripcion_Telefono',
       'Mejor_Fecha_Telefono', 'Mejor_Hora_Telefono', 'Mejor_Durac_Telefono',
       'Mejor_Estado_Cliente', 'Mejor_Sub_Estado_Cliente',
       'Mejor_Descripcion_Cliente', 'Mejor_fecha_Cliente',
       'Mejor_Hora_Cliente', 'Mejor_Durac_Cliente', 'ULT_Descripcion_Cli',
       'ULT_fecha_Cli', 'ULT_Hora_Cli', 'ULT_Durac_Cli', 'ULT_Descripcion_Tel',
       'ULT_fecha_Tel', 'ULT_Hora_Tel', 'ULT_Durac_Tel', 'Veces_Cliente',
       'Veces_Telefono', 'REPITENCIAS', 'Cantidad_Sin_Discador',
       'Cantidad_Discador', 'TELEFO1', 'TELEFO2', 'TELEFO3', 'REGION',
       'MARCADESBASE', 'MARCA2', 'FLGSUBPROCESO_HS', 'SITUACIONLABORAL']pho

Index(['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER', 'Order_Numero', 'Oferta', 'Tip_Prioridad', 'MARCA_2025',
       'NOMCOMERCIAL', 'Perfil_ic', 'tipocliente', 'TIPOINGRESO', 'ASIGNACION',
       'LINEA_FT', 'LINEA_HS_RS', 'LINEA_HS_PLUS', 'LINEA_FULL', 'MARCA',
       'TIP_TELF', 'PROVEEDOR', 'PERFIL', 'SEGMENTO', 'SCORE', 'TASA',
       'RANGO_TASA', 'ZONA', 'Tipo_Telf', 'Fecha_Llam', 'Hora_Llamada',
       'FECHA_ENVIO', 'RETIRO', 'Mejor_Estado_Telefono',
       'Mejor_Sub_Estado_Telefono', 'Mejor_Descripcion_Telefono',
       'Mejor_Fecha_Telefono', 'Mejor_Hora_Telefono', 'Mejor_Durac_Telefono',
       'Mejor_Estado_Cliente', 'Mejor_Sub_Estado_Cliente',
       'Mejor_Descripcion_Cliente', 'Mejor_fecha_Cliente',
       'Mejor_Hora_Cliente', 'Mejor_Durac_Cliente', 'ULT_Descripcion_Cli',
       'ULT_fecha_Cli', 'ULT_Hora_Cli', 'ULT_Durac_Cli', 'ULT_Descripcion_Tel',
       'ULT_fecha_Tel', 'ULT_Hora_Tel', 'ULT_Durac_Tel', 'Veces_Cliente',
       'Veces_Telefono', 'REPITENCIAS', 'Cantidad_Sin_Discador',
       'Cantidad_Discador', 'TELEFO1', 'TELEFO2', 'TELEFO3', 'REGION',
       'MARCADESBASE', 'MARCA2', 'FLGSUBPROCESO_HS', 'SITUACIONLABORAL'],
      dtype='str')

In [68]:
df_uno=df_uno[['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER']]

In [ ]:
df_uno

In [69]:
df_uno.to_csv("C:\\Users\\DATA\\Documents\\datos\\01_script\\inicio\\base_01.csv", index=False,sep=';')

(593162, 71)

In [ ]:
# df_efe_consumo['Mejor_Sub_Estado_Cliente'].unique()
    ['Mejor_Descripcion_Cliente'].unique()

<StringArray>
[                             'NO QUIERE',
                 'NO NECESITA / NO DESEA',
                              'SI QUIERE',
                         'ESTA ENDEUDADO',
                        'DESEA MAS MONTO',
                        'VOLVER A LLAMAR',
                                  'OTROS',
                     'CREDITO CONCRETADO',
                         'LO VA A PENSAR',
                       'CLIENTE DE VIAJE',
                     'INTERESES ELEVADOS',
        'TITULAR NO CALIFICA - DESEMPLEO',
                        'ABONO EN CUENTA',
            'CASA EN ZONA NO COBERTURADA',
                  'SOLICITA SER RETIRADO',
         'NEGOCIO EN ZONA NO COBERTURADA',
             'MALA EXPERIENCIA (TDA/FNC)',
 'TITULAR NO CALIFICA- GIRO RESTRINGIDO9',
                         'CONFIRMAR CITA',
      'TITULAR CONTAGIADO CON COVID - 19',
                          'DESEA ELECTRO',
                      'CLIENTE RECHAZADO']
Length: 22, dtype: str

In [54]:
df_efe_consumo[df_efe_consumo['VENDOR LEAD CODE']=='47905540'].head()

Empty DataFrame
Columns: [LAST NAME, FIRST NAME, ADDRESS1, ADDRESS3, COMMENTS, VENDOR LEAD CODE, PROVINCE, CITY, EMAIL, COMMENTS_2, PHONE NUMBER, Order_Numero, Oferta, Tip_Prioridad, MARCA_2025, NOMCOMERCIAL, Perfil_ic, tipocliente, TIPOINGRESO, ASIGNACION, LINEA_FT, LINEA_HS_RS, LINEA_HS_PLUS, LINEA_FULL, MARCA, TIP_TELF, PROVEEDOR, PERFIL, SEGMENTO, SCORE, TASA, RANGO_TASA, ZONA, Tipo_Telf, Fecha_Llam, Hora_Llamada, FECHA_ENVIO, RETIRO, Mejor_Estado_Telefono, Mejor_Sub_Estado_Telefono, Mejor_Descripcion_Telefono, Mejor_Fecha_Telefono, Mejor_Hora_Telefono, Mejor_Durac_Telefono, Mejor_Estado_Cliente, Mejor_Sub_Estado_Cliente, Mejor_Descripcion_Cliente, Mejor_fecha_Cliente, Mejor_Hora_Cliente, Mejor_Durac_Cliente, ULT_Descripcion_Cli, ULT_fecha_Cli, ULT_Hora_Cli, ULT_Durac_Cli, ULT_Descripcion_Tel, ULT_fecha_Tel, ULT_Hora_Tel, ULT_Durac_Tel, Veces_Cliente, Veces_Telefono, REPITENCIAS, Cantidad_Sin_Discador, Cantidad_Discador, TELEFO1, TELEFO2, TELEFO3, REGION, MARCADESBASE, MARCA2, FLGSUBPROCESO_HS, SITUACIONLABORAL]
Index: []

[0 rows x 71 columns]

In [10]:
df_efe_consumo.columns

Index(['LAST NAME', 'FIRST NAME', 'ADDRESS1', 'ADDRESS3', 'COMMENTS',
       'VENDOR LEAD CODE', 'PROVINCE', 'CITY', 'EMAIL', 'COMMENTS_2',
       'PHONE NUMBER', 'Order_Numero', 'Oferta', 'Tip_Prioridad', 'MARCA_2025',
       'NOMCOMERCIAL', 'Perfil_ic', 'tipocliente', 'TIPOINGRESO', 'ASIGNACION',
       'LINEA_FT', 'LINEA_HS_RS', 'LINEA_HS_PLUS', 'LINEA_FULL', 'MARCA',
       'TIP_TELF', 'PROVEEDOR', 'PERFIL', 'SEGMENTO', 'SCORE', 'TASA',
       'RANGO_TASA', 'ZONA', 'Tipo_Telf', 'Fecha_Llam', 'Hora_Llamada',
       'FECHA_ENVIO', 'RETIRO', 'Mejor_Estado_Telefono',
       'Mejor_Sub_Estado_Telefono', 'Mejor_Descripcion_Telefono',
       'Mejor_Fecha_Telefono', 'Mejor_Hora_Telefono', 'Mejor_Durac_Telefono',
       'Mejor_Estado_Cliente', 'Mejor_Sub_Estado_Cliente',
       'Mejor_Descripcion_Cliente', 'Mejor_fecha_Cliente',
       'Mejor_Hora_Cliente', 'Mejor_Durac_Cliente', 'ULT_Descripcion_Cli',
       'ULT_fecha_Cli', 'ULT_Hora_Cli', 'ULT_Durac_Cli', 'ULT_Descripcion_Tel',
       'ULT_fecha_Tel', 'ULT_Hora_Tel', 'ULT_Durac_Tel', 'Veces_Cliente',
       'Veces_Telefono', 'REPITENCIAS', 'Cantidad_Sin_Discador',
       'Cantidad_Discador', 'TELEFO1', 'TELEFO2', 'TELEFO3', 'REGION',
       'MARCADESBASE', 'MARCA2', 'FLGSUBPROCESO_HS', 'SITUACIONLABORAL'],
      dtype='str')