In [4]:
import sys 
sys.path.append('C:/Users/naand/OneDrive/Escritorio/a365/scripts/A365/interno')  

from funciones import *

In [5]:
import findspark
findspark.init()
import pyspark

from pyspark.sql import SparkSession

In [6]:
spark = SparkSession.builder \
    .appName("SparkExample") \
    .master("local[*]") \
    .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-10.2.3.jre17.jar') \
    .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-10.2.3.jre17.jar') \
    .config('spark.executor.memory', '6g') \
    .config('spark.driver.memory', '6g') \
    .getOrCreate()

In [11]:
file_list=[file for file in os.listdir(ruta_base)
    if "~$" not in file and "copia" not in file.lower() and ".zip" not in file.lower() and ".csv" not in file.lower() and "agent summary activity report (active)-_agent group-_subhour" in file.lower()]

In [12]:
file_list

[]

In [8]:
if file_list:
    for filename in file_list:
        df_ref=cargar_excel(filename)
        df_ref=df_ref[['Agent Name', 'Agent Group', 'Subhour', 'Active Time (Fmt)', 'Ready Time (Fmt)', 'Not Ready Time (Fmt)', 'Busy Time (Fmt)', 'Wrap Time (Fmt)']]
        df_ref[['apellido', 'nombre', 'usuario']] = df_ref['Agent Name'].str.extract(r'([^,]+),\s*([^()]+)\s*\(([^)]+)\)')
        df_ref.drop(columns=['Agent Name'], inplace=True)
        archivo_csv_disponible(df_ref,'temporal_campaign')
        
        df=cargar_archivo_csv(spark,'temporal_campaign.csv',';',True)

In [10]:
eliminar_archivo('temporal_campaign.csv')

Archivo temporal_campaign.csv eliminado.

In [11]:
df.show()

Py4JJavaError: An error occurred while calling o52.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 5) (192.168.1.4 executor driver): java.io.FileNotFoundException:
File file:/D:/datos/temporal_campaign.csv does not exist

It is possible the underlying files have been updated. You can explicitly invalidate
the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by
recreating the Dataset/DataFrame involved.

	at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:661)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:212)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:270)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:116)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2668)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2604)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2603)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2603)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1178)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1178)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1178)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2856)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2798)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2787)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2238)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2259)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2278)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:506)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:459)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:48)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3908)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2903)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:3898)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3896)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3896)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2903)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:3124)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:287)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:326)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.io.FileNotFoundException:
File file:/D:/datos/temporal_campaign.csv does not exist

It is possible the underlying files have been updated. You can explicitly invalidate
the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by
recreating the Dataset/DataFrame involved.

	at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:661)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:212)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:270)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:116)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

In [6]:
df.show()

+--------------------+--------------------+-----------------+----------------+--------------------+---------------+---------------+---------------+--------------+-------------+
|         Agent Group|             Subhour|Active Time (Fmt)|Ready Time (Fmt)|Not Ready Time (Fmt)|Busy Time (Fmt)|Wrap Time (Fmt)|       apellido|        nombre|      usuario|
+--------------------+--------------------+-----------------+----------------+--------------------+---------------+---------------+---------------+--------------+-------------+
|        A365_OUT_VTA|2024-06-25 10:00-...|         00:22:44|        00:11:43|            00:01:00|       00:06:01|       00:04:00|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 10:30-...|         00:30:00|        00:09:13|            00:12:03|       00:05:11|       00:03:33|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 11:00-...|         00:30:00|        00:16:29|            00:00:00|       00:07:57|       00:05:34|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 11:30-...|         00:30:00|        00:17:35|            00:00:00|       00:05:52|       00:06:33|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 12:00-...|         00:30:00|        00:09:28|            00:05:37|       00:11:26|       00:03:29|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 12:30-...|         00:30:00|        00:16:30|            00:00:00|       00:07:10|       00:06:20|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 13:00-...|         00:26:14|        00:14:27|            00:00:00|       00:06:07|       00:05:40|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 13:30-...|         00:24:51|        00:13:41|            00:00:00|       00:06:30|       00:04:40|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 14:00-...|         00:30:00|        00:00:11|            00:00:00|       00:29:29|       00:00:20|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 14:30-...|         00:30:00|        00:15:13|            00:00:00|       00:09:58|       00:04:49|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 15:00-...|         00:02:28|        00:01:45|            00:00:00|       00:00:12|       00:00:31|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 16:00-...|         00:20:12|        00:06:35|            00:00:02|       00:06:25|       00:07:10|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 16:30-...|         00:30:00|        00:07:51|            00:01:37|       00:14:55|       00:05:37|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 17:00-...|         00:30:00|        00:12:18|            00:00:00|       00:09:20|       00:08:22|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 17:30-...|         00:30:00|        00:13:51|            00:00:00|       00:10:58|       00:05:11|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|        A365_OUT_VTA|2024-06-25 18:00-...|         00:04:55|        00:02:11|            00:00:00|       00:01:44|       00:01:00|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|VAG_CL_OUT_ECO_A3...|2024-06-25 10:00-...|         00:22:44|        00:11:43|            00:01:00|       00:06:01|       00:04:00|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|VAG_CL_OUT_ECO_A3...|2024-06-25 10:30-...|         00:30:00|        00:09:13|            00:12:03|       00:05:11|       00:03:33|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|VAG_CL_OUT_ECO_A3...|2024-06-25 11:00-...|         00:30:00|        00:16:29|            00:00:00|       00:07:57|       00:05:34|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
|VAG_CL_OUT_ECO_A3...|2024-06-25 11:30-...|         00:30:00|        00:17:35|            00:00:00|       00:05:52|       00:06:33|Acasiete Lezano|Nury Clorinda |aap_nacasiete|
+--------------------+--------------------+-----------------+----------------+--------------------+---------------+---------------+---------------+--------------+-------------+
only showing top 20 rows

In [ ]:
df = df.withColumn("t_total", date_format("Active Time (Fmt)",'HH:mm:ss'))
df = df.withColumn("t_dispo", date_format("Ready Time (Fmt)",'HH:mm:ss'))
df = df.withColumn("t_no_dispo", date_format("Not Ready Time (Fmt)",'HH:mm:ss'))
df = df.withColumn("t_hablado", date_format("Busy Time (Fmt)",'HH:mm:ss'))
df = df.withColumn("t_acw", date_format("Wrap Time (Fmt)",'HH:mm:ss'))
df = df.withColumn("Busy Time (Fmt)", to_timestamp("Busy Time (Fmt)", 'HH:mm:ss'))
df = df.withColumn("Wrap Time (Fmt)", to_timestamp("Wrap Time (Fmt)", 'HH:mm:ss'))
df = df.withColumn("t_operativo", unix_timestamp("Busy Time (Fmt)") + unix_timestamp("Wrap Time (Fmt)"))
df = df.withColumn("t_operativo", expr("from_utc_timestamp(from_unixtime(t_operativo), 'UTC-5')"))
df = df.withColumn("t_operativo", unix_timestamp("t_operativo") )
df = df.withColumn("t_operativo", from_unixtime(col("t_operativo"), "HH:mm:ss"))
df = df.withColumn('fecha', to_date(df['fecha']))

campaing_name_01 = ['A365_OUT_VTA', 'VAG_CL_OUT_C2C_A365_DP_MOVIL_ECOM3']

In [24]:
df_ref.head()

,Agent Group,Subhour,Active Time (Fmt),Ready Time (Fmt),Not Ready Time (Fmt),Busy Time (Fmt),Wrap Time (Fmt),apellido,nombre,usuario
0,A365_OUT_VTA,2024-06-25 10:00-10:30,00:22:44,00:11:43,00:01:00,00:06:01,00:04:00,Acasiete Lezano,Nury Clorinda,aap_nacasiete
1,A365_OUT_VTA,2024-06-25 10:30-11:00,00:30:00,00:09:13,00:12:03,00:05:11,00:03:33,Acasiete Lezano,Nury Clorinda,aap_nacasiete
2,A365_OUT_VTA,2024-06-25 11:00-11:30,00:30:00,00:16:29,00:00:00,00:07:57,00:05:34,Acasiete Lezano,Nury Clorinda,aap_nacasiete
3,A365_OUT_VTA,2024-06-25 11:30-12:00,00:30:00,00:17:35,00:00:00,00:05:52,00:06:33,Acasiete Lezano,Nury Clorinda,aap_nacasiete
4,A365_OUT_VTA,2024-06-25 12:00-12:30,00:30:00,00:09:28,00:05:37,00:11:26,00:03:29,Acasiete Lezano,Nury Clorinda,aap_nacasiete

In [13]:
print(df_ref.columns.tolist())

['Agent Name', 'Agent Group', 'Subhour', 'Active Time (Fmt)', 'Ready Time (Fmt)', 'Not Ready Time (Fmt)', 'Busy Time (Fmt)', 'Wrap Time (Fmt)']

In [6]:

if file_list:
    for filename in file_list:
        df_ref=cargar_excel(filename)

        file_xlsx = os.path.join(ruta_base, filename)
        df01 = pd.read_excel(file_xlsx)
        temporal = 'temp01_agent_group'
        df01.to_sql(temporal, engine, index=False, if_exists='replace')

        query1 = f"""
        select * from temp01_agent_group
        """
        df_agent_summary_subhour = obtener_tabla_sql(spark,"DB_A365",query1)
        df_agent_summary_subhour_1=preparar_tabla_agent_summary_subhour(df_agent_summary_subhour)

        df_01_part1 = add_info_dota(spark,df_agent_summary_subhour_1,fecha_a_evaluar)
        df_01_part2 = add_info_base_cargada(spark,df_agent_summary_subhour_1,fecha_a_evaluar)
        df_02 = df_agent_summary_subhour_1.join(df_01_part2, ["calling_list","fecha"], "left") 

        df_03 = df_02.join(df_01_part1, ["fecha",'user_ref'], "left") 
        mover_archivo(filename)

        if not df_03.isEmpty():
            Export_list_base_sql(df_03,"DB_Tiempo",'TB_agentSumaryHour')
        else:
            print(f"{filename} no tiene datos para cargar")

['Agent Summary Activity Report (Active)-_Agent Group-_Subhour (1).xlsx']

In [8]:
fecha_a_evaluar='2024-06-01'
spark = SparkSession.builder \
    .appName("SparkExample") \
    .master("local[*]") \
    .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-10.2.3.jre17.jar') \
    .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-10.2.3.jre17.jar') \
    .config('spark.executor.memory', '4g') \
    .config('spark.driver.memory', '4g') \
    .getOrCreate()

file_list=[file for file in os.listdir(ruta_base)
    if "~$" not in file and "copia" not in file.lower() and ".zip" not in file.lower() and ".csv" not in file.lower() and "agent summary activity report (active)-_agent group-_subhour" in file.lower()]

if file_list:
    delete_SQL_hoy_TB_agentSumaryHour()
    for filename in file_list:
        file_xlsx = os.path.join(ruta_base, filename)
        df01 = pd.read_excel(file_xlsx)
        temporal = 'temp01_agent_group'
        df01.to_sql(temporal, engine, index=False, if_exists='replace')

        query1 = f"""
        select * from temp01_agent_group
        """
        df_agent_summary_subhour = obtener_tabla_sql(spark,"DB_A365",query1)
        df_agent_summary_subhour_1=preparar_tabla_agent_summary_subhour(df_agent_summary_subhour)

        df_01_part1 = add_info_dota(spark,df_agent_summary_subhour_1,fecha_a_evaluar)
        df_01_part2 = add_info_base_cargada(spark,df_agent_summary_subhour_1,fecha_a_evaluar)
        df_02 = df_agent_summary_subhour_1.join(df_01_part2, ["calling_list","fecha"], "left") 

        df_03 = df_02.join(df_01_part1, ["fecha",'user_ref'], "left") 
        mover_archivo(filename)

        if not df_03.isEmpty():
            Export_list_base_sql(df_03,"DB_Tiempo",'TB_agentSumaryHour')
        else:
            print(f"{filename} no tiene datos para cargar")
else:        
    print('No se encontro ningun archivo para campaign')

spark.stop()

El archivo FC_20240624_PART1_EQUIPO suhido

In [282]:
file_xlsx = os.path.join(ruta_base, 'REVISAR HOY.xlsx')
df01 = pd.read_excel(file_xlsx)

In [262]:
df01.head()

,ID,RUT,FECHA,ORDEN,GRUPO CANAL,CANAL GESTION,PDV,TIPO NEGOCIO,CENTRO,USUARIO,ESTADO EOC,HABILITADO?,ESTA EN BD LOGS?,Q,NUMEOR A PORTAR,NUMERO DE GRABACION,NUMERO DE CONTACTO
0,1130409545446,11304095,2024-06-03,832338275,OUTBOUND,OUTBOUND CAPTURA,5055,PORTABILIDAD SS,A365,AAP_RRUPAY,Cierre completado,SI,SI,1,5.699928e+10,5.699928e+10,5.699928e+10
1,706088145446,7060881,2024-06-03,832390210,OUTBOUND,OUTBOUND CAPTURA,5055,PORTABILIDAD SS,A365,AAP_RRUPAY,Cierre completado,SI,SI,1,5.694024e+10,5.695352e+10,5.694024e+10
2,1358432145446,13584321,2024-06-03,832474796,OUTBOUND,OUTBOUND CAPTURA,4820,PORTABILIDAD SS,A365,AAP_MCANGRE,Cierre completado,SI,SI,1,5.695979e+10,5.695979e+10,5.695979e+10
3,1545296245447,15452962,2024-06-04,832606006,OUTBOUND,OUTBOUND CAPTURA,5055,PORTABILIDAD SS,A365,AAP_RRUPAY,Cierre completado,SI,SI,1,5.698622e+10,5.698622e+10,5.698622e+10
4,1664170945447,16641709,2024-06-04,832623116,OUTBOUND,OUTBOUND CAPTURA,5055,PORTABILIDAD SS,A365,AAP_RRUPAY,Cierre completado,SI,SI,1,5.699810e+10,5.699810e+10,5.699810e+10

In [16]:
df01_migras = df01[df01['CAMPANA'] == 'MIGRACIONES']

In [283]:
temporal = 'resumen_hoy.csv'
df01.to_csv(f'{ruta_base}\\{temporal}', index=False, sep=';')

In [1]:
temporal = 'resumen_hoy.csv'

## aca pue

In [100]:
filePath = os.path.join(ruta_base, temporal)
df_resumen_hoy=spark.read.csv(filePath, sep=';', header=True)

In [101]:
window_spec = Window.orderBy(monotonically_increasing_id())

# Agregar una columna de ID secuencial
df_resumen_hoy_1 = df_resumen_hoy.withColumn("ID", row_number().over(window_spec))
df_resumen_hoy_1 = df_resumen_hoy_1.withColumn('NUMEOR A PORTAR', col('NUMEOR A PORTAR').cast('int'))
df_resumen_hoy_1 = df_resumen_hoy_1.withColumn('NUMERO DE GRABACION', col('NUMERO DE GRABACION').cast('int'))
df_resumen_hoy_1 = df_resumen_hoy_1.withColumn('NUMERO DE CONTACTO', col('NUMERO DE CONTACTO').cast('int'))
# df_resumen_hoy_1 = df_resumen_hoy_1.withColumn('PCS', col('PCS').cast('int'))

In [102]:
query1 = f"""
SELECT
	b.contact_info as contact_info_1
    ,a.nombre_base_cargada  as nombre_lista 
    ,a.fecha_carga
    ,a.nombre_skill
    ,case
        when a.nombre_skill ='PORTA_PERFILADA' then 1
        when a.nombre_skill ='PORTA_PERFILADA2' then 2
        when a.nombre_skill ='PORTA_RECUPERADOS' then 3
        when a.nombre_skill ='PORTA_PORTA5' then 3
        when a.nombre_skill ='PORTA_IVR' then 4
        when a.nombre_skill ='PILOTO_WOM' then 5
        when a.nombre_skill ='MIGRACIONES' then 6
        when a.nombre_skill ='MIGRACIONES2' then 7
        when a.nombre_skill ='CONECTA_MAYOR' then 8
        when a.nombre_skill ='SEGUNDAS' then 9
        when a.nombre_skill ='FIBRA_CROSS_3.0' then 10
    END AS ref1
from DB_BaseSemanal.dbo.TB_BaseCargada a
inner join TB_RegistroCargado b
on a.id_baseCargada=b.id_baseCargada
where a.fecha_carga >='2024-01-01'
and b.id_detalle<>5
"""

todo1 = obtener_tabla_sql(spark,"DB_PERFILADA",query1)
todo2 = obtener_tabla_sql(spark,"DB_RECUPERADOS",query1)
todo3 = obtener_tabla_sql(spark,"DB_IVR",query1)
todo4 = obtener_tabla_sql(spark,"DB_MIGRACIONES",query1)
todo5 = obtener_tabla_sql(spark,"DB_SEGUNDAS",query1)
todo6 = obtener_tabla_sql(spark,"DB_HOGAR",query1)

todo_01 = todo1.union(todo2).union(todo3).union(todo4).union(todo5).union(todo6)

In [103]:

window_spec = Window.partitionBy('fecha_carga','contact_info_1').orderBy(col("ref1").desc())
todo6 = todo6.withColumn("rank", row_number().over(window_spec))
todo6 = todo6.filter(col("rank") == 1).drop('rank')


query1 = f"""
SELECT 
fecha_registro 
,nro_negocio
,telefono_grabacion
,telefono_contacto_1
,telefono_contacto_2
,nro_linea
,contact_info as contact_info_2
,campania_usuario_reg_linea
,nombre_lista
,nombre_skill
,fecha_carga
FROM Reporte_Fuera_de_base
WHERE campania_usuario_reg_linea='MIGRACIONES'
AND fecha_registro>='2024-01-01'
and nombre_lista<>'No esta en base'
"""
df_ventas_acumuladas = obtener_tabla_sql(spark,"DB_ventas",query1)

In [104]:
df_ventas2=df_ventas_acumuladas.select('fecha_registro','nro_negocio','contact_info_2','nombre_lista','fecha_carga','nombre_skill').filter(col('contact_info_2').isNotNull())
df_ventas3=df_ventas_acumuladas.select('fecha_registro','nro_negocio','telefono_contacto_1','nombre_lista','fecha_carga','nombre_skill').filter(col('telefono_contacto_1').isNotNull())
df_ventas4=df_ventas_acumuladas.select('fecha_registro','nro_negocio','telefono_contacto_2','nombre_lista','fecha_carga','nombre_skill').filter(col('telefono_contacto_2').isNotNull())
df_ventas5=df_ventas_acumuladas.select('fecha_registro','nro_negocio','telefono_grabacion','nombre_lista','fecha_carga','nombre_skill').filter(col('telefono_grabacion').isNotNull())
df_ventas6=df_ventas_acumuladas.select('fecha_registro','nro_negocio','nro_linea','nombre_lista','fecha_carga','nombre_skill').filter(col('nro_linea').isNotNull())

df_ventas=df_ventas2.union(df_ventas3).union(df_ventas4).union(df_ventas5).union(df_ventas6)

window_spec = Window.partitionBy('fecha_registro',"contact_info_2").orderBy(col("fecha_registro").desc())
df_ventas = df_ventas.withColumn("rank", row_number().over(window_spec))
df_ventas = df_ventas.filter(col("rank") == 1).drop('rank')

In [105]:
df_resumen_hoy_2_part1= df_resumen_hoy_1.join(
    df_ventas, 
    (df_resumen_hoy_1["ORDEN"] == df_ventas["nro_negocio"]) & 
    (df_resumen_hoy_1["NUMEOR A PORTAR"] == df_ventas["contact_info_2"]) &
    (df_resumen_hoy_1["FECHA"] >= df_ventas["fecha_registro"]) , 
    "left"
).drop('fecha_registro', 'nro_negocio', 'contact_info_2') 

df_resumen_hoy_2_part2=df_resumen_hoy_2_part1.filter(col('nombre_lista').isNull()).drop('nombre_lista', 'fecha_carga','nombre_skill')

df_resumen_hoy_2_part2= df_resumen_hoy_2_part2.join(
    df_ventas, 
    (df_resumen_hoy_2_part2["ORDEN"] == df_ventas["nro_negocio"]) & 
    (df_resumen_hoy_2_part2["NUMERO DE GRABACION"] == df_ventas["contact_info_2"]) &
    (df_resumen_hoy_2_part2["FECHA"] >= df_ventas["fecha_registro"]) , 
    "left"
).drop('fecha_registro', 'nro_negocio', 'contact_info_2') 

df_resumen_hoy_2_part3=df_resumen_hoy_2_part2.filter(col('nombre_lista').isNull()).drop('nombre_lista', 'fecha_carga','nombre_skill')

df_resumen_hoy_2_part3= df_resumen_hoy_2_part3.join(
    df_ventas, 
    (df_resumen_hoy_2_part3["ORDEN"] == df_ventas["nro_negocio"]) & 
    (df_resumen_hoy_2_part3["NUMERO DE GRABACION"] == df_ventas["contact_info_2"]) &
    (df_resumen_hoy_2_part3["FECHA"] >= df_ventas["fecha_registro"]) , 
    "left"
).drop('fecha_registro', 'nro_negocio', 'contact_info_2') 

df_resumen_hoy_2_part1=df_resumen_hoy_2_part1.filter(col('nombre_lista').isNotNull())
df_resumen_hoy_2_part2=df_resumen_hoy_2_part2.filter(col('nombre_lista').isNotNull())

df_resumen_hoy_2=df_resumen_hoy_2_part1.union(df_resumen_hoy_2_part2).union(df_resumen_hoy_2_part3)

In [106]:
# df_resumen_hoy_2= df_resumen_hoy_1.join(
#     df_ventas, 
#     (df_resumen_hoy_1["ORDEN"] == df_ventas["nro_negocio"]) & 
#     (
#         (df_resumen_hoy_1["NUMEOR A PORTAR"] == df_ventas["contact_info_2"]) |
#         (df_resumen_hoy_1["NUMERO DE GRABACION"] == df_ventas["contact_info_2"]) |
#         (df_resumen_hoy_1["NUMERO DE CONTACTO"] == df_ventas["contact_info_2"]) 
#     ) &
#     (df_resumen_hoy_1["FECHA"] >= df_ventas["fecha_registro"]) , 
#     "left"
# ).drop('fecha_registro', 'nro_negocio', 'contact_info_2')

In [107]:
df_resumen_hoy_2 = df_resumen_hoy_2.withColumn('ref2', when(col('fecha_carga').isNull(), 1).otherwise(2))

window_spec = Window.partitionBy("ID").orderBy(col("ref2").desc())
df_resumen_hoy_2 = df_resumen_hoy_2.withColumn("rank", row_number().over(window_spec))
df_resumen_hoy_2 = df_resumen_hoy_2.filter(col("rank") == 1).drop('rank','ref2')

In [108]:
df_resumen_hoy_3=df_resumen_hoy_2.filter(col('nombre_lista').isNull()).drop('nombre_lista', 'fecha_carga','nombre_skill')

In [109]:
df_resumen_hoy_3_part1= df_resumen_hoy_3.join(
    todo_01, 
    (df_resumen_hoy_3["NUMEOR A PORTAR"] == todo_01["contact_info_1"]) &
    (df_resumen_hoy_3["FECHA"] >= todo_01["fecha_carga"]) , 
    "left"
).drop('contact_info_1') 
df_resumen_hoy_3_part2=df_resumen_hoy_3_part1.filter(col('nombre_lista').isNull()).drop('nombre_lista', 'fecha_carga','nombre_skill','ref1')

df_resumen_hoy_3_part2= df_resumen_hoy_3_part2.join(
    todo_01, 
    (df_resumen_hoy_3_part2["NUMERO DE GRABACION"] == todo_01["contact_info_1"]) &
    (df_resumen_hoy_3_part2["FECHA"] >= todo_01["fecha_carga"]) , 
    "left"
).drop('contact_info_1') 

df_resumen_hoy_3_part3=df_resumen_hoy_3_part2.filter(col('nombre_lista').isNull()).drop('nombre_lista', 'fecha_carga','nombre_skill','ref1')

df_resumen_hoy_3_part3= df_resumen_hoy_3_part3.join(
    todo_01, 
    (df_resumen_hoy_3_part3["NUMERO DE GRABACION"] == todo_01["contact_info_1"]) &
    (df_resumen_hoy_3_part3["FECHA"] >= todo_01["fecha_carga"]) , 
    "left"
).drop('contact_info_1')

In [110]:

df_resumen_hoy_3_part1=df_resumen_hoy_3_part1.filter(col('nombre_lista').isNotNull())
df_resumen_hoy_3_part2=df_resumen_hoy_3_part2.filter(col('nombre_lista').isNotNull())

df_resumen_hoy_3=df_resumen_hoy_3_part1.union(df_resumen_hoy_3_part2).union(df_resumen_hoy_3_part3)

In [111]:
window_spec = Window.partitionBy("ID").orderBy(col("ref1").asc())
df_resumen_hoy_3 = df_resumen_hoy_3.withColumn("rank", row_number().over(window_spec))
df_resumen_hoy_3 = df_resumen_hoy_3.filter(col("rank") == 1).drop('rank','ref1')

In [112]:
df_revisar_hoy=df_resumen_hoy_3.union(df_resumen_hoy_2)

In [113]:
df_revisar_hoy = df_revisar_hoy.withColumn('ref4', when(col('fecha_carga').isNull(), 1).otherwise(2))

In [114]:
window_spec = Window.partitionBy("ID").orderBy(col("ref4").desc())
df_revisar_hoy = df_revisar_hoy.withColumn("rank", row_number().over(window_spec))
df_revisar_hoy = df_revisar_hoy.filter(col("rank") == 1).drop('rank')

In [115]:
overwrite_table_SQL(df_revisar_hoy,"DB_A365",'tb_hoy_ultimo_con_reciclado')

In [99]:
agg_expr1 = [
    "ref4",
]

agg_expr2 = {
    "ID": "count",
}

df_registros = df_revisar_hoy.groupBy(agg_expr1).agg(agg_expr2)
df_registros.show()

+----+---------+
|ref4|count(ID)|
+----+---------+
+----+---------+

In [253]:

migras_3=migras_resultado.filter(col('ref1')==1).drop('nombre_lista', 'fecha_carga','ref1','CAMPANA')
migras_3.count()

139

In [254]:
query1 = f"""
SELECT
	b.contact_info as contact_info_1
    ,a.nombre_base_cargada  as nombre_lista 
    ,a.fecha_carga
from DB_BaseSemanal.dbo.TB_BaseCargada a
inner join TB_RegistroCargado b
on a.id_baseCargada=b.id_baseCargada
where a.fecha_carga >='2024-01-01'
and b.id_detalle<>5
"""

otros_todo = obtener_tabla_sql(spark,"DB_HOGAR",query1)

window_spec = Window.partitionBy("nombre_lista").orderBy(col("fecha_carga").desc())
otros_todo = otros_todo.withColumn("rank", row_number().over(window_spec))
otros_todo = otros_todo.filter(col("rank") == 1).drop('rank')

In [198]:
migras_3= migras_3.join(
    otros_todo, 
    (migras_3["PCS"] == otros_todo["contact_info_1"]) & 
    (migras_3["FECHA GESTION"] >= otros_todo["fecha_carga"]) , 
    "left"
).drop('contact_info_1') 
migras_3 = migras_3.withColumn('ref1', when(col('fecha_carga').isNull(), 1).otherwise(2))

In [199]:
agg_expr1 = [
    "ref1",
]

agg_expr2 = {
    "PCS": "count",
}

migras_3_001 = migras_3.groupBy(agg_expr1).agg(agg_expr2)
migras_3_001.show()

+----+----------+
|ref1|count(PCS)|
+----+----------+
|   1|       137|
+----+----------+

In [ ]:
df_01= df_01.join(
    df_bloque, 
    (df_01["contact_info"] == df_bloque["contact_info_1"]) & 
    (df_01["fecha_recepcion"] > df_bloque["fecha_carga"]) & 
    (df_01["obs1"] == 'unico') , 
    "left"
)

In [ ]:
migras_todo