### Retiro Fugas

In [1]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

In [4]:

server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

server_sql = server_zeus
db_sql = "SAMANTHA"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_samantha = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

In [1]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

fecha_mes_base='2026-07-01'

filename='retiro_tc_20260717_01.xlsx'
name_dni='DNI'

ruta_archivo = os.path.join(ruta_csv, filename)
df = pd.read_excel(ruta_archivo)

df[f"{name_dni}"] = (
    df[f"{name_dni}"]
    .astype(str)
    .str.zfill(8)
)

df = df.rename(columns={
    f'{name_dni}': 'NUMERO_DOCUMENTO'
})
df=df[["NUMERO_DOCUMENTO"]]
df.head()
server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
query = f"""
	select NUMERO_DOCUMENTO
	from DANTALION.dbo.Base_Maestra_Diners_TC_Vigente
    WHERE RETIRO IS NULL OR RETIRO =''
"""
df_tc = pd.read_sql(query, engine_kishin)

In [2]:
df_tc.shape

(39853, 1)

In [5]:
campana='dinersTc'
query = f"""
    select FECHA as fecha_gestion,DNI as NUMERO_DOCUMENTO,
    PROMOTOR as promotor,
    ESTADO as estado_venta,
    TRAMA_HORA as tramo_venta,
    MONTO as monto_venta,
    DNIEjecutivo as dni_ejecutivo_venta,
    Producto as producto_venta,
    Producto as title,
    Celular as cel_venta,1 as venta,
    subcampana
    from SAMANTHA.dbo.Ventas_Target
    where campana='{campana}'
    and cast(fecha as date) between '{fecha_mes_base}' and EOMONTH('{fecha_mes_base}')
"""
df_ventas = pd.read_sql(query, engine_samantha)

In [6]:
df_ventas.count()

fecha_gestion          201
NUMERO_DOCUMENTO       201
promotor               201
estado_venta           201
tramo_venta            201
monto_venta              0
dni_ejecutivo_venta    201
producto_venta           0
title                    0
cel_venta              201
venta                  201
subcampana               0
dtype: int64

In [7]:
df = df[
    ~df["NUMERO_DOCUMENTO"].isin(df_ventas["NUMERO_DOCUMENTO"])
].copy()

In [8]:
df.merge(df_tc, on='NUMERO_DOCUMENTO', how='inner').count()

NUMERO_DOCUMENTO    1884
dtype: int64

In [9]:

list_dni = (
    df['NUMERO_DOCUMENTO']
    .dropna()
    .drop_duplicates()
    .tolist()
)
in_clause = ",".join(f"'{x}'" for x in list_dni)

in_clause

"'70616397','43850905','72976172','44755864','47481829','70575810','71561978','43756334','45394060','71570358','47607845','70558173','72393032','73378522','70102727','41598938','46833055','43518318','73752170','45158903','48063442','43487571','40242634','70021940','44568166','71478967','72697908','47448366','47491907','44972117','07127441','75459989','46641795','48151999','06267077','45572038','73188653','74212430','42993532','42429324','71868257','75438478','47832656','40293366','47448052','44115936','75520687','44069960','70865637','45999459','75368009','40105761','41677855','44155217','41036230','48152453','73485144','40062769','42977517','73958376','10314489','46546698','72870934','71893746','47463427','47016100','72571782','70326843','48014670','70691861','44519661','45836593','71943121','70125004','40656563','76455747','47901252','77079160','77148412','46197950','45864409','48486912','47509453','47104593','46789013','72132607','47173197','76344843','40375724','46097752','44837228','48225518','75350223','45300438','76624413','41811977','71227350','70276105','46847215','46740027','08165195','48628177','44148969','40994944','71229503','48006782','73884477','46746004','42228841','70912408','44369668','74072316','43297966','06785890','03662092','46078253','73091980','40850650','70174344','76567453','71063284','48936850','70155385','41782012','71441841','46804982','00797946','41650764','45632415','74703845','45112011','43393878','47937942','48597674','70032536','70444061','45642358','70205151','73213700','40295341','41586170','72648106','70213977','48464245','47576498','10740171','42304142','10158857','44337334','73613015','72503750','72180289','71275272','70069664','71475099','45763686','45497515','42150426','73434837','70687008','45905632','42679791','72353032','73076458','40794829','46884638','72118602','76861474','71071637','71893151','09696423','09678548','76968473','44131304','70691789','71702122','74970088','43460810','46797423','46753867','72744026','48267328','09917530','74350784','47078933','72614641','46124060','46710112','42751148','48414752','44258822','44764856','10053917','40984634','71036415','70367528','70311206','10199288','40992293','46462423','44362990','72853954','46521637','77478790','70488592','10702023','70071733','71402662','29658113','47644054','70904220','73791082','70343837','73184779','73778977','47609866','45459714','46964227','06573358','09341890','73058334','73008958','72127094','45410325','76379439','46977810','75965012','70751633','73062915','72310638','07926814','70052064','72404287','42521789','42545910','75602910','75212550','72364960','46900561','47756136','70320059','73102490','73115117','43806848','04622654','71207979','47102797','10135185','47057029','71040457','76461697','10880314','47619413','71838135','72579973','46705244','42764583','40580066','70275919','43492342','70694020','47923765','73138326','05399194','70272979','06588692','76356220','71619290','47595178','73057839','73469499','74072364','45102830','42604611','47772717','10726108','10281255','77326462','41408521','70089086','47782433','72201249','09289848','72635168','73176083','70427317','07270827','76448579','45854425','31629121','45847537','44264852','46901364','41027505','46198359','46067297','72670410','72737070','46540884','46093307','47497374','72519556','70982638','44191397','47587653','42828602','10013179','46318517','75495576','40296056','48116546','40890377','74441416','77536497','48018513','46487775','29263887','42764622','70690564','44475721','73854556','70431990','47163498','09878219','70365395','46663232','72305564','40035601','75134674','48683940','06202921','45083175','46219126','25742967','22289095','47046210','32791231','10138768','44743997','72976285','74165805','46765635','46392322','72403276','70425449','46880556','73703466','47819621','74600530','75918441','46177669','70898661','77281092','41089071','40189423','48188671','72733595','41451441','31653587','45856820','45262836','72634423','44000769','46032020','29254729','74709331','47062006','70436662','46362399','18197700','73442978','45120180','46604663','71071205','72206991','71942660','46599075','42978467','71434543','77269975','70316328','47566296','42643916','43913231','46190123','43816669','40415387','45862882','70017508','41143361','46742071','73076366','72394590','46407420','48639370','47893934','46328827','10812969','40327321','46113016','28270553','06687359','70142256','07927062','41345821','75326419','15759100','73131811','48108932','70234928','44156736','48509144','73860196','48904041','43882227','47331245','40908344','73042807','25775302','70807120','70330679','70125628','76448576','44755872','72157160','47899248','77664135','70248783','43407002','41276788','70000439','70025981','48244805','74544099','41839235','70230881','72193623','40554769','47182513','46022600','72979806','09802564','74295409','70674851','45471066','46921718','70346302','45838318','73005618','72323071','29687893','72041555','09995599','70782594','42062761','45475349','46498420','47169908','47571208','44388999','76669526','10625659','75210585','72960255','72193930','73110813','44843186','70028626','74778947','70568205','70102383','72859697','46618696','71323123','40511098','46803740','47576778','45426308','72190797','73470059','44943627','72477158','48392171','46493924','48301380','10581480','44471210','41116889','42210067','74391272','76154272','47534649','43084079','72403192','48039272','70266113','44865417','46645281','76047841','42698178','70369715','47843110','78113482','71249713','29315710','04409683','47742816','45435999','09880016','44035788','71337228','43159345','72526958','41526231','73092842','42731022','71388053','72196069','70763468','72042523','71977585','71432709','72513978','74729189','46722793','48309264','42614093','47650956','70144647','73043358','72897232','15433364','76520647','42635534','74721776','47137917','46963923','72200495','05357722','08626886','47324730','44142806','74787901','48558980','73259583','45197088','48151807','70228366','71417290','47879247','75171300','40016244','70273653','72966183','72913326','73434619','72487154','70676696','75839567','72172520','45813326','41933351','44175439','41431913','70018089','41816113','70293999','42694701','47585078','70551167','07631546','41297734','21569736','42850040','72757598','06221120','44378871','73215945','47230379','74831650','73212211','72522680','76592576','46259818','72193430','44286426','45425805','71282934','46606023','40446471','72156751','70565274','74847736','71420036','46347443','41008360','70502459','41966318','76992118','48285070','74633683','17869003','71936658','46984474','70121183','45096339','47059740','72437997','73696137','40819208','71490013','47507838','70026448','08167676','74744497','46779416','70150844','43332595','46796519','75595239','44441431','70857625','73007618','76356385','23966906','47628213','42090102','47688206','46439547','46442465','74754922','48026010','47592945','73160967','47999902','22302915','07717104','46261010','45426686','45634181','70006193','40665799','02773578','47019543','76018627','72352917','43480590','47839218','47497309','71017532','46755798','45455050','48093855','70851463','46472876','70826352','46378927','47552578','45991845','46577122','19578141','40316755','72041779','73273471','70284908','47563890','43634233','70831183','76614104','72029115','70366590','72976731','40615621','41416056','20076598','00487632','73180511','44983475','47419157','71740745','45470115','74963329','44484550','45862389','74208610','44348985','43795648','70036625','43429326','45807318','06610381','72677726','46965416','71239526','09443039','72741810','75395164','70508359','45123747','46318956','41462975','45252205','73256469','72435321','74220391','41758083','71481132','46900958','70352564','43016995','76651829','77278463','40640704','42742945','43053384','40091249','10284941','45972934','76572186','76531216','46425801','44291430','46354569','10160696','70022559','75579502','45943905','75267347','40367966','48337748','71329403','71467218','72328860','75728848','72451353','70107766','70144407','46657708','73089379','40921340','72189786','47395329','70664208','47580709','70004490','10072185','72779874','46718775','47552707','43185246','44859860','47493771','70432574','46001046','77470335','06816106','74312408','71438717','72700762','47383496','10106826','73076756','47157111','73191481','45112467','42942297','47888337','74207071','10690297','09860923','07202909','47128324','47401775','72226260','48429902','75371043','45899858','72001316','76085823','71205644','74894545','72196553','72578260','47172539','70548529','47863563','46955903','74135701','75414075','70417342','70353505','45613162','72209428','47725315','48000901','45191308','74147484','45339777','70042537','70438139','48363962','73423907','47425728','77691127','75343653','43331777','46385158','70273852','40491790','47247394','71281253','70548311','73380240','44307270','72174141','48438248','45394829','75890811','09392259','49004216','46414887','73417861','09676728','41434992','48408219','47420105','47545099','06310924','47532426','47020655','40896689','47512316','71637457','47278216','72525032','77288703','73251683','40096274','46844453','46593910','47649378','41597509','46315658','70216368','40919136','70776398','41914050','72922719','42007325','46550259','47979406','72633855','71405025','45599987','10208568','41903000','46425906','46592673','77435349','17854735','46836203','40606561','47950733','42037321','70441283','40028388','48671652','74089111','76563714','74133508','40000640','46789204','76099081','44454110','47074057','47273247','43586267','44351125','72571433','76875915','76593876','71479957','70826689','70542010','70343206','72571814','72031213','76400915','44360908','73354187','75401947','20063167','08690397','47113389','47174069','46229290','45274900','41162758','40501182','46645616','71755821','71625237','10679866','44455537','45316563','45348020','72572960','70366942','48126106','70240442','48133708','77351827','71422774','47453000','45640378','75109283','73377514','73063205','73579011','70389825','71418295','72079266','70453369','45862052','73132809','70499432','46440068','45867084','72604991','41667342','45677102','46743395','45015901','72436507','48993399','73177811','47901101','70048911','75550514','43632277','47247820','70073773','48452086','46613197','72922146','70681399','18210639','42368540','46651467','76187637','46604748','71959160','74745572','74902986','48999976','18037911','08717984','47165205','71449730','46684865','73003642','76662045','44755856','45865851','75689510','71981718','32974576','74698213','73304295','71554871','76857032','47787085','70024486','45871112','09669718','73018123','41027087','77154662','74356034','76571115','44381239','47566517','45347556','70022614','41678464','46719018','47793165','43687898','70842080','72023316','74065494','46830148','40273493','70184279','41120329','40231591','45206674','46238541','74608868','70652805','44563187','48083262','43569115','40965179','70249474','41686316','43716752','71888698','40341318','72680190','48608090','46730228','70002157','74174729','43129134','75388514','47484759','41863906','71046127','72447578','77377805','45591495','43703719','73200038','75859073','70863796','72726172','43333654','45985600','45124065','41872325','09875911','25658956','47462574','46018762','42646513','72164508','71257426','70600188','71793527','10314899','45515614','47048713','75538208','47903212','70066952','70748897','72381000','73518841','70672921','72542662','46111438','44627961','47694561','40336659','77388606','10349836','70309653','76373643','76163635','75790129','72457133','25649982','17998915','40353431','41241732','77093347','70978435','74809581','70000862','10882520','74619912','45415314','42745038','72889334','70853705','42201597','74829532','71226515','71597609','77657988','73217469','21565758','41590973','71403196','70947101','45899094','74053226','72365239','76633400','42978809','76746227','73030282','47992161','44550454','72205020','71545604','07625200','46431306','47493513','47207478','40339334','40901073','46164576','70336916','70442122','46555947','76528189','42710518','46415806','45873550','30676433','46686968','08455242','44112170','77567932','44243613','48076051','47282264','43745859','46773496','71274109','06271155','47187088','41892657','72711957','47486183','70876899','41714324','46189690','41805162','45845052','70833217','25760809','48584701','78015698','71893624','70784619','43938383','70336996','46170489','46154340','70378334','19986699','75369510','47516258','41256572','77232480','74155755','72119956','20039424','07724064','48006368','70578296','72976542','44933770','26685546','43542374','71456012','48056383','46923923','46261927','74829546','70203573','40578566','45610314','46736241','76556522','45000329','72944186','47370705','45367860','46276971','74147487','76011952','70478368','43375309','44603495','45312436','70312758','72541694','73025490','45562744','47322577','70865402','46674535','72493709','40811381','47986294','09541642','71886153','45369803','25831234','40926457','72493588','61811476','73690155','42298153','05391068','07042158','70667013','71951223','45544521','46813633','41729686','72204317','44841020','70525805','70922391','42590183','48015462','72773128','71612967','70454309','73083980','45398736','75507422','46259717','70385012','41352713','71570656','73783829','72514983','72271572','40343823','70991161','75325116','75417610','70288200','71977613','76912235','71228047','71256615','77804545','71714202','42706481','06268189','46670684','76981361','10045206','70014168','72924383','72208456','70009120','73584788','60657986','10201736','76463020','73150917','45487537','43209402','45962369','21459962','72159067','70866775','45246838','72727473','45838400','47355765','71732840','70073824','71005090','45895992','48530236','46000152','73131158','70195795','72743668','71705513','40651076','71541270','48460206','45257658','07762033','08168593','74598391','48003453','48565472','73825166','44170452','43566406','46818654','72622844','45129518','44348055','43001189','74604640','70990288','74020303','76666466','71996262','74025284','70366701','41935597','71831074','47301679','46998260','46156675','43695329','42664882','70007216','72620504','47816928','45476930','48708075','76605883','40620965','74708910','76294446','46579550','10488372','75919350','08682589','71224240','72359838','74305428','46203766','40993293','47140993','73701800','48018466','72564378','10000874','70028404','72607058','73264363','71195704','70619343','47902924','17843544','10777575','44638262','74027085','75254210','72303268','72251431','73658006','46087880','10664423','43146586','72804637','46633623','40858455','74834702','72328887','73570465','45540088','71418018','44726059','48018925','70315002','46441543','08161099','10245551','47655870','70216578','74027016','70127978','71959248','40828016','73237391','45209430','47152139','75980006','47174823','08148018','47794899','07528431','24003116','46818795','42103991','44062282','20592269','46210881','40130409','73874419','71088027','73191246','71618925','74997641','70887832','77096703','40510748','73202659','45295181','46082052','73856276','45754242','72084035','45526224','46918769','72791215','42148043','48420932','25793235','43421197','09679709','72845274','47373836','70436189','40101457','73276345','08135639','72329519','45323211','70982066','71385891','07510162','46812982','71058360','45651256','73769413','25442476','40804588','72454665','73100143','47637657','07496580','76927074','71105837','70067170','72882097','48487238','48311895','43176633','76985708','44005177','16017050','25790954','72876350','10185787','70409770','40518277','09337671','40581204','46338502','18200206','74610521','45648462','73150130','71406889','43188035','44472521','72926247','48370725','77658899','46432828','42079666','42659528','09904172','10269675','72030034','72685367','41517730','40401917','48494168','70764437','72669740','72737570','47033278','43592534','70607446','08173380','45897629','75436283','44675754','72134502','46881546','46561148','70222938','46364353','72360197','73015927','71446834','19804900','71936826','06165923','46887124','73172242','40641241','46798332','46854927','75824377','47863854','70652648','07977190','41679047','72498438','47884185','42695179','76337031','72841681','02836959','72731104','46843164','70226236','41958376','45059418','43608803','76836400','48652463','70818817','06803401','47163232','70027849','04300392','40478926','44180759','42838954','47998017','73746089','47215082','48192547','77913634','73171360','47138612','72645776','77672637','47483917','73741161','47402311','71724144','70022806','09748680','71243266','47818340','71376941','40904683','70681337','71951849','40287231','46001610','72543829','72030941','71463750','45520768','73221401','72284707','73572308','44311648','70927937','48183172','42891571','48039976','70069905','70438888','77061819','48086676','06234017','43391645','72495873','46456210','45385516','47271884','76018879','70954290','43981454','47221905','74528286','75046808','71138385','46006460','71018954','41256566','71629573','70652820','71283906','70799199','76947652','70819529','43056086','48003969','46671048','43825867','48331242','46332685','73449880','10585106','10761142','72416819','44035666','45290931','74135729','72266851','76190223','45467252','46800003','02441429','47092562','07886014','45744333','70048030','16799019','77470424','70280940','71574914','42811136','70398540','76597411','76423151','47411925','48086529','46185127','73180232','72219201','43804031','76269770','41849889','40342633','70862771','46592530','45707803','72685438','73482954','47160597','75163746','70537458','45925630','02679709','43663435','48327873','45939298','72637178','75328672','75952618','46273712','43972939','75556506','76452036','76407106','72708164','06186034','47101789','41675766','73868560','70808324','74872942','73369573','70060171','41236292','47040459','44563788','73265400','70258641','40457423','41340686','71502510','08156714','70928923','74930289','42428305','41982821','44827990','77920962','41123615','47628178','46238008','46138655','44351612','45964142','43134530','48347710','09581224','44394596','10635424','74146201','72327030','75242159','46671083','70182787','48365367','46829357','71088941','71593346','47386531','73084636','70438841','73181207','45754938','72194568','48129452','70541583','70130831','73809644','75330016','72493713','76373109','70012975','74046246','45992338','72006186','77500318','46237278','70465782','72975792','29643507','46129783','44763130','47737091','44481959','09615116','40485503','45110130','47126029','73076479','46156138','06571109','40226058','71650910','09181911','72947537','47269563','47349693','73668672','43872936','80131108','40752120','71702128','29568329','44351326','48320244','43547537','70023034','10308636','70282252','70090116','45124144','40871391','72260585','72730704','72389727','42978669','74988215','45870405','70439089','46095104','70664978','72682885','46021183','48090498','70876280','75504046','70409501','47170554','46990582','70195275','45168247','72433410','40674861','74021264','71554658','43910780','07495713','43322081','45819974','48519670','76136361','46850242','76319193','63079570','71533850','40116061','70000807','76157893','72493681','70501174','44098585','45975171','42058430','44492661','15738670','70788638','71197477','70764265','00122391','40837763','07868103','41239589','45859891','70156027','72430614','72785614','47182529','46696201','43566898','44303346','47637915','44388155','40139599','47841089','09458669','46009970','43033320','43812612','77907120','70830308','70057459','46716729','43890563','48628763','70826792','44833688','70989932','76467638','76023762','44247874','45617237','44592930','70498491','47008470','48644572','75067014','43912530','72943362','46202277','45328070','07969078','45578749','

In [9]:
in_clause = ",".join(f"'{x}'" for x in list_dni)

In [11]:
df.count()

NUMERO_DOCUMENTO    2030
dtype: int64

In [13]:
try:
    with engine_kishin.begin() as conn:
        query = f"""
            UPDATE DANTALION.dbo.Base_Maestra_Diners_TC
            SET RETIRO = 'RETIRO_17'
            WHERE NUMERO_DOCUMENTO IN ({in_clause})
                and fecha_envio >= '{fecha_mes_base}'
                AND fecha_envio <= EOMONTH('{fecha_mes_base}')
        """
        result = conn.execute(text(query))
        print("Filas actualizadas:", result.rowcount)

except Exception as e:
    print(e)

Filas actualizadas: 1884

In [10]:
fecha_mes_base

'2026-07-01'

In [ ]:

df_ventas.head()

,fecha_gestion,NUMERO_DOCUMENTO,promotor,estado_venta,tramo_venta,monto_venta,dni_ejecutivo_venta,producto_venta,title,cel_venta,venta,subcampana
0,2026-07-01,07259135,08728081,1.-VALIDADA,9,None,08728081,None,None,981260227,1,None
1,2026-07-01,07779510,44592143,6.-SIN VALIDAR,13,None,44592143,None,None,989371280,1,None
2,2026-07-01,40102384,44592143,1.-VALIDADA,10,None,44592143,None,None,932595948,1,None
3,2026-07-01,40552162,47202133,1.-VALIDADA,10,None,47202133,None,None,988594366,1,None
4,2026-07-01,41266190,44592143,1.-VALIDADA,9,None,44592143,None,None,940049145,1,None

In [14]:
exec_query_sql(server_kishin, db_kishin, user_kishin, pwd_kishin, "tNumeros_Diners_tc", "SP tNumeros diners TC")
exec_query_sql(server_zeus, "ODIN", user_zeus, pwd_zeus, "EXEC Sp_Actualizar_Diners_tc", "SP actualizar diners TC Zeus")
exec_query_sql(server_sa, "ODIN", user_sa, pwd_sa, "EXEC Sp_Actualizar_Diners_tc", "SP actualizar diners TC SA")

SP tNumeros diners TC | realizado | duración: 25.21 seg
SP actualizar diners TC Zeus | realizado | duración: 35.56 seg
SP actualizar diners TC SA | realizado | duración: 3.5 seg

In [8]:
query = f"""
	select NUMERO_DOCUMENTO,PROB_CONTACTO,concat('2026-07-',right(retiro,2)) as retiro
	from DANTALION.dbo.Base_Maestra_Diners_TC_Vigente
    WHERE RETIRO IS not NULL OR RETIRO <>''
"""
df_tc = pd.read_sql(query, engine_kishin)

In [9]:
df_tc.head()

  NUMERO_DOCUMENTO PROB_CONTACTO      retiro
0         47216152             D  2026-07-01
1         71561197             D  2026-07-01
2         42968074             C  2026-07-01
3         73473064             E  2026-07-01
4         46510882             C  2026-07-01

In [ ]:


server_sql = server_zeus
db_sql = "SAMANTHA"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_zeus = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
fecha_mes_base='2026-06-01'
campana=fecha_a_nombre('2026-05-01')
query = f"""
select dni as NumDoc, 1 as venta_target from SAMANTHA.dbo.Ventas_Target
where CAMPANA='Diners'
and CONVERT(DATE, FECHA) >= CONVERT(DATE, '{fecha_mes_base}')
AND CONVERT(DATE, FECHA) < DATEADD(MONTH, 1, CONVERT(DATE, '{fecha_mes_base}'))
   
"""
df_venta = pd.read_sql(query, engine_zeus)

df_target = df_tc.merge(
    df_venta,
    on='NumDoc',
    how='left'
)
df_final = df_target.merge(
    df,
    on='NumDoc',
    how='inner'
)
df_final = (
    df_final[df_final['venta_target'].isnull()]
    .drop(columns=['venta_target'])
)
df_final.rename(
    columns={
        'Importe Solicitado': 'Monto'
    },
    inplace=True
)
print(df_final.columns.tolist())

c:\Users\DATA\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

['NumDoc', 'TIPO_PRODUCTO', 'RETIRO', 'Canal', 'Autor', 'Subcanal', 'Motivo', 'Monto', 'fecha', 'hora']

In [72]:
df_final=df_final[df_final['Monto'].notnull()]

In [78]:
df_final[['TIPO_PRODUCTO','Canal', 'Monto', 'fecha']].head()

  TIPO_PRODUCTO              Canal    Monto       fecha
0           PPD  CANALES DIGITALES  41100.0  2026-06-04
1           PPD  CANALES DIGITALES  13800.0  2026-06-04
2           PPD     CONTACT CENTER   6000.0  2026-06-04

In [ ]:

total_monto_ppd = df_final.loc[
    df_final['TIPO_PRODUCTO'] == 'PPD',
    'Monto'
].sum()

total_ope_ppd = df_final.loc[
    df_final['TIPO_PRODUCTO'] == 'PPD',
    'Monto'
].count()

print(f'PPD | Monto total: {int(total_monto_ppd)} |  Total operaciones {int(total_ope_ppd)} ')

PPD | Monto total: 60900 |  Total operaciones 3

In [ ]:
# ruta_archivo = os.path.join(ruta_csv, 'PPD_plus.xlsx')
# df_list_filtrada.to_excel(ruta_archivo, index=False)

In [ ]:
list_dni = (
    df_final.loc[df_final['RETIRO'].isna(), 'NumDoc']
    .dropna()
    .drop_duplicates()
    .tolist()
)

in_clause = ",".join(f"'{x}'" for x in list_dni)

try:
    with engine_kishin.begin() as conn:
        query = f"""
            UPDATE DANTALION.dbo.Base_Maestra_Diners
            SET RETIRO = 'RETIRO'
            WHERE NumDoc IN ({in_clause})
                and CONVERT(DATE, fecha_envio) >= CONVERT(DATE, '{fecha_mes_base}')
                AND CONVERT(DATE, fecha_envio) < DATEADD(MONTH, 1, CONVERT(DATE, '{fecha_mes_base}'))
        """
        result = conn.execute(text(query))
        print("Filas actualizadas:", result.rowcount)

except Exception as e:
    print(e)

In [77]:
exec_query_sql(server_kishin, db_kishin, user_kishin, pwd_kishin, "tNumeros_Diners", "SP tNumeros diners")
exec_query_sql(server_zeus, "ODIN", user_zeus, pwd_zeus, "EXEC Sp_Actualizar_Diners", "SP actualizar diners Zeus")
exec_query_sql(server_sa, "ODIN", user_sa, pwd_sa, "EXEC Sp_Actualizar_Diners", "SP actualizar diners SA")

SP tNumeros diners | realizado | duración: 5.48 seg
SP actualizar diners Zeus | realizado | duración: 5.54 seg
SP actualizar diners SA | realizado | duración: 1.5 seg