### Retiro Fugas

In [1]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

In [2]:

server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

In [3]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

fecha_mes_base='2026-06-01'

filename='retiro_20260623.xlsx'
name_dni='DNI'

ruta_archivo = os.path.join(ruta_csv, filename)
df = pd.read_excel(ruta_archivo)

df[f"{name_dni}"] = (
    df[f"{name_dni}"]
    .astype(str)
    .str.zfill(8)
)

df = df.rename(columns={
    f'{name_dni}': 'NUMERO_DOCUMENTO'
})
df=df[["NUMERO_DOCUMENTO"]]
df.head()
server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
query = f"""
	select NUMERO_DOCUMENTO
	from DANTALION.dbo.Base_Maestra_Diners_TC_Vigente
    WHERE RETIRO IS NULL OR RETIRO =''
"""
df_tc = pd.read_sql(query, engine_kishin)

In [4]:
df = df.merge(df_tc, on='NUMERO_DOCUMENTO', how='inner')
list_dni = (
    df['NUMERO_DOCUMENTO']
    .dropna()
    .drop_duplicates()
    .tolist()
)
in_clause = ",".join(f"'{x}'" for x in list_dni)

in_clause

"'05586043','06782221','07688026','07752436','07788109','09488196','09507918','09856195','09950475','09985384','10106229','10348439','10425507','10610342','10616354','10622959','16675284','17592272','18197028','19893992','21527621','21532638','21863570','26717193','29734679','31772258','32965273','40067101','40077681','40122390','40123444','40225861','40359565','40461216','40524032','40582275','40608172','40640153','40713113','40820778','40948805','40965179','40976088','41075756','41249750','41311387','41340018','41347163','41420872','41468499','41668081','41712140','41726017','41761673','41895891','41896344','41931170','42070256','42264024','42282273','42580968','42745430','42947359','42963048','42973193','42978669','43035956','43086740','43106909','43208533','43235957','43248446','43250177','43274572','43351971','43416053','43494099','43505156','43575815','43615911','43618209','43671036','43678921','43853596','43885339','43906998','44066928','44120869','44260046','44323735','44350998','44367146','44399057','44404186','44418271','44460877','44547184','44553575','44673514','44755864','44793744','44803149','44819128','44836982','44918707','45050484','45168293','45274556','45275530','45392511','45394214','45444238','45446276','45449900','45459306','45460084','45492742','45614471','45797873','45813235','45859593','45862815','45869509','45888068','46006732','46057059','46148851','46159259','46162447','46190861','46223628','46351079','46417387','46567850','46596951','46641987','46659397','46671093','46684528','46686940','46710523','46753744','46836594','46868463','47109270','47115619','47181005','47238486','47265003','47296070','47301679','47338905','47341732','47349748','47384472','47452185','47461238','47497097','47520985','47553731','47559446','47656413','47717588','47797987','47945611','48052358','48437466','48463427','48515647','48591799','70006193','70024372','70043502','70178992','70190625','70251565','70254755','70255762','70273503','70275839','70370934','70384766','70410690','70429567','70432807','70448043','70483833','70508349','70540137','70550821','70611393','70650800','70795965','70825024','70874326','70876589','70886140','70895986','71032515','71211989','71250833','71253769','71296391','71332054','71497897','71517176','71673524','71737735','71776834','71787514','71889152','71951210','71985835','72012149','72028481','72028577','72039941','72044223','72112402','72156832','72175549','72180696','72191335','72214692','72224458','72225957','72352609','72367274','72395172','72437654','72440810','72484375','72503750','72517294','72520043','72539385','72546178','72582788','72606634','72630408','72639428','72660933','72667523','72733554','72816121','72878734','72878946','72894124','72896905','72905857','72940180','72972636','73105968','73252954','73271682','73310769','73435645','73450136','73454975','73596003','73610908','73622235','73682715','73753373','73821918','73824440','73857837','73864609','73874411','73941961','74062744','74063924','74070184','74218700','74279222','74441237','74611177','74644419','74729189','74733717','74834936','74842778','74871383','74916273','74942292','74960361','74982240','75266986','75385496','75549530','75551813','75797011','76092762','76128629','76189002','76241771','76413872','76506768','76523019','76589908','76783438','77241857','77668580','78288995','80062028','80141209'"

In [2]:
dni = [
    '09129265',
    '00124856',
    '09575813',
    '25746029',
    '08584203',
    '29290915',
    '00439542',
    '40071405',
    '44114467',
    '06684324',
    '25538137',
    '07005585',
    '80089100',
    '07484790',
    '44834522',
    '25796354',
    '08386328',
    '06982873',
    '07368416',
    '21527967',
    '06073492',
    '08408708',
    '10778046',
    '10778437',
    '08608380',
    '09092378',
    '08723115',
    '03503922',
    '09179434',
    '08640899',
    '09329750',
    '25859927',
    '09790593'
]

In [3]:
linea_sae = [
    15000,
    10500,
    10000,
    25000,
    12000,
    20000,
    25000,
    23400,
    13900,
    19700,
    17600,
    15500,
    20000,
    25000,
    24500,
    17100,
    25000,
    27600,
    15000,
    29600,
    25000,
    25000,
    13300,
    19600,
    28100,
    13900,
    20600,
    8000,
    25000,
    19200,
    15700,
    10000,
    26900
]

In [4]:
monto_desembolsar = [
    14330,
    8517,
    6667,
    17936,
    14217,
    8259,
    7605,
    20200,
    3856,
    8461,
    4575,
    5273,
    9310,
    3388,
    6979,
    10027,
    12270,
    6717,
    3026,
    5463,
    14544,
    7692,
    8954,
    2511,
    25400,
    4812,
    7881,
    6879,
    6200,
    5663,
    9223,
    4949,
    13422
]

In [5]:
pct_sae = [
    '025',
    '024',
    '025',
    '021',
    '024',
    '024',
    '021',
    '023',
    '021',
    '023',
    '021',
    '024',
    '022',
    '022',
    '021',
    '021',
    '021',
    '021',
    '025',
    '023',
    '023',
    '022',
    '024',
    '021',
    '021',
    '021',
    '023',
    '024',
    '030',
    '021',
    '021',
    '025',
    '021'
]

In [6]:
celular = [
    '979759584',
    '961730494',
    '985062074',
    '987970633',
    '982483149',
    '944204061',
    '947002626',
    '999887777',
    '955756485',
    '996803742',
    '942859677',
    '940687056',
    '991554986',
    '951418639',
    '988110547',
    '932016338',
    '992926393',
    '999990483',
    '978322607',
    '978518705',
    '988803498',
    '988138808',
    '972870364',
    '958509253',
    '996204487',
    '944645851',
    '999911558',
    '969142168',
    '994012885',
    '993562584',
    '986137257',
    '980032018',
    '971169868'
]

In [5]:
df.head()

  NUMERO_DOCUMENTO
0         43459252
1         75421815
2         46464077
3         72410120
4         46335049

In [7]:
df = pd.DataFrame({
    'CODDOC': dni,
    'security_phrase': linea_sae,
    'MONTO_DESEMBOLSAR': monto_desembolsar,
    'email': pct_sae,
    'phone_number': celular
})

# df['CODDOC'] = df['CODDOC'].astype(str)
# df['CELULAR'] = df['CELULAR'].astype(str)
# df['LINEA_SAE'] = df['LINEA_SAE'].astype(int)
# df['MONTO_DESEMBOLSAR'] = df['MONTO_DESEMBOLSAR'].astype(int)

# print(df.head())
# print(df.shape)

In [15]:
query = """
    SELECT 
        rtrim(ltrim(isnull(APELLIDO_PATERNO,'')))+' '+rtrim(ltrim(isnull(APELLIDO_MATERNO,'')))+' '+rtrim(ltrim(isnull(NOMBRE_1,'')))/*+' '+rtrim(ltrim(isnull(NOMBRE_2,''))) */as address1          ,DIRECCION as address2
        ,FEC_FACTURACION as address3
        ,CODDOC as vendor_lead_code 
        ,PROVINCIA as province
        ,DISTRITO as city
        ,fecha_envio
    FROM DANTALION.dbo.Base_Maestra_Cencosud_PPFF
    where CODDOC in(
        '09129265','00124856','09575813','25746029','08584203','29290915','00439542','40071405','44114467','06684324','25538137','07005585','80089100','07484790','44834522','25796354','08386328','06982873','07368416','21527967','06073492','08408708','10778046','10778437','08608380','09092378','08723115','03503922','09179434','08640899','09329750','25859927','09790593')
   and fecha_envio>='2026-05-01'     
"""
df_agenda = pd.read_sql(query, engine_kishin)

In [18]:
df = pd.DataFrame({
    'vendor_lead_code': dni,
    'security_phrase': linea_sae,
    'MONTO_DESEMBOLSAR': monto_desembolsar,
    'email': pct_sae,
    'phone_number': celular
})

In [16]:
print(df_agenda.columns.tolist())
print(df.columns.tolist())

['address1', 'address2', 'address3', 'vendor_lead_code', 'province', 'city', 'fecha_envio']
['CODDOC', 'security_phrase', 'MONTO_DESEMBOLSAR', 'email', 'phone_number']

In [19]:
df_agenda = df_agenda.merge(df, on='vendor_lead_code', how='inner')

In [26]:
print(df_agenda.columns.tolist())

['address1', 'address2', 'address3', 'vendor_lead_code', 'province', 'city', 'fecha_envio', 'security_phrase', 'MONTO_DESEMBOLSAR', 'email', 'phone_number']

In [29]:
# df_agenda['security_phrase'] = 'linea sae ' + df_agenda['security_phrase'].astype('Int64').astype(str)
df_agenda['comments'] = 'MONTO_DESEMBOLSAR ' + df_agenda['MONTO_DESEMBOLSAR'].astype('Int64').astype(str)
df_agenda.head()

,address1,address2,address3,vendor_lead_code,province,city,fecha_envio,security_phrase,MONTO_DESEMBOLSAR,email,phone_number,comments
0,VASQUEZ URDAY DE MANCHEGO LOLA,JIRON POSITOS SAN MARTIN DE PORRES 385 URBANIZ...,15,08584203,LIMA,SAN MARTIN DE PORRES,2026-06-01,linea sae 12000,14217,024,982483149,MONTO_DESEMBOLSAR 14217
1,CHAVEZ ESCALANTE ESLINDA,CALLE LOS CONQUISTADORES 13 DE OCTUBRE DPTO 0 ...,20,09129265,LIMA,SAN JUAN DE MIRAFLORES,2026-05-01,linea sae 15000,14330,025,979759584,MONTO_DESEMBOLSAR 14330
2,OCHOA CARDENAS JULIANA,AVENIDA LOS FRENOS LOS FRENOS URBANIZACION LOS...,10,00124856,LIMA,LA MOLINA,2026-05-01,linea sae 10500,8517,024,961730494,MONTO_DESEMBOLSAR 8517
3,MOGOLLON RONQUILLO FREDDY,CALLE JOSE PARODI 38,21,25746029,CALLAO,BELLAVISTA,2026-05-01,linea sae 25000,17936,021,987970633,MONTO_DESEMBOLSAR 17936
4,ROQUE GRANDA FRIDA,CALLE SN MARIA AUXILIADORA URBANIZACION MARIA ...,6,09575813,LIMA,SAN JUAN DE MIRAFLORES,2026-06-01,linea sae 10000,6667,025,985062074,MONTO_DESEMBOLSAR 6667

In [30]:
ruta_archivo = os.path.join(ruta_csv, 'agenda_01.xlsx')
df_agenda.to_excel(ruta_archivo, index=False)

In [ ]:
df['security'] = (
    'linea sae ' +
    df['LINEA_SAE'].astype(str) +
    ' ' +
    df['security'].fillna('')
)

In [6]:
df.count()

NUMERO_DOCUMENTO    42
dtype: int64

In [5]:
try:
    with engine_kishin.begin() as conn:
        query = f"""
            UPDATE DANTALION.dbo.Base_Maestra_Diners_TC
            SET RETIRO = 'AGENDAS_OTRO_CANAL'
            WHERE NUMERO_DOCUMENTO IN ({in_clause})
                and TRY_CONVERT(DATE, fecha_envio) >= TRY_CONVERT(DATE, '{fecha_mes_base}')
                AND TRY_CONVERT(DATE, fecha_envio) < DATEADD(MONTH, 1, TRY_CONVERT(DATE, '{fecha_mes_base}'))
        """
        result = conn.execute(text(query))
        print("Filas actualizadas:", result.rowcount)

except Exception as e:
    print(e)

Filas actualizadas: 306

In [8]:
exec_query_sql(server_kishin, db_kishin, user_kishin, pwd_kishin, "tNumeros_Diners_tc", "SP tNumeros diners TC")
exec_query_sql(server_zeus, "ODIN", user_zeus, pwd_zeus, "EXEC Sp_Actualizar_Diners_tc", "SP actualizar diners TC Zeus")
exec_query_sql(server_sa, "ODIN", user_sa, pwd_sa, "EXEC Sp_Actualizar_Diners_tc", "SP actualizar diners TC SA")

SP tNumeros diners TC | realizado | duración: 167.61 seg
SP actualizar diners TC Zeus | realizado | duración: 53.48 seg
SP actualizar diners TC SA | realizado | duración: 11.03 seg

In [ ]:


server_sql = server_zeus
db_sql = "SAMANTHA"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_zeus = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
fecha_mes_base='2026-06-01'
campana=fecha_a_nombre('2026-05-01')
query = f"""
select dni as NumDoc, 1 as venta_target from SAMANTHA.dbo.Ventas_Target
where CAMPANA='Diners'
and CONVERT(DATE, FECHA) >= CONVERT(DATE, '{fecha_mes_base}')
AND CONVERT(DATE, FECHA) < DATEADD(MONTH, 1, CONVERT(DATE, '{fecha_mes_base}'))
   
"""
df_venta = pd.read_sql(query, engine_zeus)

df_target = df_tc.merge(
    df_venta,
    on='NumDoc',
    how='left'
)
df_final = df_target.merge(
    df,
    on='NumDoc',
    how='inner'
)
df_final = (
    df_final[df_final['venta_target'].isnull()]
    .drop(columns=['venta_target'])
)
df_final.rename(
    columns={
        'Importe Solicitado': 'Monto'
    },
    inplace=True
)
print(df_final.columns.tolist())

c:\Users\DATA\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

['NumDoc', 'TIPO_PRODUCTO', 'RETIRO', 'Canal', 'Autor', 'Subcanal', 'Motivo', 'Monto', 'fecha', 'hora']

In [72]:
df_final=df_final[df_final['Monto'].notnull()]

In [78]:
df_final[['TIPO_PRODUCTO','Canal', 'Monto', 'fecha']].head()

  TIPO_PRODUCTO              Canal    Monto       fecha
0           PPD  CANALES DIGITALES  41100.0  2026-06-04
1           PPD  CANALES DIGITALES  13800.0  2026-06-04
2           PPD     CONTACT CENTER   6000.0  2026-06-04

In [ ]:

total_monto_ppd = df_final.loc[
    df_final['TIPO_PRODUCTO'] == 'PPD',
    'Monto'
].sum()

total_ope_ppd = df_final.loc[
    df_final['TIPO_PRODUCTO'] == 'PPD',
    'Monto'
].count()

print(f'PPD | Monto total: {int(total_monto_ppd)} |  Total operaciones {int(total_ope_ppd)} ')

PPD | Monto total: 60900 |  Total operaciones 3

In [ ]:
# ruta_archivo = os.path.join(ruta_csv, 'PPD_plus.xlsx')
# df_list_filtrada.to_excel(ruta_archivo, index=False)

In [ ]:
list_dni = (
    df_final.loc[df_final['RETIRO'].isna(), 'NumDoc']
    .dropna()
    .drop_duplicates()
    .tolist()
)

in_clause = ",".join(f"'{x}'" for x in list_dni)

try:
    with engine_kishin.begin() as conn:
        query = f"""
            UPDATE DANTALION.dbo.Base_Maestra_Diners
            SET RETIRO = 'RETIRO'
            WHERE NumDoc IN ({in_clause})
                and CONVERT(DATE, fecha_envio) >= CONVERT(DATE, '{fecha_mes_base}')
                AND CONVERT(DATE, fecha_envio) < DATEADD(MONTH, 1, CONVERT(DATE, '{fecha_mes_base}'))
        """
        result = conn.execute(text(query))
        print("Filas actualizadas:", result.rowcount)

except Exception as e:
    print(e)

In [77]:
exec_query_sql(server_kishin, db_kishin, user_kishin, pwd_kishin, "tNumeros_Diners", "SP tNumeros diners")
exec_query_sql(server_zeus, "ODIN", user_zeus, pwd_zeus, "EXEC Sp_Actualizar_Diners", "SP actualizar diners Zeus")
exec_query_sql(server_sa, "ODIN", user_sa, pwd_sa, "EXEC Sp_Actualizar_Diners", "SP actualizar diners SA")

SP tNumeros diners | realizado | duración: 5.48 seg
SP actualizar diners Zeus | realizado | duración: 5.54 seg
SP actualizar diners SA | realizado | duración: 1.5 seg