In [89]:
import sys 
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

port_mysql = '3306'
user_valentina = "flazo"
pwd_valentina = "T4rg3t2026$$"
server_valentina = "db.mastermold.dev"
db_valentina = "crm_target"
filename_retiro_telef='blacklist_celulares.txt'
fecha_ref='2026-05-01'
tb_name='alfcc_clientes'
periodo='mayo 2026'


def obtener_dni_cliente(tb_name,periodo):
    query = f"""
    SELECT 
    DISTINCT 
    NUMERO_DOCUMENTO as col_01
    FROM {tb_name}
    WHERE cl_base = '{periodo}'
    and cl_estado=1
    """

    df_retiro_dni = pd.read_sql(query, engine_mysql)

    df_retiro_dni["col_01"] = (
        df_retiro_dni["col_01"]
        .astype(str)
        .str.zfill(8)
    )
    return df_retiro_dni

def quitar_telf_enriquecidos(df_retiro_telef,engine_mysql,tb_name):

    if df_retiro_telef.empty:
        print("vacío")
        return
    list_numero = (
        df_retiro_telef['col_02']
        .drop_duplicates()
        .tolist()
    )


    in_clause = ",".join(f"'{x}'" for x in list_numero)
    print(in_clause)

    for col in cols_tel:

        query = f"""
        UPDATE crm_target.{tb_name}
        SET {col} = 0
        WHERE cl_base = 'mayo 2026'
        AND cl_estado = 1
        AND {col} IN ({in_clause})
        """

        with engine_mysql.begin() as conn:
            result = conn.execute(text(query))
            print(f"{col}: {result.rowcount} filas actualizadas")

def tb_retiro_telef(query, engine_mysql,cols_tel,df_list,df_venta):
    df_base_mes = pd.read_sql(query, engine_mysql)

    df = df_base_mes.melt(
        id_vars='col_01',
        value_vars=cols_tel,
        var_name='tipo_telf',
        value_name='col_02'
    )
    df['col_02'] = (
        df['col_02']
        .fillna(0)            
        .astype('int64')        
        .astype(str)              
    )
    df = df[
        (df['col_02'].notna()) &
        (df['col_02'] != '') &
        (df['col_02'] != '0') &
        (df['col_02'].str.len() == 9) &
        (df['col_02'].str.startswith('9'))
    ]


    df_list['col_02'] = (
        df_list['col_02']
        .fillna(0)
        .astype('int64')        
        .astype(str)              
    )

    df = df .merge(
        df_list,
        on="col_02",
        how="inner"
    )

    ids_quitar = df_venta['col_01'].drop_duplicates()

    df= df[
        ~df['col_01'].isin(ids_quitar)
    ]
    return df.drop_duplicates(
        subset=['col_01'],
        keep='last'
    )

def update_base_cliente(engine_mysql,df,tb_name):
    if df.empty:
        print("vacio")
        return
    query = """
    DELETE FROM crm_target.tb_temporal
    """

    with engine_mysql.begin() as conn:
        result = conn.execute(text(query))
        print("Filas eliminadas:", result.rowcount)

    df[['col_01','col_02','col_03']].to_sql(
        name="tb_temporal",
        con=engine_mysql,
        if_exists="append",
        index=False,
        chunksize=1000
    )

    query = f"""
    UPDATE crm_target.{tb_name} a
    INNER JOIN crm_target.tb_temporal b
        ON a.NUMERO_DOCUMENTO = b.col_01 
    SET 
        a.cl_estado = b.col_03,
        a.estado = b.col_02
    WHERE 
        a.cl_base = 'mayo 2026'
    """

    with engine_mysql.begin() as conn:
        result = conn.execute(text(query))
        print("Filas afectadas:", result.rowcount)

def preparar_info(df_list,df_base,df_venta,tipo_retiro):
    if df_list.empty:
        print("vacio")
        return
    df_list['col_01'] = (
        df_list['col_01']
        .fillna(0)            
        .astype('int64')        
    )
    df_list = df_list[df_list['col_01'] != 0].copy()
    df_list['col_01'] = (
        df_list['col_01']
        .astype(str)
        .str.zfill(8)
    )
    df_list = df_list.merge(
        df_base,
        on="col_01",
        how="inner"
    )

    ids_quitar = df_venta['col_01'].drop_duplicates()

    df_list= df_list[
        ~df_list['col_01'].isin(ids_quitar)
    ]
    df_list['col_02']=tipo_retiro
    df_list['col_03']='3'
    print(f"df_list filas: {df_list.shape[0]}")
    return df_list

def venta_periodo(fecha_ref):
    query = f"""
    select distinct dni as col_01 from crm_target.alfcc_ventas
    where fecha>='{fecha_ref}'
    """

    return pd.read_sql(query, engine_mysql)


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

In [ ]:

filePath = os.path.join(ruta_csv, filename_retiro_telef)
df_list = pd.read_csv(filePath)

reemplazo = {
    'CELULAR': 'col_02',
}
df_list = df_list.rename(columns=reemplazo)

df_venta=venta_periodo(fecha_ref)

In [ ]:

# evaluar numero enriquecidos

cols_tel = ['cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10']

query_telf_enriquecidos = """
SELECT  NUMERO_DOCUMENTO as col_01, cl_telf7, cl_telf8, cl_telf9, cl_telf10 
FROM crm_target.alfcc_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_retiro_telef_enriquecidos=tb_retiro_telef(query_telf_enriquecidos, engine_mysql,cols_tel,df_list,df_venta)
quitar_telf_enriquecidos(df_retiro_telef_enriquecidos,engine_mysql)

'951892894','971779220','910934217','959935183','960841136','981243142','953275043','962361246','986523837','985484839','936918089','938853248','959310306','936308835','943014102','946555791','922690772','990156898','957749276','959359280','979193705','973620677','944375330','969706461','912133622','962530757','981666715','937637376','971310287','947055748','932978902','998226665','952318634','914627600','980734302','964387676','940863418','966808055','922145823','956163993','936651667','950690773','995918182','947004975','968960964','973698121'
cl_telf7: 3 filas actualizadas
cl_telf8: 30 filas actualizadas
cl_telf9: 11 filas actualizadas
cl_telf10: 2 filas actualizadas

In [ ]:

# evaluar numero 

cols_tel = ['cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4','cl_telf5', 'cl_telf6','cl_movil', 'cl_celular', 'cl_telefono']

query_telf = """
SELECT  NUMERO_DOCUMENTO as col_01,cl_telf1, cl_telf2, cl_telf3, cl_telf4, cl_telf5, cl_telf6,cl_movil, cl_celular, cl_telefono 
FROM crm_target.alfcc_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_retiro_telef=tb_retiro_telef(query_telf, engine_mysql,cols_tel,df_list,df_venta)

df_retiro_telef['col_02']='Retirar Telf'
df_retiro_telef['col_03']='3'

update_base_cliente(engine_mysql,df)

Filas eliminadas: 1
Filas afectadas: 1

In [88]:

filename='blacklist_dni.txt'
tipo_retiro='Retirar Blacklist'

obtener_dni_cliente(tb_name,periodo)
filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)
df_list.rename(columns={'DNI': 'col_01'}, inplace=True)

print(df_list.columns.tolist())

['col_01']

In [ ]:
df=preparar_info(df_list,df_retiro_dni,df_venta,tipo_retiro)
update_base_cliente(engine_mysql,df)

df_list filas: 1
Filas eliminadas: 1
Filas afectadas: 1

     col_01             col_02 col_03
0  10218026  Retirar Blacklist      3

In [ ]:
filename='blacklist_dni.txt'
tipo_retiro='Retirar Blacklist'

obtener_dni_cliente(tb_name,periodo)
filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)
df_list.rename(columns={'DNI': 'col_01'}, inplace=True)

df_list.head(2)

     col_01
0  46654470
1  75469965

In [ ]:
df=preparar_info(df_list,df_retiro_dni,df_venta,tipo_retiro)
update_base_cliente(engine_mysql,df)

In [ ]:
tb_name='alfcc_clientes'
periodo='mayo 2026'
filename='202605_BAE_RETIRO.txt'
tipo_retiro='Retirar BAE'
# evaluar numero 

obtener_dni_cliente(tb_name,periodo)
filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)
df_list.rename(columns={'DNI': 'col_01'}, inplace=True)

df_list.columns.tolist()

In [ ]:
df=preparar_info(df_list,df_retiro_dni,df_venta,tipo_retiro)
update_base_cliente(engine_mysql,df)

In [83]:
exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC VALENTINA.DBO.ALFCC_BASE_VALENTINA", "SP actualizar BASE CREDICASH")

SP actualizar BASE CREDICASH | realizado | duración: 90.36 seg

In [2]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

In [5]:
print(
    df_venta['dni']
    .drop_duplicates()
    .tolist()
)

['25852137', '44426603', '20029022', '40579033', '23967029', '74405803', '23983904', '05232951', '03361702', '45403836', '46774549', '02719548', '27410504', '26683936', '71992333', '60163637', '01049208', '00838704', '41873842', '45095217', '40421730', '73760117', '47037111', '32108912', '45235705', '21504716', '15432337', '15433829', '73576237', '18072514', '16420897', '17948854', '44360032', '43054854', '02601400', '07982417', '45110406', '22506216', '76141639', '09257700', '02386913', '70042019', '07075817', '41954118', '43264418', '47583432', '73270756', '18125310', '29440435', '47056135', '32136518', '19553044', '01137759', '44041454', '04045236', '48189736', '10755149', '45052515', '02835738', '73339751', '41547617', '42453133', '76518732', '16777919', '45308738', '43177900', '44073750', '22311147', '00092431', '76040836', '43899650', '80231853', '45071437', '80158850', '26958644', '00249233', '48367054', '40073657', '43280854', '43705143', '07458148', '03568731', '41986218', '41589327', '42124134', '03585607', '41712628', '80230510', '72940516', '20023242', '03671314', '48080941', '01038815', '47580505', '00443116', '10631008', '22246302', '46505301', '43775531', '45055429', '31678818', '47815112', '47294230', '08897132', '40067819', '40571943', '16012730', '71459717', '09790004', '42621118', '72390411', '07458615', '47556104', '04642514', '72388546', '19881932', '07042114', '26682232', '19182086', '21856116', '03620256', '44531602', '16741887', '20113736', '44021030', '73423978', '18160736', '05245622', '42629792', '47641189', '47080579', '46447743', '47163610', '47508518', '33672945', '22277841', '42577978', '42025683', '43213360', '44176519', '15945907', '80525162', '22428134', '48510795', '26960627', '73903629', '29648224', '29680160', '00976663', '21081539', '19980019', '70305805', '32797029', '22312229', '45876919', '28226353', '04342252', '42533907', '22314552', '10440454', '05229904', '70231221', '10167657', '48261033', '28804848', '42767355', '47626032', '31674345', '40177644', '27703942', '44538148', '70139345', '48022137', '00114234', '73792947', '45598451', '43515059', '43422130', '76261350', '09328731', '15724040', '43353640', '02779343', '43845148', '41669148', '47494857', '41238348', '16800326', '40814791', '40515506', '45253640', '42501838', '40708724', '32939819', '10778287', '08685066', '40750498', '47027053', '77178646', '02866937', '42789345', '75969340', '47965548', '05340434', '43328516', '33247507', '40048930', '42341637', '19429690', '08431055', '09927101', '20963815', '07321922', '42123332', '28223147', '43646933', '30417737', '45900821', '17446345', '44256617', '22700766', '10585253', '19557605', '42087209', '47374140', '25427437', '44784415', '70266424', '07525259', '41066147', '73111615', '41374319', '43729302', '47974039', '41233484', '42290543', '47080005', '47573432', '80416001', '41118815', '41212521', '43538082', '32952537', '00484056', '76434106', '46909836', '45375432', '41073858', '31654481', '43816446', '28119184', '15757107', '00447834', '21079785', '42214305', '73381445', '72028354', '45352867', '46673202', '47966615', '40157722', '40376716', '09329101', '76136714', '40014348', '26926390', '41197897', '18117377', '00442128', '46669524', '72277366', '09280630', '40948057', '15758032', '46568432', '45057912', '29237328', '07682791', '40634144', '46905001', '70610820', '76306776', '42896714', '40056691', '43497739', '61707810', '41884886', '32486409', '03643487', '20556499', '70822943', '43429661', '09748950', '41524160', '44674227', '70142114', '29337217', '16610117', '48039815', '70007414', '43786151', '47258063', '17636142', '44296019', '25783712', '77393214', '27385958', '01120813', '70255279', '42768533', '45717568', '45881076', '22296514', '31034507', '18825151', '32833040', '47046859', '29650693', '19237835', '42408135', '40126886', '47113514', '20080178', '46249614', '44746319', '43588833', '43883842', '70198016', '06770718', '75531590', '00797839', '10259530', '46746636', '02846948', '72958054', '02681139', '47330234', '05335558', '21123844', '43805854', '44457945', '47929633', '40220732', '48090637', '76230451', '41409533', '44068342', '47115552', '74239257', '19572649', '16425231', '01036738', '43039446', '22271336', '80002031', '09728654', '29632540', '77167156', '32805536', '71667845', '42330332', '78518357', '47680337', '74599332', '47271041', '77529339', '26641152', '80495334', '45675951', '47233652', '48539850', '44996541', '40761951', '27712241', '01188847', '73892445', '44334955', '23985132', '76252253', '27578737', '05618746', '27667634', '41828554', '47026546', '03636646', '40645736', '76082551', '42626652', '44806855', '45701456', '45478059', '76827233', '41487430', '46847535', '47651244', '08582059', '43917941', '40533156', '70411736', '05375430', '75378458', '46563135', '71248834', '77126145', '76638152', '41858138', '43024845', '29652936', '44455234', '45492236', '41311242', '60381744', '30426142', '70570230', '32128641', '70565234', '09754534', '47602635', '72304544', '47270131', '47810034', '70217545', '44850574', '74053248', '46822834', '46946216', '75084916', '19968402', '40346000', '09888842', '40089317', '20102319', '00115049', '45617146', '15352916', '44857936', '43253245', '18145794', '21511056', '77063317', '05342952', '46196333', '70235233', '31477788', '19965612', '09290694', '22314518', '18044038', '42514434', '16691145', '19578532', '25748646', '44428500', '19404354', '18143643', '45313041', '42817168', '18884545', '15409819', '27856619', '70868130', '43406519', '45935471', '70278041', '40064863', '19540755', '47935966', '44055537', '42489658', '20565935', '43993698', '30575824', '19332439', '16759430', '26663092', '45842510', '26720824', '22465031', '16632324', '05580325', '29600585', '76957140', '26662706', '22249996', '47375687', '31650744', '15707393', '41803533', '45973749', '29607459', '15643540', '73436533', '44078452', '43892253', '26631751', '02662734', '42122730', '21799956', '43523943', '43105432', '75738049', '16682737', '16667907', '19325401', '71790450', '76656832', '08308937', '02724539', '31040667', '43282693', '80663055', '15842138', '70078656', '41803535', '76632144', '71577867', '72309422', '29474102', '18111222', '45652086', '48858327', '23957715', '29625094', '10155715', '29624515', '45980923', '01856417', '80339244', '48276436', '03688667', '44843151', '40930218', '70059709', '21577946', '45771054', '70324528', '21879532', '77799040', '43302525', '44830146', '00253650', '44840681', '47636093', '26731994', '44416777', '42778731', '27046918', '47812154', '43900718', '47850014', '02876239', '75940591', '01128032', '09751005', '40386334', '28272117', '48116215', '41933754', '41114539', '23981555', '47533594', '27719674', '76099232', '41972613', '70555245', '47095623', '70499470', '25817528', '10068025', '15428460', '80534783', '40626032', '48669918', '03361330', '21116715', '19037791', '80633857', '15847652', '31668401', '45957045', '15986539', '42380348', '01127638', '47966677', '10536654', '04809541', '00238436', '28292047', '80634331', '41915891', '42069429', '43085716', '42880434', '43715951', '30419915', '25218944', '29277021', '43284485', '09206108', '43430617', '07473915', '07500527', '22414064', '18151739', '18187064', '10118969', '42313492', '44344733', '09091912', '44371524', '46203508', '45122701', '44100447', '71539434', '19566134', '41898591', '10723194', '22493431', '20049614', '23945198', '32844966', '07464116', '27847664', '80307638', '40274378', '09832023', '07642989', '03473514', '26683170', '40958316', '40735797', '22669939', '40744717', '23006529', '45055100', '20424126', '05071058', '32732432', '80565816', '33265540', '41626129', '80639217', '43233843', '40488445', '42735655', '19888832', '23170866', '00416380', '44405237', '21109220', '41229263', '46046438', '03652819', '08301518', '45663620', '27258799', '42486098', '48756257', '40574016', '15726215', '47950666', '18840684', '80253118', '70112354', '71849189', '48075421', '00792391', '46559260', '40049696', '45507999', '20590540', '46489656', '44251259', '72105911', '43799140', '47735208', '63323215', '41429245', '40603329', '47095029', '43032461', '76248945', '43086617', '45938308', '19525213', '27247516', '19207519', '48441225', '02817138', '44567432', '45716443', '44688083', '72992510', '44917974', '47666595', '80644690', '41649581', '70450285', '43460241', '29481440', '28267692', '76509408', '42999171', '70161056', '71888204', '45192337', '32738602', '41152017', '02870370', '05399053', '22453750', '43446529', '42345932', '19322263', '44820829', '72323940', '04055132', '43920403', '41967403', '10098030', '47000318', '72812553', '48065045', '17638643', '46615008', '48166307', '80352303', '46479932', '44079660', '03696381', '04080523', '48380221', '76691812', '42614301', '08371194', '47356056', '32893949', '45151542', '06858615', '41498575', '45327602', '41861852', '44483059', '44406503', '19916595', '77155228', '45989015', '32821145', '47906075', '80155019', '21532380', '28266358', '46923618', '48238365', '08991604', '41497214', '08547229', '42782598', '70217304', '45721247', '46225988', '71094226', '43311986', '48258592', '80582815', '45236333', '21579068', '47601092', '70979025', '26935006', '44943020', '40959308', '44052336', '46081819', '72957095', '20584216', '80076777', '22504315', '41886311', '22962282', '23372593', '44377610', '43145888', '29330315', '46922717', '16486555', '44627157', '16655006', '40297914', '47594473', '48398501', '43359492', '32387721', '72117106', '72904038', '30416857', '76445249', '44064135', '70289540', '71550756', '41959237', '19259438', '48876854', '43338417', '03657716', '00099468', '70929615', '10744015', '41405518', '19576437', '73242346', '00514839', '40841001', '22270757', '16158158', '44676616', '73379632', '45999314', '71872229', '01862886', '32952034', '44191544', '15385251', '32132431', '41165933', '43460718', '42487721', '17453416', '47916615', '32613148', '49035050', '00493792', '43804436', '43834438', '45780128', '30856616', '44591893', '20014297', '70132295', '42376219', '01034391', '40333092', '43468691', '00967397', '48409197', '40340594', '01129094', '16660316', '28287115', '40635191', '28316696', '75822216', '43846091', '19802196', '04824116', '18081092', '47173316', '40761699', '42066298', '70060734', '47705314', '32963851', '19224718', '45473418', '47760632', '40622994', '74030316', '47067233', '32845338', '26961038', '29571619', '29380316', '04647846', '22075715', '72931692', '45446598', '19188940', '71999716', '43964115', '47769897', '25860090', '43223017', '75090145', '73350284', '45197033', '45302018', '41547412', '46539651', '45066417', '44607162', '40059634', '30431756', '43975495', '26962113', '16747746', '71120015', '10450418', '48513214', '46626510', '74620017', '80202450', '22498047', '01174138', '31653039', '48097239', '75884459', '18148744', '43642330', '40882101', '42191029', '76401862', '02810625', '45882655', '47965931', '43270492', '21484816', '40216095', '05356138', '73812455', '73083763', '41081807', '00998440', '46409857', '70175545', '47989723', '43373408', '05376616', '41534301', '41155814', '43503145', '45375526', '26641030', '43260390', '47057344', '45996751', '44705952', '23171574', '74812342', '47393024', '21851957', '47786191', '47224810', '71800132', '74659114', '45100840', '47353151', '09228639', '43394377', '47582514', '19535601', '75155799', '46889802', '29259714', '07164647', '33413256', '43752114', '02762118', '76190114', '42146715', '43319502', '42077909', '40726400', '41642397', '42878930', '32901134', '43268010', '41011594', '70333059', '09096017', '44407959', '04066842', '44359801', '73342254', '43565029', '44871339', '10034753', '32381154', '43804358', '19252030', '72423543', '45029130', '17987866', '70880212', '44400089', '33431868', '80530689', '21472119', '41135428', '27720832', '18147480', '73434330', '73657159', '45469136', '40872343', '43062124', '40422902', '17553343', '19219636', '21299445', '02865957', '71976793', '46828731', '28066596', '72939202', '40713934', '43665717', '25721612', '42983076', '41900296', '19568045', '47680644', '29515146', '47077694', '45170955', '76794853', '44432538', '40137290', '18047848', '19422728', '70009419', '80544446', '76767757', '46423521', '42671190', '19526503', '07519646', '47372133', '48772118', '45957297', '29447617', '43824785', '46655833', '70834884', '01012049', '31665355', '80275454', '31657519', '19662738', '42638349', '32857240', '23007215', '10683216', '70916514', '24004812', '45386823', '42713994', '80643041', '42031938', '75320053', '42553551', '40687393', '47170391', '08031915', '74976735', '42847616', '00983579', '40922449', '45616055', '45387996', '10520770', '48021563', '16628359', '07750615', '16021265', '42530324', '21415035', '48098098', '46282861', '70224350', '23957215', '00176427', '42940608', '45477856', '03486415', '43258393', '42506713', '09059206', '42969997', '42928714', '40046648', '02405852', '32902390', '07574550', '17450742', '44230531', '45110568', '30953643', '44292966', '42310980', '42984319', '30419959', '04631959', '16125011', '43014418', '40812858', '19326897', '22311092', '45121308', '76968697', '29425717', '48353507', '40150049', '71903555', '45507651', '70431817', '48272463', '22664595', '70576842', '72555659', '19559660', '42313005', '74150290', '10255539', '09701439', '44306716', '43286894', '80560332', '74970636', '00322716', '70214250', '70005568', '48353954', '45627558', '46777535', '25002259', '77166145', '47954716', '10801603', '10666457', '47255493', '46459595', '40275739', '46992784', '09328797', '25318479', '71487506', '46208388', '25563848', '05395556', '19418841', '29736018', '42600717', '43524220', '27730342', '43044581', '09240434', '47033759', '46852635', '44661700', '02801340', '40532118', '31653610', '72361736', '80622524', '03305028', '23900312', '41390554', '09619235', '27153131', '47726941', '01091939', '80300619', '00824705', '05335977', '31657172', '43017582', '42440232', '05389687', '44986444', '76647859', '42299751', '77414659', '45146014', '22479938', '47777220', '44549330', '45027355', '41430450', '16011170', '43043801', '74797841', '47670331', '71703360', '73863245', '40465600', '06814793', '71998591', '47837399', '45651850', '10707340', '43326110', '40060410', '73096133', '03361158', '42967738', '41182037', '33790615', '15989414', '44113262', '47821525', '76376503', '10518130', '71197317', '04748107', '10725130', '46804691', '09741544', '73077347', '41692330', '44353547', '31653465', '16692741', '80263946', '20983817', '42975748', '32940807', '07610816', '45030294', '08901525', '76267754', '71944335', '46130034', '42756287', '31616161', '22303533', '46810417', '41469083', '27565807', '02804499', '44345526', '41788291', '01149610', '45962191', '76570401', '71378543', '45711925', '17592102', '25815792', '17585014', '43485334', '09551771', '43148748', '27429215', '46364245', '46370574', '72197037', '40425110', '73449498', '44392249', '46063618', '45483575', '22097268', '80330737', '42893942', '29634315', '76638505', '74089537', '47985143', '47195841', '45561824', '48255241', '40951016', '21136847', '41966876', '02754716', '42160553', '42204259', '72233907', '21499134', '21537849', '45834427', '42738939', '45259600', '42473005', '80221339', '42042523', '70201585', '43988037', '74689719', '47603648', '48210821', '41962743', '09100675', '77467733', '40532757', '70017748', '73438938', '40913499', '73201356', '25768334', '10510226', '46760215', '09402769', '04308448', '75177166', '00101940', '44363155', '48607714', '28217913', '78201273', '72647456', '43641036', '20960416', '73097567', '02827139', '41808618', '21805215', '18157233', '32905656', '45854165', '42347168', '44076568', '03561742', '23686648', '17950767', '32643268', '31626716', '45661916', '31037331', '74082542', '80629315', '41726074', '42912413', '70154057', '43534650', '45065643', '01122750', '42210753', '47366255', '42664917', '42762994', '42582449', '73696018', '42518207', '22241116', '43864138', '26622325', '25730914', '43180427', '71494246', '40461374', '22655862', '09255128', '46579888', '44859342', '45479216', '43863231', '40826311', '41978948', '75543432', '71655617', '01012045', '20568690', '43146999', '46625690', '40060677', '40686646', '17579057', '45991919', '40260772', '25446919', '73488489', '78971217', '72778347', '43162934', '33672948', '44012246', '80497236', '75627260', '43309616', '46458032', '44970632', '48593049', '22307542', '26674533', '45921135', '43712348', '40469790', '47686034', '28296337', '27664859', '45292504', '73074831', '80226803', '70226317', '46055817', '43831318', '72021608', '01084893', '43223641', '46073330', '44260329', '45400476', '42993115', '43047218', '01271416', '32984243', '76786802', '70000808', '80649660', '70096050', '74300000', '44060420', '62097353', '48095431', '48177068', '48507931', '30426527', '20587817', '10362406', '74620330', '16637015', '29679217', '40186514', '47606355', '33260990', '44700408', '42751002', '25559618', '47274695', '10708791', '42742597', '22515744', '41236693', '27727038', '41268715', '44032726', '41858195', '41102889', '31032030', '40446333', '02831535', '41713748', '24294031', '47939931', '07497950', '10706460', '47501538', '40414906', '40258807', '46234434', '70137218', '07514949', '41674725', '21538092', '29613615', '44789297', '43199915', '02877699', '41704116', '43649600', '44816596', '41154870', '42885142', '29456571', '32912638', '46384201', '44094259', '40817018', '40171104', '72959219', '46786916', '42456796', '17580750', '19568386']

In [3]:

ruta_archivo = os.path.join(ruta_csv, 'llamadas_01.xlsx')
df_credicash.to_excel(ruta_archivo, index=False)

ruta_archivo = os.path.join(ruta_csv, 'maquina.xlsx')
df_llamada.to_excel(ruta_archivo, index=False)

### evaluar numero enriquecidos

In [2]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT  NUMERO_DOCUMENTO, cl_telf8, cl_telf9, cl_telf10 
FROM crm_target.alfcc_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_dni = pd.read_sql(query, engine_mysql)

cols_tel = [
    'cl_telf8','cl_telf9','cl_telf10'
]

df_long = df_dni.melt(
    id_vars='NUMERO_DOCUMENTO',
    value_vars=cols_tel,
    var_name='tipo_telf',
    value_name='CELULAR'
)
df_long['CELULAR'] = (
    df_long['CELULAR']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)
df_long = df_long[
    (df_long['CELULAR'].notna()) &
    (df_long['CELULAR'] != '') &
    (df_long['CELULAR'].str.len() == 9) &
    (df_long['CELULAR'].str.startswith('9'))
]

In [3]:
filename='blacklist_celulares.txt'
filePath = os.path.join(ruta_csv, filename)

df_list = pd.read_csv(filePath)
df_list['CELULAR'] = (
    df_list['CELULAR']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)
df_list.head()

     CELULAR
0  900000202
1  900000323
2  900000531
3  900000910
4  900001728

In [4]:
df_list['CELULAR'] = df_list['CELULAR'].astype(str)

df_list = df_list.merge(
    df_long,
    on="CELULAR",
    how="inner"
)

print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 4

In [5]:
print(
    df_list['CELULAR']
    .drop_duplicates()
    .tolist()
)

['981296029', '987158466', '987899306', '998986061']

In [ ]:
from sqlalchemy import text
list_numero=['981296029', '987158466', '987899306', '998986061']
query = f"""
update crm_target.alfcc_clientes
set cl_telf8=0
where cl_base='mayo 2026'
and cl_estado=1
and cl_telf8 in(
{list_numero}
)
"""
with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas actualizadas:", result.rowcount)

Filas actualizadas: 11

In [7]:
list_numero=['981296029', '987158466', '987899306', '998986061']

In [8]:
print(list_numero.tolist())

AttributeError: 'list' object has no attribute 'tolist'

In [9]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 464

## actualizar retiro telef

In [ ]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT  NUMERO_DOCUMENTO,cl_telf1, cl_telf2, cl_telf3, cl_telf4, cl_telf5, cl_telf6, cl_telf7,cl_movil, cl_celular, cl_telefono 
FROM crm_target.alfcc_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_dni = pd.read_sql(query, engine_mysql)

cols_tel = [
    'cl_telf1','cl_telf2','cl_telf3','cl_telf4','cl_telf5',
    'cl_telf6',
    'cl_movil','cl_celular','cl_telefono'
]

df_long = df_dni.melt(
    id_vars='NUMERO_DOCUMENTO',
    value_vars=cols_tel,
    var_name='tipo_telf',
    value_name='CELULAR'
)
df_long['CELULAR'] = (
    df_long['CELULAR']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)
df_long = df_long[
    (df_long['CELULAR'].notna()) &
    (df_long['CELULAR'] != '') &
    (df_long['CELULAR'].str.len() == 9) &
    (df_long['CELULAR'].str.startswith('9'))
]

In [3]:
filename='202605_BAE_RETIRO.txt'
filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)
df_list.head()

        DNI
0  46654470
1  75469965
2  72765590
3  31620060
4  45777360

In [ ]:
filename='blacklist_celulares.txt'
filePath = os.path.join(ruta_csv, filename)

df_list = pd.read_csv(filePath)
df_list['CELULAR'] = (
    df_list['CELULAR']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)
df_list.head()

     CELULAR
0  900000202
1  900000323
2  900000531
3  900000910
4  900001728

In [12]:
df_list['CELULAR'] = df_list['CELULAR'].astype(str)

df_list = df_list.merge(
    df_long,
    on="CELULAR",
    how="inner"
)

print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 901

In [13]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 0

In [14]:
reemplazo = {
    'NUMERO_DOCUMENTO': 'col_01',
}
df_list = df_list.rename(columns=reemplazo)

df_list['col_02'] ='Retiro Telf'
df_list['col_03'] ='3'
df_list .head()

     CELULAR    col_01    tipo_telf       col_02 col_03
0  900093328  42034808     cl_telf6  Retiro Telf      3
1  900584636  29683346     cl_telf6  Retiro Telf      3
2  900620475  70012357     cl_telf6  Retiro Telf      3
3  901076318  20520227     cl_telf1  Retiro Telf      3
4  901076318  20520227  cl_telefono  Retiro Telf      3

In [15]:
df_list.head()

     CELULAR    col_01    tipo_telf       col_02 col_03
0  900093328  42034808     cl_telf6  Retiro Telf      3
1  900584636  29683346     cl_telf6  Retiro Telf      3
2  900620475  70012357     cl_telf6  Retiro Telf      3
3  901076318  20520227     cl_telf1  Retiro Telf      3
4  901076318  20520227  cl_telefono  Retiro Telf      3

In [16]:
df_list = df_list.drop_duplicates(
    subset=['col_01'],
    keep='last'
)
df_list.count()

CELULAR      684
col_01       684
tipo_telf    684
col_02       684
col_03       684
dtype: int64

In [17]:

df_list["col_01"] = (
    df_list["col_01"]
    .astype(str)
    .str.zfill(8)
)

In [18]:

df_list[['col_01','col_02','col_03']].to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

684

In [ ]:
df_list['CELULAR'] 


df_list.to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

     CELULAR
0  900000202
1  900000531
2  900001728
3  900003782
4  900004400

In [11]:
print(
    df_list['CELULAR']
    .drop_duplicates()
    .tolist()
)

['901914305', '902876236', '902893436', '906573460', '912676290', '913300840', '914050257', '914647039', '920033871', '920233049', '920309404', '920569770', '920574786', '920637180', '921729655', '922804891', '923802595', '924261113', '924470592', '926579945', '926931724', '926974122', '927687059', '927910705', '927987418', '928919344', '931740138', '932130621', '932813141', '932941966', '934573818', '935339850', '936052202', '936447502', '936898041', '937173655', '937202437', '937518944', '938132787', '938171773', '939114190', '939173337', '939187202', '939317200', '939373234', '939586724', '939667425', '940781497', '941260823', '941265695', '941276327', '941288702', '941339959', '941467158', '941792920', '941824681', '941897091', '941909576', '942199388', '942993339', '942997731', '943082431', '943425401', '944128135', '944181154', '944415166', '944625644', '944641740', '944726273', '944752465', '945086183', '945173393', '945363397', '945451818', '945552413', '945750143', '945769393', '945864246', '945882180', '946197694', '946628235', '947027689', '947042702', '947143169', '947380402', '947435458', '948114602', '948453771', '948481954', '948538942', '948654298', '948987920', '949127252', '949961255', '950147802', '950203531', '950453861', '950825062', '950874536', '951206544', '951426238', '951568805', '951628856', '951695324', '951832483', '951869094', '951989054', '952072250', '952313317', '952394031', '952419603', '952522529', '952652344', '952966000', '953662499', '954142901', '954375939', '954688661', '955784970', '955860837', '955892631', '956373365', '956686238', '956708256', '956762784', '956851481', '957011113', '957452690', '957547635', '958332633', '958805960', '958890765', '959712639', '959797323', '960053293', '960458725', '960543893', '960553522', '960789080', '961061906', '961427849', '961826058', '962389111', '963340242', '963547455', '963649983', '963739756', '964012003', '964019444', '964022195', '964153555', '964344263', '964588598', '964992730', '965000777', '965605521', '965656407', '965939674', '965989549', '966404789', '966456007', '966611804', '966642442', '967051386', '967596320', '968213839', '968238345', '968364305', '968447703', '968596244', '968735641', '969381194', '969503423', '970115142', '970149238', '970777856', '971018480', '971022517', '971391565', '971446956', '971601285', '972577793', '973287845', '973667205', '973754709', '973794950', '973805644', '974576709', '974774817', '974794915', '975202983', '975353724', '976268469', '976290116', '976465460', '976720508', '977993912', '978194254', '979276927', '979411457', '979758365', '979769815', '980220734', '980426396', '982852612', '983441340', '983769796', '984244018', '984319206', '984415308', '984470586', '984588492', '984618358', '984639652', '984903911', '985453299', '985479610', '986020989', '986037962', '986525681', '986696197', '986803168', '987208000', '988244859', '988902015', '988930998', '989034224', '989193488', '989464649', '989949815', '990203936', '990252523', '990333111', '991246462', '991343229', '991602984', '992131527', '992154443', '992908481', '993233217', '993453597', '993459006', '993463509', '993521519', '993543865', '993554340', '993838611', '993977018', '994192379', '994859236', '995083780', '995346034', '995774518', '995853840', '995884529', '996633908', '996905954', '996962802', '997135921', '997347230', '997438388', '997853395', '998334741', '999274206', '999951755', '999979538']

In [ ]:
df_list['CELULAR'] 

reemplazo = {
    'CELULAR': 'col_02',
}
df_list = df_list.rename(columns=reemplazo)
df_list.to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)

In [4]:

print(f"df_dni filas: {df_long.shape[0]}")
print(f"df_list filas: {df_list.shape[0]}")
df_list['CELULAR'] = (
    df_list['CELULAR']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)

df_dni filas: 190898
df_list filas: 614450

In [26]:
dnis = [
    "70663492",
    "47002810",
    "75797316",
    "61273533",
    "10182850",
    "70884441",
    "07876887"
]

telefonos = [
    "983849201",
    "900927220",
    "986506300",
    "981422534",
    "989341699",
    "941800134",
    "998183675"
]

# import pandas as pd

df_manual_dni = pd.DataFrame({
    "dni_cliente": dnis,
})


df_manual_telf = pd.DataFrame({
    "CELULAR": telefonos
})

In [23]:
df_manual_telf.head()

     CELULAR
0  983849201
1  900927220
2  986506300
3  981422534
4  989341699

In [ ]:
data = [
    ("70663492", "983849201"),
    ("47002810", "900927220"),
    ("75797316", "986506300"),
    ("61273533", "981422534"),
    ("10182850", "989341699"),
    ("70884441", "941800134"),
    ("07876887", "998183675")
]


df_manual = pd.DataFrame(data, columns=["DNI", "CELULAR"])

In [21]:
spark_df = spark.createDataFrame(df_manual)
spark_df.show()

NameError: name 'spark' is not defined

In [25]:
df_manual.head()

        DNI   TELEFONO
0  70663492  983849201
1  47002810  900927220
2  75797316  986506300
3  61273533  981422534
4  10182850  989341699

In [27]:
df_manual_telf['CELULAR'] = df_manual_telf['CELULAR'].astype(str)

df_manual_telf = df_manual_telf.merge(
    df_long,
    on="CELULAR",
    how="inner"
)

print(f"df_list filas: {df_manual_telf.shape[0]}")

df_list filas: 0

In [6]:
df_list['cl_estado']='3'
df_list['estado']='Retirar Telf'
df_list=df_list[['NUMERO_DOCUMENTO','cl_estado','estado']]
df_list.count()

NUMERO_DOCUMENTO    417
cl_estado           417
estado              417
dtype: int64

In [7]:
df_list = df_list.drop_duplicates(
    subset=['NUMERO_DOCUMENTO'],
    keep='last'
)
df_list.count()

NUMERO_DOCUMENTO    216
cl_estado           216
estado              216
dtype: int64

In [10]:
df_list.head()

     col_01 col_03        col_02
1  45773218      3  Retirar Telf
3  43888745      3  Retirar Telf
5  04647692      3  Retirar Telf
7  47240319      3  Retirar Telf
9  71563325      3  Retirar Telf

In [9]:
reemplazo = {
    'NUMERO_DOCUMENTO': 'col_01',
    'estado': 'col_02',
    'cl_estado': 'col_03'
}
df_list = df_list.rename(columns=reemplazo)

In [10]:
from sqlalchemy import create_engine

engine = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

In [ ]:

df_list.to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

216

In [19]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfcc_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO = b.col_01 
SET 
    a.cl_estado = b.col_03,
    a.estado = b.col_02
WHERE 
    a.cl_base = 'mayo 2026'
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

Filas afectadas: 684

In [20]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 70

In [ ]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfcc_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO COLLATE utf8mb4_general_ci
       = b.col_01 COLLATE utf8mb4_general_ci
SET 
    a.cl_estado = b.col_02,
    a.estado = b.col_03
WHERE 
    a.cl_base = 'mayo 2026'
    AND (
        IFNULL(a.cl_estado,'') COLLATE utf8mb4_general_ci 
            <> IFNULL(b.col_02,'') COLLATE utf8mb4_general_ci
        OR 
        IFNULL(a.estado,'') COLLATE utf8mb4_general_ci 
            <> IFNULL(b.col_03,'') COLLATE utf8mb4_general_ci
    )
LIMIT 1000
"""

with engine.begin() as conn:
    total = 0

    while True:
        result = conn.execute(text(query))
        filas = result.rowcount
        total += filas

        print("Filas afectadas:", filas)

        if filas == 0:
            break

    print("TOTAL ACTUALIZADO:", total)

In [ ]:

engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT 
* FROM tb_temporal
"""

df_prueba_01 = pd.read_sql(query, engine_mysql)

df_prueba_01.columns

Index(['col_01', 'col_02', 'col_03', 'col_04'], dtype='object')

In [8]:
update_mysql_en_bloques(
    df=df_list,
    tabla="alfcc_clientes",
    periodo="mayo 2026",
    col_llave_mysql="NUMERO_DOCUMENTO",
    col_valor_mysql="cl_estado",
    col_llave_df="NUMERO_DOCUMENTO",
    col_valor_df="retiro",
    host=server_valentina,
    user=user_valentina,
    password=pwd_valentina,
    database=db_valentina,
    port=port_mysql,
    batch_size=2000,
    validar_sin_grabar=False
)

Total registros a procesar: 11788
Lote 0 - 2000 actualizado | filas afectadas: 1927
Lote 2000 - 4000 actualizado | filas afectadas: 1931
Lote 4000 - 6000 actualizado | filas afectadas: 1908
Lote 6000 - 8000 actualizado | filas afectadas: 1898
Lote 8000 - 10000 actualizado | filas afectadas: 1897
Lote 10000 - 11788 actualizado | filas afectadas: 1690
Proceso terminado. Total filas afectadas: 11251

## actualizar retiro dni

In [5]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT 
DISTINCT 
NUMERO_DOCUMENTO as dni_cliente
FROM alfcc_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_dni = pd.read_sql(query, engine_mysql)

df_dni["dni_cliente"] = (
    df_dni["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)

In [21]:
filename='blacklist_dni.txt'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)

In [ ]:
filename='blacklist_dni.txt'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)

df_list.rename(columns={'DNI': 'dni_cliente'}, inplace=True)
df_list["dni_cliente"] = (
    df_list["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)
print(df_list.columns)
print(df_dni.columns)

Index(['dni_cliente'], dtype='object')
Index(['dni_cliente'], dtype='object')

In [35]:
print(df_dni.columns)
print(df_list.columns)

Index(['dni_cliente'], dtype='object')
Index(['dni_cliente'], dtype='object')

In [ ]:

exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC VALENTINA.DBO.ALFCC_BASE_VALENTINA", "SP actualizar BASE CREDICASH")
exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC VALENTINA.DBO.ALFCC_BASE_VALENTINA", "SP actualizar BASE CREDICASH")
exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC VALENTINA.DBO.ALFCC_BASE_VALENTINA", "SP actualizar BASE CREDICASH")
exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC VALENTINA.DBO.ALFCC_BASE_VALENTINA", "SP actualizar BASE CREDICASH")
exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC VALENTINA.DBO.ALFCC_BASE_VALENTINA", "SP actualizar BASE CREDICASH")

SP actualizar BASE CREDICASH | realizado | duración: 91.97 seg

In [7]:
df_list = df_list.merge(
    df_dni,
    on="dni_cliente",
    how="inner"
)

print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 6183

In [8]:
df_list['col_03']=3
df_list['col_02']='Retiro Bae'

In [10]:
reemplazo = {
    'dni_cliente': 'col_01',
    # 'retiro': 'col_02',
}
df_list = df_list.rename(columns=reemplazo)
df_list.head()

     col_01  col_03      col_02
0  73694914       3  Retiro Bae
1  30677717       3  Retiro Bae
2  09639416       3  Retiro Bae
3  41419547       3  Retiro Bae
4  41551915       3  Retiro Bae

In [24]:
df_list['retiro']='Retirar BlackList'
df_list=df_list[['dni_cliente','retiro']]
df_list.count()

dni_cliente    1
retiro         1
dtype: int64

In [12]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfcc_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO = b.col_01 
SET 
    a.cl_estado = b.col_03,
    a.estado = b.col_02
WHERE 
    a.cl_base = 'mayo 2026'
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

Filas afectadas: 6867

In [11]:

df_list[['col_01', 'col_02', 'col_03']].to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

6183

In [ ]:
df_list

In [13]:

ruta_archivo = os.path.join(ruta_csv, 'retiro_credicash.xlsx')
df_list.to_excel(ruta_archivo, index=False)

In [ ]:
update_mysql_en_bloques(
    df=df_list,
    tabla="alfin_clientes",
    periodo="mayo 2026",
    col_llave_mysql="NUMERO_DOCUMENTO",
    col_valor_mysql="estado",
    col_llave_df="dni_cliente",
    col_valor_df="retiro",
    host=server_valentina,
    user=user_valentina,
    password=pwd_valentina,
    database=db_valentina,
    port=port_mysql,
    batch_size=2000,
    validar_sin_grabar=False
)

Total registros a procesar: 1648
Lote 0 - 1648 actualizado | filas afectadas: 0
Proceso terminado. Total filas afectadas: 0

## ejecutar query

In [ ]:
from sqlalchemy import create_engine


engine = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)
with engine.begin() as conn:
    result = conn.execute(text("""
        UPDATE crm_target.alfcc_clientes
        SET cl_estado = 3
        WHERE estado <> 'ACTIVO'
        AND cl_base = 'mayo 2026'
    """))
    
    print("Filas afectadas:", result.rowcount)

## actualizar dni a otro lote

In [3]:
filename='dni_repetidos_alfin.csv'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)

In [5]:
df_list["NUMERO_DOCUMENTO"] = (
    df_list["NUMERO_DOCUMENTO"]
    .astype(str)
    .str.zfill(8)
)
df_list.head()

  NUMERO_DOCUMENTO
0         46507674
1         40963267
2         41782588
3         40658062
4         09457398

In [6]:
df_list['lote_ref']='BD-Target -ASM'

In [7]:
update_mysql_en_bloques(
    df=df_list,
    tabla="alfin_clientes",
    periodo="mayo 2026",
    col_llave_mysql="NUMERO_DOCUMENTO",
    col_valor_mysql="lote",
    col_llave_df="NUMERO_DOCUMENTO",
    col_valor_df="lote_ref",
    host=server_valentina,
    user=user_valentina,
    password=pwd_valentina,
    database=db_valentina,
    port=port_mysql,
    batch_size=2000,
    validar_sin_grabar=False
)

Total registros a procesar: 1066
Lote 0 - 1066 actualizado | filas afectadas: 1066
Proceso terminado. Total filas afectadas: 1066

In [ ]:
BD-Target -ASM

In [5]:
exec_query_sql(server_zeus, "MAEBA", user_zeus, pwd_zeus, "ADM_OBJ_TG.spFunnelDinersTc", "SP funnel diners_tc Zeus")

SP funnel diners_tc Zeus | realizado | duración: 19.96 seg

In [ ]:
overwrite_table_SQL(spark,df_prueba_1,f'borrar_TARGET_202604_01',server_kishin,user_kishin,pwd_kishin,'DANTALION')
overwrite_table_SQL(spark,df_prueba_2,f'borrar_TARGET_202604_02',server_kishin,user_kishin,pwd_kishin,'DANTALION')
overwrite_table_SQL(spark,df_prueba_ch,f'borrar_TARGET_202604_ch',server_kishin,user_kishin,pwd_kishin,'DANTALION')

df_list filas: 1066

In [ ]:
df_dni filas: 128183
df_list filas: 12546

In [ ]:
ssss

In [7]:
print(df_list.columns)
print(df_long.columns)

Index(['TELEFONO'], dtype='object')
Index(['NUMERO_DOCUMENTO', 'tipo_telf', 'TELEFONO'], dtype='object')

df_list filas: 1

In [ ]:
df_list filas: 2036

NUMERO_DOCUMENTO    1
retiro              1
dtype: int64

In [10]:
df_list.head()

  NUMERO_DOCUMENTO         retiro
0         40503275  Retirar Telef

Total registros a procesar: 1
Lote 0 - 1 actualizado | filas afectadas: 1
Proceso terminado. Total filas afectadas: 1