In [1]:
import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *

spark = SparkSession.builder \
    .appName("SparkExample") \
    .master("local[*]") \
    .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
    .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
    .config('spark.executor.memory', '8g') \
    .config('spark.driver.memory', '8g') \
    .getOrCreate()

## actualizar retiro telef

In [50]:
filename = '20260507_BASE_CREDICASH_TARGET.txt'
df_base = cargar_archivo_csv(spark, filename, '|', True)

filename = '20260507_BASE_CREDICASH_TARGET_INVENTARIO.txt'
df_base_inventario = cargar_archivo_csv(spark, filename, '|', True)

# filename = '20260311_BASE_CREDICASH_TARGET_TELEFONOS.txt'
# df_score = cargar_archivo_csv(spark, filename, '|', True)

In [53]:


df_base = df_base.select(
    'DETALLE_OFERTA',
    'DETALLE_TASA',
    F.lit('base_regular').alias('base')
)

In [ ]:
TIPDOC|DNI|NOMBRE|PERFIL|OFERTA_CREDICASH|PLAZO_CREDICASH|TASA_CREDICASH|CME_CREDICASH|GRUPO_SEGMENTO_CREDICASH|PROPENSION_CREDICASH|OFERTA_ELECTRO|PLAZO_ELECTRO|TASA_ELECTRO|CME_ELECTRO|PROPENSION_ELECTRO|REGION|TIENDA|SEMAFORO|DEPARTAMENTO|PROVINCIA|DISTRITO|DIRECCION|FLG_AAHH|FLG_URB|TIPO_ZONA|MARCA_PD|FLG_PEARS|PRODUCTO_EXTERNO|FLG_CRUCE_RECURRENTE|FRESCURA|RANGO_EDAD|RANGO_SUELDO|TIPO_CLIENTE|INTENSIDAD_MAX

In [54]:
df_base_inventario = df_base_inventario.select(
    'DETALLE_OFERTA',
    'DETALLE_TASA',
    F.lit('inventario').alias('base')
)

{"ts": "2026-05-07 11:10:00.040", "level": "ERROR", "logger": "DataFrameQueryContextLogger", "msg": "[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `DETALLE_OFERTA` cannot be resolved. Did you mean one of the following? [`DEPARTAMENTO`, `FLG_PEARS`, `FLG_URB`, `SEMAFORO`, `TASA_ELECTRO`]. SQLSTATE: 42703", "context": {"file": "jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)", "line": "", "fragment": "col", "errorClass": "UNRESOLVED_COLUMN.WITH_SUGGESTION"}, "exception": {"class": "Py4JJavaError", "msg": "An error occurred while calling o244.select.\n: org.apache.spark.sql.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `DETALLE_OFERTA` cannot be resolved. Did you mean one of the following? [`DEPARTAMENTO`, `FLG_PEARS`, `FLG_URB`, `SEMAFORO`, `TASA_ELECTRO`]. SQLSTATE: 42703;\n'Project ['DETALLE_OFERTA, 'DETALLE_TASA, inventario AS base#923]\n+- Relation [TIPDOC#884,DNI#885,NOMBRE#886,PERFIL#887,OFERTA_CREDICASH#888,PLAZO_CREDICASH#889,TASA_CREDICASH#890,CME_CREDICASH#891,GRUPO_SEGMENTO_CREDICASH#892,PROPENSION_CREDICASH#893,OFERTA_ELECTRO#894,PLAZO_ELECTRO#895,TASA_ELECTRO#896,CME_ELECTRO#897,PROPENSION_ELECTRO#898,REGION#899,TIENDA#900,SEMAFORO#901,DEPARTAMENTO#902,PROVINCIA#903,DISTRITO#904,DIRECCION#905,FLG_AAHH#906,FLG_URB#907,TIPO_ZONA#908,... 9 more fields] csv\n\r\n\tat org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:430)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:166)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:406)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:404)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6(CheckAnalysis.scala:404)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6$adapted(CheckAnalysis.scala:404)\r\n\tat scala.collection.immutable.List.foreach(List.scala:323)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:404)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:281)\r\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:281)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:252)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:289)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:241)\r\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:228)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:289)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:238)\r\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\r\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:238)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:91)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:122)\r\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:84)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:322)\r\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)\r\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:322)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:139)\r\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:330)\r\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:717)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:330)\r\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\r\n\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:329)\r\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:139)\r\n\tat scala.util.Try$.apply(Try.scala:217)\r\n\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1392)\r\n\tat org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1453)\r\n\tat org.apache.spark.util.LazyTry.get(LazyTry.scala:58)\r\n\tat org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:150)\r\n\tat org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:90)\r\n\tat org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$1(Dataset.scala:114)\r\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\r\n\tat org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:112)\r\n\tat org.apache.spark.sql.classic.Dataset.withPlan(Dataset.scala:2306)\r\n\tat org.apache.spark.sql.classic.Dataset.select(Dataset.scala:914)\r\n\tat org.apache.spark.sql.classic.Dataset.select(Dataset.scala:231)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:75)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\r\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\r\n\tat py4j.Gateway.invoke(Gateway.java:282)\r\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\r\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\r\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)\r\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:108)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\tSuppressed: org.apache.spark.util.Utils$OriginalTryStackTraceException: Full stacktrace of original doTryWithCallerStacktrace caller\r\n\t\tat org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:430)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:166)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:406)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:404)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6(CheckAnalysis.scala:404)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6$adapted(CheckAnalysis.scala:404)\r\n\t\tat scala.collection.immutable.List.foreach(List.scala:323)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:404)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:281)\r\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:273)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:281)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:252)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:289)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:241)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:228)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:289)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:238)\r\n\t\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\r\n\t\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:238)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:91)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:122)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:84)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:322)\r\n\t\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)\r\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:322)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:139)\r\n\t\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:330)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:717)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:330)\r\n\t\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:329)\r\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:139)\r\n\t\tat scala.util.Try$.apply(Try.scala:217)\r\n\t\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1392)\r\n\t\tat org.apache.spark.util.LazyTry.tryT$lzycompute(LazyTry.scala:46)\r\n\t\tat org.apache.spark.util.LazyTry.tryT(LazyTry.scala:46)\r\n\t\t... 21 more\r\n", "stacktrace": [{"class": null, "method": "deco", "file": "c:\\Users\\DATA\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyspark\\errors\\exceptions\\captured.py", "line": "263"}, {"class": null, "method": "get_return_value", "file": "c:\\Users\\DATA\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\py4j\\protocol.py", "line": "327"}]}}

AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `DETALLE_OFERTA` cannot be resolved. Did you mean one of the following? [`DEPARTAMENTO`, `FLG_PEARS`, `FLG_URB`, `SEMAFORO`, `TASA_ELECTRO`]. SQLSTATE: 42703;
'Project ['DETALLE_OFERTA, 'DETALLE_TASA, inventario AS base#923]
+- Relation [TIPDOC#884,DNI#885,NOMBRE#886,PERFIL#887,OFERTA_CREDICASH#888,PLAZO_CREDICASH#889,TASA_CREDICASH#890,CME_CREDICASH#891,GRUPO_SEGMENTO_CREDICASH#892,PROPENSION_CREDICASH#893,OFERTA_ELECTRO#894,PLAZO_ELECTRO#895,TASA_ELECTRO#896,CME_ELECTRO#897,PROPENSION_ELECTRO#898,REGION#899,TIENDA#900,SEMAFORO#901,DEPARTAMENTO#902,PROVINCIA#903,DISTRITO#904,DIRECCION#905,FLG_AAHH#906,FLG_URB#907,TIPO_ZONA#908,... 9 more fields] csv

In [ ]:
['TIPDOC', 'DNI', 'NOMBRE', 'PERFIL', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'GRUPO_SEGMENTO_CREDICASH', 'PROPENSION_CREDICASH', 'OFERTA_ELECTRO', 'PLAZO_ELECTRO', 'TASA_ELECTRO', 'CME_ELECTRO', 'PROPENSION_ELECTRO', 'REGION', 'TIENDA', 'SEMAFORO', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'FLG_AAHH', 'FLG_URB', 'TIPO_ZONA', 'MARCA_PD', 'FLG_PEARS', 'PRODUCTO_EXTERNO', 'FLG_CRUCE_RECURRENTE', 'FRESCURA', 'RANGO_EDAD', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'INTENSIDAD_MAX', 'DETALLE_OFERTA', 'DETALLE_TASA']

In [ ]:
['TIPDOC', 'DNI', 'NOMBRE', 'PERFIL', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'GRUPO_SEGMENTO_CREDICASH', 'PROPENSION_CREDICASH', 'OFERTA_ELECTRO', 'PLAZO_ELECTRO', 'TASA_ELECTRO', 'CME_ELECTRO', 'PROPENSION_ELECTRO', 'REGION', 'TIENDA', 'SEMAFORO', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'FLG_AAHH', 'FLG_URB', 'TIPO_ZONA', 'MARCA_PD', 'FLG_PEARS', 'PRODUCTO_EXTERNO', 'FLG_CRUCE_RECURRENTE', 'FRESCURA', 'RANGO_EDAD', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'INTENSIDAD_MAX', 'DETALLE_OFERTA', 'DETALLE_TASA']e

['TIPDOC', 'DNI', 'NOMBRE', 'PERFIL', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'GRUPO_SEGMENTO_CREDICASH', 'PROPENSION_CREDICASH', 'OFERTA_ELECTRO', 'PLAZO_ELECTRO', 'TASA_ELECTRO', 'CME_ELECTRO', 'PROPENSION_ELECTRO', 'REGION', 'TIENDA', 'SEMAFORO', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'FLG_AAHH', 'FLG_URB', 'TIPO_ZONA', 'MARCA_PD', 'FLG_PEARS', 'PRODUCTO_EXTERNO', 'FLG_CRUCE_RECURRENTE', 'FRESCURA', 'RANGO_EDAD', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'INTENSIDAD_MAX', 'DETALLE_OFERTA', 'DETALLE_TASA']

In [55]:
print(15791+36085+14713)

66589

In [57]:
df=df_base.toPandas()

In [58]:
import os

ruta_archivo = os.path.join(ruta_csv, 'ivr_202603271706.xlsx')

df.to_excel(ruta_archivo, index=False)

In [ ]:

# df_base.show()

+---------------+-------------+-----+
| DETALLE_OFERTA| DETALLE_TASA|count|
+---------------+-------------+-----+
|           NULL|         NULL| 7036|
| EMPEORA OFERTA| EMPEORA TASA| 5665|
| EMPEORA OFERTA|MANTIENE TASA| 9781|
| EMPEORA OFERTA|  MEJORA TASA|  345|
|MANTIENE OFERTA| EMPEORA TASA|  872|
|MANTIENE OFERTA|MANTIENE TASA|34352|
|MANTIENE OFERTA|  MEJORA TASA|  861|
|  MEJORA OFERTA| EMPEORA TASA|  481|
|  MEJORA OFERTA|MANTIENE TASA| 6904|
|  MEJORA OFERTA|  MEJORA TASA| 7328|
+---------------+-------------+-----+

+---------------+-------------+------------+
| DETALLE_OFERTA| DETALLE_TASA|        base|
+---------------+-------------+------------+
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|  MEJORA OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|           NULL|         NULL|base_regular|
| EMPEORA OFERTA| EMPEORA TASA|base_regular|
|  MEJORA OFERTA|MANTIENE TASA|base_regular|
|  MEJORA OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|  MEJORA OFERTA|MANTIENE TASA|base_regular|
|           NULL|         NULL|base_regular|
|           NULL|         NULL|base_regular|
| EMPEORA OFERTA|MANTIENE TASA|base_regular|
| EMPEORA OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
|MANTIENE OFERTA|MANTIENE TASA|base_regular|
+---------------+-------------+------------+
only showing top 20 rows

In [10]:
df_base=df_base.select('DNI','TASA_CREDICASH','TASA_ELECTRO', 'OFERTA_CREDICASH','OFERTA_ELECTRO','INTENSIDAD_MAX')
df_base_inventario=df_base_inventario.select('DNI','TASA_CREDICASH','TASA_ELECTRO', 'OFERTA_CREDICASH','OFERTA_ELECTRO','INTENSIDAD_MAX')

In [11]:
df_base = df_base.withColumn(
    "DNI",
    F.right(
        F.concat(F.lit("00000000"), F.col("DNI")),
        F.lit(8)
    )
)
df_base=df_base.filter(F.col('DNI').isNotNull())
df_base_inventario = df_base_inventario.withColumn(
    "DNI",
    F.right(
        F.concat(F.lit("00000000"), F.col("DNI")),
        F.lit(8)
    )
)
df_base_inventario=df_base_inventario.filter(F.col('DNI').isNotNull())

In [8]:
print(df_base.columns)
print(df_base_inventario.columns)

['TIPDOC', 'DNI', 'NOMBRE', 'PERFIL', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'GRUPO_SEGMENTO_CREDICASH', 'PROPENSION_CREDICASH', 'OFERTA_ELECTRO', 'PLAZO_ELECTRO', 'TASA_ELECTRO', 'CME_ELECTRO', 'PROPENSION_ELECTRO', 'REGION', 'TIENDA', 'SEMAFORO', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'FLG_AAHH', 'FLG_URB', 'TIPO_ZONA', 'MARCA_PD', 'FLG_PEARS', 'PRODUCTO_EXTERNO', 'FLG_CRUCE_RECURRENTE', 'FRESCURA', 'RANGO_EDAD', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'INTENSIDAD_MAX', 'DETALLE_OFERTA', 'DETALLE_TASA']
['TIPDOC', 'DNI', 'NOMBRE', 'PERFIL', 'OFERTA_CREDICASH', 'PLAZO_CREDICASH', 'TASA_CREDICASH', 'CME_CREDICASH', 'GRUPO_SEGMENTO_CREDICASH', 'PROPENSION_CREDICASH', 'OFERTA_ELECTRO', 'PLAZO_ELECTRO', 'TASA_ELECTRO', 'CME_ELECTRO', 'PROPENSION_ELECTRO', 'REGION', 'TIENDA', 'SEMAFORO', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'DIRECCION', 'FLG_AAHH', 'FLG_URB', 'TIPO_ZONA', 'MARCA_PD', 'FLG_PEARS', 'PRODUCTO_EXTERNO', 'FLG_CRUCE_RECURRENTE', 'FRESCURA', 'RANGO_EDAD', 'RANGO_SUELDO', 'TIPO_CLIENTE', 'INTENSIDAD_MAX']

In [12]:
df_base_01=df_base.toPandas()
df_base_inventario_01=df_base_inventario.toPandas()

In [6]:
from sqlalchemy import create_engine

engine = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

In [ ]:

reemplazo = {
    'DNI': 'col_01',
    'OFERTA_CREDICASH': 'col_02',
    'OFERTA_ELECTRO': 'col_03'
}
df_base_02 = df_base_01.rename(columns=reemplazo)
# 'DNI', 'TASA_CREDICASH', 'TASA_ELECTRO', 'OFERTA_CREDICASH','OFERTA_ELECTRO', 'INTENSIDAD_MAX'

In [34]:
import pandas as pd

df_base_02['col_03'] = (
    pd.to_numeric(df_base_02['col_03'], errors='coerce')  # convierte a número
    .fillna(0)                                           # reemplaza NaN
    .astype(int)                                         # ahora sí convierte
    .astype(str)                                         # a string
)
df_base_02.head()

     col_01 TASA_CREDICASH TASA_ELECTRO   col_02 col_03 INTENSIDAD_MAX
0  03369493           56.2         45.8   7000.0   6570              6
1  44923897           40.7         45.8  11600.0   7000              6
2  45571497           40.7         45.8  11600.0   6390              5
3  45428699             48         45.8   8900.0   7000              6
4  76264197           67.9         59.8   5500.0   6000              6

In [36]:

df_base_02[['col_01', 'col_02', 'col_03']].to_sql(
    name="tb_temporal",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

73625

In [37]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfcc_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO = b.col_01 
SET 
    a.OFERTA_CREDICASH = b.col_02,
    a.OFERTA_ELECTRO= b.col_03
WHERE 
    a.cl_base = 'mayo 2026'
"""

with engine.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

Filas afectadas: 73625

In [38]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 73625

In [39]:
exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC ALFCC_BASE_VALENTINA", "SP actualizar base credicash")

SP actualizar base credicash | realizado | duración: 91.2 seg

In [33]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT  NUMERO_DOCUMENTO,cl_telf1, cl_telf2, cl_telf3, cl_telf4, cl_telf5, cl_telf6, cl_telf7, cl_telf8, cl_telf9, cl_telf10, cl_movil, cl_celular, cl_telefono 
FROM crm_target.alfcc_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_dni = pd.read_sql(query, engine_mysql)

cols_tel = [
    'cl_telf1','cl_telf2','cl_telf3','cl_telf4','cl_telf5',
    'cl_telf6','cl_telf7','cl_telf8','cl_telf9','cl_telf10',
    'cl_movil','cl_celular','cl_telefono'
]

df_long = df_dni.melt(
    id_vars='NUMERO_DOCUMENTO',
    value_vars=cols_tel,
    var_name='tipo_telf',
    value_name='CELULAR'
)
df_long['CELULAR'] = (
    df_long['CELULAR']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)
df_long = df_long[
    (df_long['CELULAR'].notna()) &
    (df_long['CELULAR'] != '') &
    (df_long['CELULAR'].str.len() == 9) &
    (df_long['CELULAR'].str.startswith('9'))
]

In [16]:
filename='blacklist_celulares.txt'
filePath = os.path.join(ruta_csv, filename)

df_list = pd.read_csv(filePath)

In [18]:

print(f"df_dni filas: {df_long.shape[0]}")
print(f"df_list filas: {df_list.shape[0]}")
df_list['CELULAR'] = (
    df_list['CELULAR']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)

df_dni filas: 169357
df_list filas: 601774

In [ ]:

# telefonos = ["987863718", "991187143", "966700993", "997167060"]

# df_manual = pd.DataFrame(telefonos, columns=["TELEFONO"])

In [5]:
df_long.head()

  NUMERO_DOCUMENTO tipo_telf    CELULAR
2         80708936  cl_telf1  931185554
4         80686119  cl_telf1  969443669
6         80681915  cl_telf1  980257187
7         80681241  cl_telf1  973476485
8         80678740  cl_telf1  900212933

In [19]:
df_list['CELULAR'] = df_list['CELULAR'].astype(str)

df_list = df_list.merge(
    df_long,
    on="CELULAR",
    how="inner"
)

print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 226

In [20]:
df_list['retiro']='3'
df_list['estado']='Retirar Telf'
df_list=df_list[['NUMERO_DOCUMENTO','retiro','estado']]
df_list.count()

NUMERO_DOCUMENTO    226
retiro              226
estado              226
dtype: int64

In [21]:
df_list = df_list.drop_duplicates(
    subset=['NUMERO_DOCUMENTO'],
    keep='last'
)
df_list.count()

NUMERO_DOCUMENTO    117
retiro              117
estado              117
dtype: int64

In [22]:
reemplazo = {
    'NUMERO_DOCUMENTO': 'col_01',
    'retiro': 'col_02',
    'estado': 'col_03'
}
df_list = df_list.rename(columns=reemplazo)

In [23]:
from sqlalchemy import create_engine

engine = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

In [24]:

df_list.to_sql(
    name="tb_temporal",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

117

In [ ]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfcc_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.numero_documento COLLATE utf8mb4_general_ci 
       = b.col_01 COLLATE utf8mb4_general_ci
SET 
    a.cl_estado = b.col_02,
    a.estado = b.col_03
"""

with engine.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

In [ ]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfcc_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO COLLATE utf8mb4_general_ci
       = b.col_01 COLLATE utf8mb4_general_ci
SET 
    a.cl_estado = b.col_02,
    a.estado = b.col_03
WHERE 
    a.cl_base = 'mayo 2026'
    AND (
        IFNULL(a.cl_estado,'') COLLATE utf8mb4_general_ci 
            <> IFNULL(b.col_02,'') COLLATE utf8mb4_general_ci
        OR 
        IFNULL(a.estado,'') COLLATE utf8mb4_general_ci 
            <> IFNULL(b.col_03,'') COLLATE utf8mb4_general_ci
    )
LIMIT 1000
"""

with engine.begin() as conn:
    total = 0

    while True:
        result = conn.execute(text(query))
        filas = result.rowcount
        total += filas

        print("Filas afectadas:", filas)

        if filas == 0:
            break

    print("TOTAL ACTUALIZADO:", total)

OperationalError: (pymysql.err.OperationalError) (1969, 'Query execution was interrupted (max_statement_time exceeded)')
[SQL:
UPDATE crm_target.alfcc_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO COLLATE utf8mb4_general_ci
       = b.col_01 COLLATE utf8mb4_general_ci
SET
    a.cl_estado = b.col_02,
    a.estado = b.col_03
WHERE
    a.cl_base = 'mayo 2026'
    AND (
        IFNULL(a.cl_estado,'') COLLATE utf8mb4_general_ci
            <> IFNULL(b.col_02,'') COLLATE utf8mb4_general_ci
        OR
        IFNULL(a.estado,'') COLLATE utf8mb4_general_ci
            <> IFNULL(b.col_03,'') COLLATE utf8mb4_general_ci
    )
LIMIT 1000
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:

engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT 
* FROM tb_temporal
"""

df_prueba_01 = pd.read_sql(query, engine_mysql)

df_prueba_01.columns

Index(['col_01', 'col_02', 'col_03', 'col_04'], dtype='object')

In [8]:
update_mysql_en_bloques(
    df=df_list,
    tabla="alfcc_clientes",
    periodo="mayo 2026",
    col_llave_mysql="NUMERO_DOCUMENTO",
    col_valor_mysql="cl_estado",
    col_llave_df="NUMERO_DOCUMENTO",
    col_valor_df="retiro",
    host=server_valentina,
    user=user_valentina,
    password=pwd_valentina,
    database=db_valentina,
    port=port_mysql,
    batch_size=2000,
    validar_sin_grabar=False
)

Total registros a procesar: 11788
Lote 0 - 2000 actualizado | filas afectadas: 1927
Lote 2000 - 4000 actualizado | filas afectadas: 1931
Lote 4000 - 6000 actualizado | filas afectadas: 1908
Lote 6000 - 8000 actualizado | filas afectadas: 1898
Lote 8000 - 10000 actualizado | filas afectadas: 1897
Lote 10000 - 11788 actualizado | filas afectadas: 1690
Proceso terminado. Total filas afectadas: 11251

## actualizar retiro dni

In [10]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT 
DISTINCT 
NUMERO_DOCUMENTO as dni_cliente
FROM alfcc_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_dni = pd.read_sql(query, engine_mysql)

df_dni["dni_cliente"] = (
    df_dni["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)

In [11]:
filename='blacklist_dni.txt'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)
df_list.head(2)

   DNI
0    0
1   14

In [12]:

df_list.rename(columns={'DNI': 'dni_cliente'}, inplace=True)
df_list["dni_cliente"] = (
    df_list["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)
print(df_list.columns)
print(df_dni.columns)

Index(['dni_cliente'], dtype='object')
Index(['dni_cliente'], dtype='object')

In [13]:
df_list = df_list.merge(
    df_dni,
    on="dni_cliente",
    how="inner"
)

print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 0

In [19]:
df_list['retiro']='Retirar BlackList'
df_list=df_list[['dni_cliente','retiro']]
df_list.count()

dni_cliente    1648
retiro         1648
dtype: int64

In [ ]:
update_mysql_en_bloques(
    df=df_list,
    tabla="alfin_clientes",
    periodo="mayo 2026",
    col_llave_mysql="NUMERO_DOCUMENTO",
    col_valor_mysql="estado",
    col_llave_df="dni_cliente",
    col_valor_df="retiro",
    host=server_valentina,
    user=user_valentina,
    password=pwd_valentina,
    database=db_valentina,
    port=port_mysql,
    batch_size=2000,
    validar_sin_grabar=False
)

Total registros a procesar: 1648
Lote 0 - 1648 actualizado | filas afectadas: 0
Proceso terminado. Total filas afectadas: 0

## ejecutar query

In [ ]:
from sqlalchemy import create_engine


engine = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)
with engine.begin() as conn:
    result = conn.execute(text("""
        UPDATE crm_target.alfcc_clientes
        SET cl_estado = 3
        WHERE estado <> 'ACTIVO'
        AND cl_base = 'mayo 2026'
    """))
    
    print("Filas afectadas:", result.rowcount)

In [7]:
df_01=df_list.toPandas()

In [8]:
df_01.head()

,cl_id,TIPO_DOI,NUMERO_DOCUMENTO,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,SUCURSAL,TIENDA,DEPARTAMENTO,PROVINCIA,...,PROMOCION,PROMOCION2,nombre_base,NumEntidades,p_banco,PERFIL_GLOBAL,FLG_AAHH,SCORE_TELEFONO,PILOTO_PLAZAS,INTENSIDAD_MAX
0,3065361,None,15413942,ANA MARIA,ARREDONDO,CHOCCATA,NaN,CAÃ‘ETE,LIMA,CAÃ‘ETE,...,None,None,2026-05-08,None,None,None,NO EMERGENTE,2,NaN,NaN

In [11]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
    select * from alfin_clientes
where NUMERO_DOCUMENTO='15413942'
and cl_base='Marzo 2026'
"""

df_dni = pd.read_sql(query, engine_mysql)

In [ ]:
['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']

['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']

In [16]:
df_dni["Tasa_1"] = 62.0
df_dni["Tasa_2"] = 60.0

df_dni["lote"] = "REINGRESO"
df_dni["cl_base"] = "Mayo 2026"
df_dni["cl_carga"] = "2026-05-08"
df_dni["cl_estado"] = 1
df_dni["estado"] = "ACTIVO"
df_dni["nombre_base"] = "2026-05-08"
df_dni = df_dni.drop(columns=["cl_id"])

In [17]:
from sqlalchemy import create_engine

engine = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

df_dni.to_sql(
    name="alfin_clientes",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

1

## actualizar dni a otro lote

In [3]:
filename='dni_repetidos_alfin.csv'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)

In [5]:
df_list["NUMERO_DOCUMENTO"] = (
    df_list["NUMERO_DOCUMENTO"]
    .astype(str)
    .str.zfill(8)
)
df_list.head()

  NUMERO_DOCUMENTO
0         46507674
1         40963267
2         41782588
3         40658062
4         09457398

In [6]:
df_list['lote_ref']='BD-Target -ASM'

In [7]:
update_mysql_en_bloques(
    df=df_list,
    tabla="alfin_clientes",
    periodo="mayo 2026",
    col_llave_mysql="NUMERO_DOCUMENTO",
    col_valor_mysql="lote",
    col_llave_df="NUMERO_DOCUMENTO",
    col_valor_df="lote_ref",
    host=server_valentina,
    user=user_valentina,
    password=pwd_valentina,
    database=db_valentina,
    port=port_mysql,
    batch_size=2000,
    validar_sin_grabar=False
)

Total registros a procesar: 1066
Lote 0 - 1066 actualizado | filas afectadas: 1066
Proceso terminado. Total filas afectadas: 1066

In [ ]:
BD-Target -ASM

In [5]:
exec_query_sql(server_zeus, "MAEBA", user_zeus, pwd_zeus, "ADM_OBJ_TG.spFunnelDinersTc", "SP funnel diners_tc Zeus")

SP funnel diners_tc Zeus | realizado | duración: 19.96 seg

In [ ]:
overwrite_table_SQL(spark,df_prueba_1,f'borrar_TARGET_202604_01',server_kishin,user_kishin,pwd_kishin,'DANTALION')
overwrite_table_SQL(spark,df_prueba_2,f'borrar_TARGET_202604_02',server_kishin,user_kishin,pwd_kishin,'DANTALION')
overwrite_table_SQL(spark,df_prueba_ch,f'borrar_TARGET_202604_ch',server_kishin,user_kishin,pwd_kishin,'DANTALION')

df_list filas: 1066

In [ ]:
df_dni filas: 128183
df_list filas: 12546

In [ ]:
ssss

In [7]:
print(df_list.columns)
print(df_long.columns)

Index(['TELEFONO'], dtype='object')
Index(['NUMERO_DOCUMENTO', 'tipo_telf', 'TELEFONO'], dtype='object')

df_list filas: 1

In [ ]:
df_list filas: 2036

NUMERO_DOCUMENTO    1
retiro              1
dtype: int64

In [10]:
df_list.head()

  NUMERO_DOCUMENTO         retiro
0         40503275  Retirar Telef

Total registros a procesar: 1
Lote 0 - 1 actualizado | filas afectadas: 1
Proceso terminado. Total filas afectadas: 1