In [1]:
import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *

# spark = SparkSession.builder \
#     .appName("SparkExample") \
#     .master("local[*]") \
#     .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
#     .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
#     .config('spark.executor.memory', '8g') \
#     .config('spark.driver.memory', '8g') \
#     .getOrCreate()

## actualizar retiro telef

In [ ]:

print(f"df_dni filas: {df_long.shape[0]}")
print(f"df_list filas: {df_list.shape[0]}")
df_list['TELEFONO'] = (
    df_list['TELEFONO']
    .fillna(0)            
    .astype('int64')        
    .astype(str)              
)

df_dni filas: 163965
df_list filas: 13150

In [ ]:

# telefonos = ["987863718", "991187143", "966700993", "997167060"]

# df_manual = pd.DataFrame(telefonos, columns=["TELEFONO"])

In [11]:
df_list = df_list.merge(
    df_long,
    on="TELEFONO",
    how="inner"
)

print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 104

In [12]:

reemplazo = {
    'NUMERO_DOCUMENTO': 'col_01',
}
df_list = df_list.rename(columns=reemplazo)
df_list['col_02']='Retirar Telef'
df_list['col_03']=3
df_list=df_list[['col_01','col_02','col_03']]
df_list = df_list.drop_duplicates(
    subset=['col_01'],
    keep='first'
)
df_list.shape

(67, 3)

In [13]:
df_list.head()

     col_01         col_02  col_03
0  05709984  Retirar Telef       3
1  02895851  Retirar Telef       3
3  16014273  Retirar Telef       3
4  41980489  Retirar Telef       3
5  70314359  Retirar Telef       3

In [14]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 6867

In [15]:

df_list[['col_01', 'col_02', 'col_03']].to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

67

In [16]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfin_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO = b.col_01 
SET 
    a.estado = b.col_02,
    a.cl_estado= b.col_03
WHERE 
    a.cl_base = 'mayo 2026'
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

Filas afectadas: 67

In [17]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfin_clientes
SET 
    cl_estado=3
WHERE 
    cl_base = 'mayo 2026'
    and estado<> 'ACTIVO'
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 1929

In [17]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 67

In [ ]:
# update_mysql_en_bloques(
#     df=df_list,
#     tabla="alfin_clientes",
#     periodo="mayo 2026",
#     col_llave_mysql="NUMERO_DOCUMENTO",
#     col_valor_mysql="estado",
#     col_llave_df="NUMERO_DOCUMENTO",
#     col_valor_df="retiro",
#     host=server_valentina,
#     user=user_valentina,
#     password=pwd_valentina,
#     database=db_valentina,
#     port=port_mysql,
#     batch_size=2000,
#     validar_sin_grabar=False
# )

Total registros a procesar: 6
Lote 0 - 6 actualizado | filas afectadas: 3
Proceso terminado. Total filas afectadas: 3

## actualizar retiro dni

In [18]:
from sqlalchemy import create_engine


engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

query = """
SELECT 
DISTINCT 
NUMERO_DOCUMENTO as dni_cliente
FROM alfin_clientes
WHERE cl_base = 'mayo 2026'
and cl_estado=1
"""

df_dni = pd.read_sql(query, engine_mysql)

df_dni["dni_cliente"] = (
    df_dni["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)

In [19]:
reemplazo = {
    'dni_cliente': 'col_01',
}
df_dni = df_dni.rename(columns=reemplazo)

In [20]:
filename='RetiroDefinitivo_BlackList.csv'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)
df_list.rename(columns={'DNI': 'col_01'}, inplace=True)
df_list["col_01"] = (
    df_list["col_01"]
    .astype(str)
    .str.zfill(8)
)
df_list['col_03']=3
df_list['col_02']='Retirar Definitivo'
df_list=df_list[['col_01','col_02','col_03']]

df_list.head()

     col_01              col_02  col_03
0  00013948  Retirar Definitivo       3
1  00015508  Retirar Definitivo       3
2  00031376  Retirar Definitivo       3
3  00035800  Retirar Definitivo       3
4  00036260  Retirar Definitivo       3

In [21]:
df_list = df_list.merge(
    df_dni,
    on="col_01",
    how="inner"
)

print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 0

In [14]:
df_list = df_list.drop_duplicates(
    subset=['col_01'],
    keep='first'
)
print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 2

In [15]:
df_list.head()

     col_01              col_02  col_03
0  08739782  Retirar Definitivo       3
1  23690763  Retirar Definitivo       3

In [ ]:
df_list['col_03']=3
df_list['col_02']='Retirar definitivo'
df_list=df_list[['col_01','col_02','col_03']]

In [22]:
df_list['col_02']='Retirar Cali Opor'

In [22]:
filename='RetiroDeGestion_BlackList.csv'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)
df_list.rename(columns={'DNI': 'col_01'}, inplace=True)
df_list["col_01"] = (
    df_list["col_01"]
    .astype(str)
    .str.zfill(8)
)
df_list['col_03']=3
df_list['col_02']='Retirar Definitivo'
df_list=df_list[['col_01','col_02','col_03']]

df_list.head()

     col_01              col_02  col_03
0  03866035  Retirar Definitivo       3
1  03867988  Retirar Definitivo       3
2  03877469  Retirar Definitivo       3
3  03890737  Retirar Definitivo       3
4  23985035  Retirar Definitivo       3

In [23]:
df_list = df_list.merge(
    df_dni,
    on="col_01",
    how="inner"
)

df_list = df_list.drop_duplicates(
    subset=['col_01'],
    keep='first'
)
print(f"df_list filas: {df_list.shape[0]}")

df_list filas: 653

In [24]:
df_list.head()

     col_01              col_02  col_03
0  00029171  Retirar Definitivo       3
1  45266796  Retirar Definitivo       3
2  00229598  Retirar Definitivo       3
3  00240478  Retirar Definitivo       3
4  00371354  Retirar Definitivo       3

In [25]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 0

In [26]:

df_list[['col_01', 'col_02', 'col_03']].to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

653

In [23]:
from sqlalchemy import text

query = """
DELETE FROM crm_target.tb_temporal
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas eliminadas:", result.rowcount)

Filas eliminadas: 1787

In [29]:
df_list.head()

     col_01             col_02  col_03
0  00029171  Retirar BlackList       3
1  45266796  Retirar BlackList       3
2  00229598  Retirar BlackList       3
3  00240478  Retirar BlackList       3
4  00371354  Retirar BlackList       3

In [28]:
df_list['col_02']='Retirar BlackList'
df_list.count()

col_01    653
col_02    653
col_03    653
dtype: int64

In [ ]:

reemplazo = {
    'dni_cliente': 'col_01',
    'retiro': 'col_02',
    'estado': 'col_03'
}
df_list = df_list.rename(columns=reemplazo)
df_list.head()

     col_01             col_02  col_03
0  05358759  Retirar BlackList       3
1  05377283  Retirar BlackList       3
2  09822790  Retirar BlackList       3
3  10459054  Retirar BlackList       3
4  10548156  Retirar BlackList       3

In [30]:

df_list[['col_01', 'col_02', 'col_03']].to_sql(
    name="tb_temporal",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

653

In [17]:
df_list.head()

     col_01                                          col_02  col_03
0  22313090  Retirar Retiros por calificacion y oportunidad       3
1  10480794  Retirar Retiros por calificacion y oportunidad       3
2  32908380  Retirar Retiros por calificacion y oportunidad       3
3  10132661  Retirar Retiros por calificacion y oportunidad       3
4  18178794  Retirar Retiros por calificacion y oportunidad       3

In [19]:
print(
    df_list['col_01']
    .drop_duplicates()
    .tolist()
)

['20714264', '20902698', '20902790', '20976897', '20984392', '21002539', '22519705', '22530292', '22666436', '22759696', '22877147', '22880733', '22984404', '22994539', '22996414', '23001618', '23173921', '23254793', '23277023', '24468122', '24682712', '26697063', '26711897', '26713691', '26941590', '19323697', '19325492', '19329338', '19337234', '19409793', '19422299', '19422699', '19523495', '19527943', '19532970', '19559294', '19559342', '19560297', '19565034', '19572995', '19574719', '19693195', '19815345', '19847527', '19854392', '19862614', '19905252', '19918892', '21012899', '21094011', '21121648', '21133492', '21138395', '21264236', '21299643', '21427623', '21434302', '21444045', '21456695', '21480830', '23676691', '23835499', '23845415', '23864618', '23878432', '23894298', '24712094', '24872310', '24889591', '24991897', '25005499', '25300204', '19952315', '19954598', '19958290', '20000794', '20015896', '20020343', '20021691', '20022268', '20048803', '20073084', '20096899', '22187950', '22194499', '22245581', '22249996', '22273450', '22276996', '22277596', '22309274', '22319216', '22406609', '22427095', '22439846', '22476698', '22484635', '22498280', '22510601', '23950557', '23997107', '23999795', '24383800', '25821892', '25851992', '25852922', '25855027', '26601397', '26610730', '26614933', '26622723', '26659299', '26662995', '26684538', '26686519', '20400005', '20406167', '19324461', '19333843', '19523910', '19528417', '19562253', '19814717', '19847520', '19856215', '19858439', '19898899', '19921358', '21066646', '21122798', '21139497', '21143415', '21145390', '21442076', '21483619', '21497996', '21498714', '23809544', '23835119', '23867290', '23882429', '23886590', '23922690', '24719291', '24804792', '24895599', '24998902', '25000692', '25199703', '20684547', '20685799', '20698643', '20717699', '20720599', '20898043', '20974995', '20998803', '22515746', '22516698', '22518014', '22519792', '22665017', '22672169', '22673114', '23008542', '23011251', '23014391', '23210927', '23238039', '23393035', '23461893', '24493814', '24695566', '26697615', '26704091', '26711399', '26712154', '26723432', '26952961', '27043658', '27055145', '19324278', '19327659', '19331741', '19428440', '19430891', '19976493', '19983991', '20014621', '20028390', '20030995', '20053093', '20062897', '20084799', '20087475', '20097122', '20102482', '22276361', '22287892', '22290823', '22292400', '22297762', '22405953', '22406851', '22419014', '22435693', '22453094', '22471494', '22478342', '22488327', '22494775', '22495703', '22503401', '22510324', '23963196', '23976091', '23983942', '23994900', '24392466', '25816846', '25818541', '25840978', '25855997', '26623692', '26636792', '26641609', '26668492', '19322709', '19526224', '19526495', '20699292', '20903715', '20971097', '20972792', '20995243', '22515759', '22665535', '22729733', '22751892', '22755235', '22876490', '23003191', '23006107', '23016294', '23170995', '23172443', '23221946', '23268595', '23373992', '23384263', '23394698', '23449195', '24660990', '24675201', '26696109', '26696786', '26697202', '26698381', '26700011', '26705539', '26708046', '26713214', '26717917', '26721177', '26722401', '26924998', '26963297', '27075314', '27076001', '27144014', '27254522', '20112191', '20114329', '20117138', '19533750', '19539499', '19561647', '19562197', '19572563', '19677764', '19809899', '19826791', '19873417', '19884595', '19897396', '19907240', '19919318', '21094038', '21117515', '21143847', '21411824', '21421516', '21428097', '21481002', '23568496', '23860746', '23916298', '23932542', '24705797', '24707138', '24707251', '24718692', '24895654', '25002490', '25135399', '25209966', '25302407', '19939926', '19944262', '20021495', '20023696', '20046991', '20051324', '20054176', '20066535', '20094992', '20100449', '22292796', '22301542', '22401096', '22413958', '22417010', '22428601', '22459976', '22471093', '22486391', '22486912', '22487232', '22492914', '22498331', '22498717', '22509055', '23947996', '23959825', '23961697', '23966602', '23976034', '23980412', '23982390', '25851691', '25856798', '25860995', '26632141', '26641948', '26647292', '26655398', '26656016', '26676194', '20104697', '20106294', '20108899', '20115516', '20407426', '20407960', '20440439', '20525227', '20534498', '20571219', '20572691', '20577542', '20584738', '21522898', '21524641', '21543690', '21544091', '21552948', '21578089', '21780691', '21817491', '21819779', '21826891', '21834949', '21837155', '21866321', '21870871', '21873507', '21875204', '21885546', '22063093', '22072597', '22079010', '22099827', '22102455', '22185215', '07963294', '23902314', '23939625', '25512116', '25552846', '25573095', '25575392', '25635042', '25655562', '25716424', '25749622', '25780631', '25783639', '25787694', '19978667', '20004795', '20013510', '20017743', '19546248', '19558431', '19561195', '19561408', '19700066', '19811841', '19822153', '19840799', '19849217', '19849698', '19863873', '19881292', '19936895', '19937592', '21014016', '21077797', '21121831', '21138094', '21400794', '21406893', '21413798', '21414326', '21416288', '21458496', '21503792', '23547415', '23706644', '23824640', '23850509', '23859621', '23905087', '23920741', '23924798', '23925706', '23926390', '23933083', '24812894', '24886567', '24890216', '24985797', '25219393', '20642905', '20522126', '20539198', '20547199', '20560438', '20569474', '20569514', '20585291', '20590394', '21508993', '21520845', '21550636', '21552393', '21553103', '21562824', '21571295', '21822955', '21825710', '21845894', '21851798', '21858591', '21869535', '21872960', '21876234', '21879758', '22080014', '22083416', '22093392', '22100255', '22103237', '22185939', '16712262', '25321277', '25412597', '25540446', '25556198', '25562515', '25614503', '25635298', '25654816', '25702885', '25725893', '25782943', '25789954', '25790991', '25793418', '25794292', '25800389', '27246456', '27252318', '00176633', '00252315', '00374592', '00401695', '00432490', '00434290', '00443096', '00445000', '20887391', '20903623', '21001694', '22521552', '22642141', '22663811', '22669284', '22705693', '22711392', '22733240', '22755145', '22878926', '22887406', '22960199', '22995002', '23001595', '23020056', '23140242', '23257697', '24575699', '26698696', '26702390', '26702498', '26710210', '26713793', '26714658', '26715198', '26724316', '26921199', '26958090', '27074996', '27149741', '27295478', '27295811', '27373353', '20106299', '20112895', '20413097', '20051015', '20055745', '20065822', '20102598', '22292695', '22423234', '22479422', '22480807', '22502099', '22510124', '22510404', '23957618', '44621047', '23991149', '23998805', '24005418', '24006308', '24380243', '25819869', '25832865', '25833894', '25852412', '26613993', '26615094', '26619095', '26620825', '26629392', '26665492', '26668138', '26678804', '26680359', '26681603', '00839245', '00186229', '00186494', '20532224', '20534532', '20566798', '20567240', '20567694', '20574492', '20590526', '21526533', '21542691', '21546390', '21572518', '21576094', '21788013', '21825838', '21828717', '21831855', '21834440', '22080294', '22100506', '22103559', '22186621', '44750726', '23940352', '23946094', '25311441', '25320304', '25328791', '25563591', '25618615', '25640414', '25680711', '25686207', '25723996', '25732893', '25735545', '25753661', '25762618', '25767435', '25792096', '25797732', '25800938', '20532892', '20536545', '20537510', '20571232', '20575919', '21512226', '21522972', '21536398', '21539615', '21561155', '21578047', '21782898', '21789436', '21837899', '21843195', '21843783', '21868208', '21882946', '22079646', '22082693', '25782119', '44310218', '25310760', '25315500', '25315736', '25328289', '25448040', '25480516', '25500519', '25506998', '25508817', '25516423', '25522012', '25569398', '25580693', '25583593', '25639016', '25667387', '25693801', '25714875', '25741092', '25780001', '25784030', '00171796', '00186945', '00410919', '00444299', '00445295', '00447998', '00210494', '00216193', '00237483', '00245286', '00420291', '00443593', '00443915', '00447296', '00459990', '00470395', '00487367', '00489194', '00494735', '00499497', '00504853', '00522027', '00523315', '00683966', '00803833', '00807719', '01291802', '02039899', '02064997', '02367590', '02429097', '02440994', '00885469', '00915715', '00931393', '01012527', '00478277', '00479902', '00491646', '00495490', '00504897', '00508005', '00509894', '00521796', '00521991', '00793389', '00813396', '00826849', '00827838', '00830949', '01186062', '01188847', '01269911', '02041403', '02392442', '02420193', '02443295', '03598719', '03631990', '03633916', '03637076', '03639491', '27396997', '27428697', '27437592', '27544590', '27550785', '27557995', '27660994', '27714794', '27730597', '27825785', '27858131', '27974411', '00461338', '00468699', '00484625', '00494794', '00498593', '00503990', '00504568', '00797399', '00801362', '00811227', '00812438', '01159367', '01299256', '02150333', '02290769', '02386937', '02437190', '03604136', '03604674', '03617493', '03622197', '03624196', '03628591', '03652885', '03654784', '03657022', '03657315', '03657644', '03662074', '03664219', '00949550', '01014020', '01052892', '01044613', '01056891', '01070350', '01072165', '01086190', '01111995', '01126899', '01136055', '01142554', '01152097', '01543946', '01870099', '02852196', '02857194', '02857337', '02872566', '02883194', '02889393', '02899116', '03123035', '03223534', '03312894', '03353314', '03358288', '03359298', '03366990', '03368090', '03368497', '03465933', '03467369', '03474906', '03477232', '03484507', '03492964', '03496242', '03502855', '03570416', '03570840', '03583592', '05294292', '05332851', '05341190', '05388638', '01320797', '01331026', '00107103', '03696747', '04035596', '04052892', '04325926', '06613418', '06649616', '06661718', '06704207', '06767852', '06775019', '06783693', '06804918', '06901247', '06922172', '01315431', '00246031', '00254716', '00420430', '00446591', '00461214', '00479197', '00483391', '00517207', '00518133', '00521692', '00800596', '00828396', '00830091', '01158811', '01161528', '01170217', '01189494', '01231413', '01279955', '01296017', '01298170', '02416395', '02421590', '02438993', '03601726', '03615121', '03618805', '03630098', '01128299', '01134455', '01150685', '01545995', '01554290', '01847924', '01872596', '01889338', '02866765', '02881316', '02890000', '03099690', '03121058', '03228512', '03312143', '03356997', '03362354', '03483828', '03489693', '03496301', '03498899', '03499993', '03501815', '03573253', '03584017', '05329179', '05389019', '05631110', '05933194', '06164691', '01327228', '02525593', '02607352', '02614895', '02663801', '02705793', '02707196', '02756993', '02769891', '02791836', '02793380', '02808795', '02832337', '04626092', '04642595', '05227339', '05255080', '07597420', '07645909', '07664993', '27541596', '27557592', '27575708', '27729929', '27732694', '27748298', '27858518', '27988895', '27991575', '00001598', '00105297', '01539793', '02447197', '02449093', '02626299', '02633048', '02698833', '02715022', '02720237', '02720361', '02726094', '02727099', '02727228', '02729415', '02761216', '02843685', '04637093', '04825103', '04827393', '05202956', '05243652', '00927497', '00968141', '00974798', '00999428', '01047445', '01065187', '01079064', '01096356', '01127391', '01154290', '01809896', '01332492', '02601098', '02660894', '02661685', '02683498', '02724595', '02725186', '02738454', '02742459', '02742887', '02745504', '02749689', '02761178', '02791827', '02801799', '02814232', '02817292', '02825239', '02825434', '02844714', '02849733', '04634477', '04644383', '04646363', '04651821', '04808984', '04827209', '05234198', '00860198', '00961871', '00962833', '00964219', '00976235', '01016843', '01045599', '01053105', '01118065', '01127392', '01158185', '01339993', '01501699', '01539318', '01541191', '01541323', '02445594', '02614314', '02653390', '02664039', '02696501', '02702248', '02709354', '02728850', '02734480', '02743162', '02753296', '02756161', '02756647', '02768144', '02831492', '02836516', '02845926', '04433110', '04628771', '04749482', '04816275', '05071994', '07563682', '07565650', '07568395', '07635118', '07644039', '27431003', '27709442', '27719737', '27727896', '27735591', '27748138', '27913733', '27927662', '27969554', '01844792', '02038195', '02854038', '02886563', '02888995', '02897941', '02898019', '03102594', '03303117', '03311619', '03351844', '03363495', '03372193', '03383367', '03462591', '03500998', '03567941', '03569288', '03578259', '03583895', '05376114', '05641295', '05929891', '05958196', '06001316', '06051328', '06070399', '06080037', '06124568', '06142515', '06155296', '06163217', '06178615', '06206604', '27395095', '27417641', '27419730', '27422210', '27570554', '27578302', '27861599', '27979659', '00062090', '00070923', '00120018', '03849797', '03861183', '03862793', '03871137', '03885592', '04002397', '04041591', '04211233', '06597885', '06606466', '06662114', '06690038', '06738558', '06803689', '06828097', '06872819', '06873623', '06882307', '06935802', '07020257', '07025946', '08419910', '08434789', '08434976', '03671131', '03671542', '03672117', '03679051', '03682719', '03683194', '07075795', '07098233', '07100015', '07139219', '07149593', '07169305', '07217229', '07223093', '07263098', '07350714', '07432819', '07491723', '07492248', '07495615', '07508094', '00106639', '03694617', '03699680', '03862794', '03866191', '03870583', '03893577', '04023390', '04035738', '04072392', '06586498', '06630092', '06694898', '06696397', '06713019', '06763198', '06804592', '06849473', '06884441', '06884497', '06898591', '06914518', '06917602', '06917924', '06934111', '06944306', '06986125', '06990556', '08403290', '08420190', '03609142', '03627790', '03644331', '03664032', '03668597', '03678068', '03678595', '03680337', '03684490', '07119438', '07157509', '07168396', '07225449', '07257008', '07290314', '07301014', '07315726', '07359050', '07381101', '00044110', '00080294', '00128105', '03701158', '03853740', '03856547', '03862386', '04057818', '04068415', '04216630', '06636088', '06637617', '06742795', '06743744', '06746266', '06769880', '06780098', '06829499', '06878318', '06904597', '06946496', '03634984', '03640456', '03644717', '03645384', '03648669', '03663708', '03674650', '03677643', '03678946', '03681994', '03682836', '03684214', '07098216', '07126420', '07136191', '07138997', '07142995', '07147891', '07161290', '07224289', '07254698', '07357796', '07362598', '07379118', '07384189', '07395998', '07428522', '07450991', '07466517', '07471609', '07475703', '07488123', '07510992', '08898993', '09003591', '09011215', '09049792', '09061649', '09062953', '09070099', '09090105', '09095955', '09192431', '09222486', '09223317', '09242645', '09300896', '09307150', '10050693', '10060692', '10071901', '10072799', '10073711', '10084337', '10096301', '10111197', '10125499', '10130698', '10149891', '10161141', '10187506', '10196815', '10198594', '10200617', '10210997', '10215770', '10234271', '10237221', '10242098', '15635018', '07667028', '07680858', '07684595', '07687992', '07688908', '07727580', '07728198', '07761996', '07875698', '07899318', '09324897', '09361127', '09368201', '09400628', '09468691', '09469641', '09475011', '09477440', '09497750', '09503531', '09512691', '09523895', '09550277', '08914795', '08928014', '09002597', '09014197', '09015096', '09059333', '09123720', '09137994', '09166791', '09167051', '09180609', '09181696', '09194417', '09197986', '09203218', '09221139', '09268699', '09286190', '10045292', '10045497', '10050478', '10067999', '10071986', '10072926', '10076714', '10091594', '10091634', '10117893', '10134995', '10139154', '10153795', '10171398', '10174099', '10182415', '10183523', '10195118', '10239648', '10242697', '15630126', '07533099', '07595891', '07613557', '07613694', '07623323', '07678595', '07800280', '07819887', '07822792', '07835101', '07902319', '07913218', '07934598', '07954683', '07958979', '09324421', '09346590', '09372998', '09384748', '09423796', '09431017', '09436199', '09461513', '09475679', '09479751', '09481034', '10251719', '10255395', '10255887', '10275635', '10292446', '10314315', '10324995', '10339416', '10348595', '10356199', '10356318', '10357594', '10360393', '10393075', '10394404', '10413810', '10414424', '10430593', '10433314', '10439658', '10452015', '10455993', '10460094', '10460670', '10466320', '10467493', '16428994', '16494098', '16520386', '16526793', '16548217', '16557191', '16563357', '16616334', '16665544', '16700633', '16716819', '16718111', '16730884', '16733547', '16760192', '16788392', '16797597', '08502597', '08535993', '08540014', '08566316', '08567096', '08620122', '08640590', '08643593', '08665559', '08684201', '08689190', '08737241', '08752209', '08763242', '08775732', '08887320', '09600315', '09608997', '09615744', '09616094', '09617298', '09635299', '09641497', '09644299', '09683057', '09706143', '01863796', '02883343', '02889693', '03300757', '03306135', '03362693', '03369216', '03480046', '03496811', '03503748', '03566444', '05367094', '05397714', '05417117', '05618673', '06034517', '06071093', '06084093', '06088450', '06091766', '06117718', '06205292', '06211091', '06265914', '06284293', '03658731', '03660031', '03660996', '03674393', '03680891', '07136017', '07144496', '07180441', '07245277', '07263499', '07340901', '07450228', '07453396', '07470744', '07475817', '07482095', '07500499', '08911195', '08912302', '08915930', '08922620', '09748854', '09765698', '10505169', '10516630', '10528318', '10535623', '10581916', '10586615', '10619530', '10621070', '10632313', '10649299', '10683443', '10688391', '10694418', '18114592', '18118977', '18123893', '18138514', '18177734', '15694292', '15702399', '15731599', '15754191', '15974699', '15985955', '16001723', '16001727', '16003509', '16017935', '16124616', '17600239', '17612290', '17615057', '17622466', '17624730', '17631325', '17634194', '17882795', '17895108', '17898295', '17932597', '17945397', '17956531', '17982999', '17985130', '18046319', '18048475', '29621863', '29621910', '08966419', '09014393', '09042919', '09046091', '09064034', '09085783', '09158773', '09184596', '09242340', '10048591', '10066491', '10090054', '10104225', '10119420', '10124439', '10131102', '10174535', '10180596', '10195494', '10234930', '10237143', '10245544', '15619897', '15639977', '15644260', '15653797', '15682618', '15708882', '07570295', '07609519', '07611754', '07625012', '07687318', '07702018', '07716253', '07759494', '07921514', '09356916', '09376417', '09430118', '09488494', '09492994', '09496299', '09517499', '09550847', '09563794', '29633599', '29642602', '29648890', '29648993', '29650093', '29663992', '29673096', '29676514', '29687444', '29688606', '29731912', '30415616', '30423991', '30575824', '32121451', '32129891', '32138169', '32295463', '32386427', '32404943', '32405947', '32542675', '32731100', '32733301', '32793203', '32872295', '32897491', '06206503', '06544316', '06552096', '06557394', '06566528', '07986793', '08041589', '08050899', '08053045', '08137196', '08143816', '08146696', '08168892', '08191387', '08201719', '08314894', '08320097', '08326959', '09830790', '09838496', '09845149', '09865332', '09883515', '09896994', '09905441', '09921863', '09951720', '09951981', '09964737', '09536518', '09544945', '09547218', '09547725', '09551659', '09565887', '09572836', '10252414', '10345119', '10347615', '10374954', '10381093', '10407599', '10413294', '10433796', '10476393', '16420495', '16440427', '16457836', '16518843', '16524179', '16540697', '16555439', '16578693', '16599889', '16610153', '16639756', '06999922', '07044019', '07057916', '08404495', '08454591', '08461797', '08488177', '08520071', '08585094', '08601666', '08687663', '08717115', '08808805', '08815693', '09596414', '09605418', '09626603', '09653416', '09659094', '09664175', '09681096', '09706929', '09717640', '09726390', '09726797', '09755093', '09756706', '09758897', '097843

In [31]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfin_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO = b.col_01 
SET 
    a.estado = b.col_02,
    a.cl_estado= b.col_03
WHERE 
    a.cl_base = 'mayo 2026'
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

Filas afectadas: 653

In [32]:
exec_query_sql(server_sa, "VALENTINA", user_sa, pwd_sa, "EXEC VALENTINA.DBO.ALFIN_BASE_VALENTINA", "SP actualizar BASE ALFIN")

SP actualizar BASE ALFIN | realizado | duración: 57.58 seg

In [ ]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfin_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO = b.col_01 
SET 
    a.estado = b.col_02,
    a.cl_estado= b.col_03
WHERE 
    a.cl_base = 'mayo 2026'
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

OperationalError: (pymysql.err.OperationalError) (1969, 'Query execution was interrupted (max_statement_time exceeded)')
[SQL:
UPDATE crm_target.alfin_clientes a
INNER JOIN crm_target.tb_temporal b
    ON TRIM(CAST(a.NUMERO_DOCUMENTO AS CHAR)) = TRIM(CAST(b.col_01 AS CHAR))
SET
    a.estado = b.col_02,
    a.cl_estado= b.col_03
WHERE
    a.cl_base = 'mayo 2026'
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
# update_mysql_en_bloques(
#     df=df_list,
#     tabla="alfin_clientes",
#     periodo="mayo 2026",
#     col_llave_mysql="NUMERO_DOCUMENTO",
#     col_valor_mysql="estado",
#     col_llave_df="dni_cliente",
#     col_valor_df="retiro",
#     host=server_valentina,
#     user=user_valentina,
#     password=pwd_valentina,
#     database=db_valentina,
#     port=port_mysql,
#     batch_size=2000,
#     validar_sin_grabar=False
# )

Total registros a procesar: 1648
Lote 0 - 1648 actualizado | filas afectadas: 0
Proceso terminado. Total filas afectadas: 0

## ejecutar query

In [ ]:
from sqlalchemy import create_engine


engine = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

In [ ]:
with engine.begin() as conn:
    result = conn.execute(text("""
        UPDATE crm_target.alfin_clientes
        SET cl_estado = 3
        WHERE estado <> 'ACTIVO'
        AND cl_base = 'mayo 2026'
    """))
    
    print("Filas afectadas:", result.rowcount)

## actualizar dni a otro lote

In [3]:
filename='dni_repetidos_alfin.csv'

filePath = os.path.join(ruta_csv, filename)
df_list = pd.read_csv(filePath)

In [5]:
df_list["NUMERO_DOCUMENTO"] = (
    df_list["NUMERO_DOCUMENTO"]
    .astype(str)
    .str.zfill(8)
)
df_list.head()

  NUMERO_DOCUMENTO
0         46507674
1         40963267
2         41782588
3         40658062
4         09457398

In [6]:
df_list['lote_ref']='BD-Target -ASM'

In [7]:
update_mysql_en_bloques(
    df=df_list,
    tabla="alfin_clientes",
    periodo="mayo 2026",
    col_llave_mysql="NUMERO_DOCUMENTO",
    col_valor_mysql="lote",
    col_llave_df="NUMERO_DOCUMENTO",
    col_valor_df="lote_ref",
    host=server_valentina,
    user=user_valentina,
    password=pwd_valentina,
    database=db_valentina,
    port=port_mysql,
    batch_size=2000,
    validar_sin_grabar=False
)

Total registros a procesar: 1066
Lote 0 - 1066 actualizado | filas afectadas: 1066
Proceso terminado. Total filas afectadas: 1066

In [ ]:
BD-Target -ASM

In [5]:
exec_query_sql(server_zeus, "MAEBA", user_zeus, pwd_zeus, "ADM_OBJ_TG.spFunnelDinersTc", "SP funnel diners_tc Zeus")

SP funnel diners_tc Zeus | realizado | duración: 19.96 seg

In [ ]:
overwrite_table_SQL(spark,df_prueba_1,f'borrar_TARGET_202604_01',server_kishin,user_kishin,pwd_kishin,'DANTALION')
overwrite_table_SQL(spark,df_prueba_2,f'borrar_TARGET_202604_02',server_kishin,user_kishin,pwd_kishin,'DANTALION')
overwrite_table_SQL(spark,df_prueba_ch,f'borrar_TARGET_202604_ch',server_kishin,user_kishin,pwd_kishin,'DANTALION')

df_list filas: 1066

In [ ]:
df_dni filas: 128183
df_list filas: 12546

In [ ]:
ssss

In [7]:
print(df_list.columns)
print(df_long.columns)

Index(['TELEFONO'], dtype='object')
Index(['NUMERO_DOCUMENTO', 'tipo_telf', 'TELEFONO'], dtype='object')

df_list filas: 1

In [ ]:
df_list filas: 2036

NUMERO_DOCUMENTO    1
retiro              1
dtype: int64

In [10]:
df_list.head()

  NUMERO_DOCUMENTO         retiro
0         40503275  Retirar Telef

Total registros a procesar: 1
Lote 0 - 1 actualizado | filas afectadas: 1
Proceso terminado. Total filas afectadas: 1