In [1]:
import sys 
sys.path.append('C:/Users/Data/Documents/lazo_fernando/target_script_01/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *

spark = SparkSession.builder \
    .appName("SparkExample") \
    .master("local[*]") \
    .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.4.0.jre11.jar') \
    .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.4.0.jre11.jar') \
    .config('spark.executor.memory', '8g') \
    .config('spark.driver.memory', '8g') \
    .getOrCreate()

c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\testing\utils.py:127: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

In [2]:
port_mysql = '3306'

user_valentina = "flazo"
pwd_valentina = "T4rg3t2026$$"
server_valentina = "db.mastermold.dev"
db_valentina = "crm_target"


server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

engine_mysql = create_engine(
    f"mysql+pymysql://{user_valentina}:{pwd_valentina}@{server_valentina}:{port_mysql}/{db_valentina}"
)

In [ ]:
query = f"""
    select * from crm_target.alfin_clientes
where cl_id  in(3495810,
3495811,3495812,3495813,3495814,3495815,3495817,3495818,3495819,3495820,3495822,3495824,3495825,3495826,3495828,3495829,3495830,3495831,3495832,3495833,3495835,3495836,3495837,3495838,3495839,3495842,3495843,3495844,3495846,3495847,3495848,3495850,3495851,3495854,3495856,3495857,3495858,3495859,3495860,3495861,3495867,3495868,3495869,3495870,3495871,3495872,3495874,3495875,3495876,3495877,3495879,3495880,3495881,3495882,3495883,3495884,3495885,3495886,3495887,3495888,3495892,3495894,3495896,3495898,3495899,3495902,3495903,3495904,3495905,3495906,3495907,3495908,3495910,3495911,3495912,3495913,3495914,3495916,3495917,3495919,3495921,3495922,3495923,3495924,3495925,3495928,3495929,3495930,3495932,3495934,3495935,3495937,3495938,3495940,3495945,3495947,3495948,3495949,3495950,3495951,3495953,3495954,3495955,3495956,3495957,3495959,3495960,3495962,3495963,3495965,3495968,3495969,3495971,3495972,3495973,3495974,3495976,3495977,3495980,3495981,3495982,3495983,3495985,3495986,3495987,3495988,3495989,3495991,3495992,3495996,3495997,3495998,3496000,3496002,3496003,3496004,3496006,3496007,3496008,3496009,3496010,3496012,3496017,3496019,3496021,3496022,3496023,3496024,3496025,3496026,3496027,3496028,3496029,3496030,3496032,3496033,3496034,3496035,3496036,3496037,3496038,3496040,3496041,3496042,3496043,3496044,3496045,3496046,3496047,3496048,3496049,3496050,3496052,3496053,3496054,3496055,3496056,3496057,3496058,3496060,3496061,3496063,3496064,3496066,3496067,3496068,3496069,3496070,3496072,3496073,3496074,3496076,3496077,3496080,3496081,3496084,3496085,3496086,3496087,3496088,3496089,3496091,3496093,3496094,3496095,3496096,3496098,3496099,3496100,3496101,3496102,3496103,3496105,3496106,3496107,3496108,3496109,3496110,3496111,3496112,3496114,3496115,3496118,3496119,3496120,3496121,3496126,3496127,3496128,3496129,3496131,3496132,3496135,3496136,3496137,3496138,3496139,3496140,3496144,3496145,3496146,3496147,3496148,3496149,3496150,3496151,3496153,3496154,3496155,3496157,3496158,3496159,3496161,3496163,3496166,3496167,3496168,3496169,3496170,3496171,3496173,3496174,3496175,3496178,3496179,3496180,3496181,3496182,3496183,3496184,3496186,3496187,3496188,3496190,3496191,3496192,3496193,3496194,3496195,3496196,3496197,3496199,3496200,3496201,3496203,3496205,3496207,3496208,3496209,3496210,3496211,3496212,3496213,3496214,3496216,3496217,3496218,3496219,3496220,3496221,3496222,3496224,3496225,3496226,3496229,3496230,3496233,3496234,3496236,3496237,3496238,3496239,3496240,3496241,3496243,3496249,3496251,3496252,3496253,3496255,3496256,3496259,3496260,3496261,3496262,3496263,3496265,3496266,3496267,3496269,3496272,3496273,3496274,3496276,3496277,3496278,3496280,3496281,3496282,3496283,3496284,3496285,3496286,3496288,3496289,3496291,3496293,3496295,3496297,3496298,3496300,3496301,3496302,3496303,3496304,3496305,3496306,3496307,3496308,3496313,3496314,3496317,3496318,3496319,3496321,3496322,3496325,3496326,3496328,3496329,3496330,3496331,3496333,3496335,3496338,3496339,3496340,3496341,3496342,3496343,3496344,3496348,3496349,3496350,3496351,3496352,3496353,3496354,3496355,3496356,3496357,3496358,3496360,3496361,3496362,3496363,3496364,3496365,3496368,3496370,3496372,3496373,3496375,3496376,3496378,3496380,3496383,3496385,3496387,3496388,3496389,3496391,3496392,3496393,3496394,3496395,3496396,3496399,3496400,3496401,3496403,3496405,3496406,3496408,3496409,3496410,3496411,3496414,3496415,3496416,3496419,3496421,3496422,3496423,3496426,3496427,3496428,3496429,3496430,3496431,3496434,3496435,3496436,3496440,3496441,3496443,3496444,3496445,3496446,3496447,3496448,3496449,3496450,3496452,3496453,3496454,3496455,3496458,3496459,3496460,3496461,3496462,3496464,3496465,3496466,3496467,3496468,3496471,3496472,3496473,3496475,3496476,3496477,3496478,3496479,3496480,3496482,3496483,3496484,3496486,3496487,3496488,3496490,3496494,3496495,3496496,3496497,3496498,3496499,3496500,3496501,3496503,3496505,3496507,3496508,3496509,3496511,3496512,3496513,3496514,3496515,3496516,3496519,3496521,3496523,3496524,3496525,3496526,3496528,3496529,3496530,3496538,3496539,3496540,3496541,3496544,3496546,3496547,3496548,3496549,3496550,3496551,3496552,3496553,3496554,3496555,3496556,3496558,3496559,3496560,3496561,3496562,3496564,3496565,3496566,3496567,3496568,3496570,3496571,3496574,3496576,3496577,3496578,3496579,3496580,3496581,3496582,3496584,3496585,3496587,3496589,3496590,3496591,3496592,3496594,3496596,3496598,3496602,3496604,3496609,3496610,3496612,3496613,3496615,3496616,3496617,3496619,3496620,3496621,3496622,3496623,3496624,3496625,3496627,3496629,3496630,3496631,3496632,3496634,3496635,3496637,3496638,3496640,3496642,3496644,3496645,3496646,3496647,3496648,3496649,3496650,3496652,3496655,3496659,3496660,3496663,3496664,3496665,3496667,3496668,3496670,3496673,3496674,3496675,3496676,3496677,3496678,3496680,3496682,3496683,3496684,3496685,3496686,3496687,3496688,3496689,3496690,3496691,3496692,3496693,3496694,3496695,3496696,3496698,3496700,3496701,3496702,3496704,3496705,3496706,3496707,3496708,3496710,3496713,3496714,3496715,3496716,3496717,3496718,3496721,3496722,3496723,3496725,3496726,3496728,3496729,3496730,3496731,3496732,3496733,3496734,3496735,3496736,3496737,3496738,3496739,3496740,3496742,3496743,3496744,3496746,3496747,3496749,3496751,3496753,3496754,3496756,3496759,3496760,3496765,3496767,3496768,3496769,3496771,3496772,3496775,3496776,3496779,3496780,3496781,3496782,3496783,3496785,3496786,3496787,3496789,3496790,3496791,3496792,3496793,3496794,3496795,3496796,3496797,3496799,3496802,3496803,3496805,3496807,3496808,3496809,3496810,3496811,3496812,3496813,3496814,3496816,3496818,3496819,3496820,3496821,3496822,3496824,3496825,3496826,3496828,3496830,3496832,3496833,3496834,3496836,3496838,3496839,3496840,3496844,3496845,3496846,3496847,3496849,3496850,3496852,3496853,3496854,3496856,3496857,3496858,3496860,3496861,3496862,3496863,3496864,3496865,3496866,3496867,3496868,3496869,3496870,3496871,3496872,3496873,3496874,3496877,3496879,3496880,3496881,3496883,3496884,3496885,3496887,3496889,3496890,3496891,3496892,3496893,3496894,3496896,3496902,3496903,3496904,3496905,3496906,3496907,3496908,3496910,3496911,3496912,3496913,3496916,3496917,3496918,3496919,3496920,3496921,3496922,3496923,3496924,3496925,3496926,3496927,3496928,3496930,3496931,3496932,3496933,3496934,3496935,3496936,3496937,3496938,3496939,3496940,3496941,3496942,3496943,3496944,3496945,3496946,3496947,3496948,3496951,3496952,3496953,3496954,3496956,3496957,3496958,3496959,3496960,3496962,3496963,3496964,3496965,3496967,3496969,3496970,3496971,3496972,3496973,3496974,3496975,3496976,3496977,3496978,3496979,3496983,3496984,3496985,3496987,3496988,3496990,3496992,3496993,3496995,3496997,3496998,3496999,3497000,3497001,3497002,3497003,3497004,3497006,3497008,3497010,3497012,3497013,3497015,3497016,3497017,3497018,3497019,3497021,3497022,3497023,3497024,3497025,3497026,3497028,3497029,3497031,3497032,3497033,3497034,3497035,3497036,3497037,3497039,3497040,3497041,3497043,3497045,3497047,3497048,3497049,3497050,3497051,3497052,3497053,3497055,3497056,3497057,3497058,3497059,3497060,3497061,3497062,3497063,3497064,3497065,3497067,3497068,3497069,3497071,3497072,3497074,3497076,3497078,3497080,3497082,3497085,3497086,3497087,3497088,3497090,3497092,3497095,3497098,3497101,3497102,3497104,3497105,3497106,3497107,3497108,3497110,3497111,3497112,3497113,3497114,3497116,3497117,3497118,3497119,3497121,3497122,3497123,3497125,3497126,3497128,3497129,3497130,3497132,3497133,3497134,3497135,3497137,3497138,3497139,3497140,3497141,3497143,3497144,3497145,3497146,3497147,3497148,3497149,3497150,3497151,3497152,3497154,3497155,3497156,3497158,3497159,3497161,3497162,3497163,3497164,3497165,3497168,3497169,3497171,3497172,3497173,3497174,3497176,3497177,3497178,3497179,3497180,3497181,3497182,3497184,3497185,3497186,3497188,3497189,3497190,3497191,3497195,3497196,3497200,3497201,3497202,3497205,3497206,3497207,3497208,3497209,3497211,3497212,3497213,3497214,3497215,3497216,3497217,3497220,3497221,3497223,3497224,3497225,3497226,3497227,3497229,3497231,3497232,3497233,3497235,3497236,3497238,3497239,3497240,3497241,3497242,3497243,3497244,3497245,3497246,3497247,3497250,3497251,3497252,3497253,3497257,3497258,3497259,3497262,3497264,3497265,3497272,3497274,3497275,3497276,3497281,3497282,3497283,3497284,3497285,3497286,3497288,3497289,3497290,3497291,3497292,3497294,3497299,3497300,3497301,3497302,3497303,3497304,3497305,3497308,3497309,3497310,3497311,3497315,3497316,3497317,3497319,3497320,3497321,3497323,3497324,3497325,3497326,3497328,3497330,3497332,3497333,3497334,3497335,3497336,3497338,3497339,3497343,3497344,3497345,3497346,3497348,3497350,3497351,3497353,3497354,3497355,3497356,3497357,3497358,3497359,3497362,3497363,3497365,3497366,
3497367,
3497371,
3499872,
3525267)
and oferta_max>=5000
"""
df_valentian = pd.read_sql(query, engine_mysql)

In [37]:
query = """
select * from DANTALION.dbo.Base_Maestra_Alfin_bk
where fecha_envio>='2026-08-01'
"""
df_maestra = obtener_tabla_sql(spark,query,server_kishin,user_kishin,pwd_kishin,db_kishin)

query = """
	SELECT distinct Dni as NUMERO_DOCUMENTO FROM THOTH.dbo.Tmp_LLamadas_Alfin_5 
    where Descripcion_ in(
        'EXPRESO FUTURA DENUNCIA ANTE INDECOPI O REGULADOR',
        'EXPRESO QUE NO AUTORIZÓ USO DE DATOS PERSONALES',
        'EXPRESO RECIBIR MÚLTIPLES LLAMADAS',
        'FUERA DE SERVICIO'
    )
    """
df_quitar=obtener_tabla_sql(spark,query,server_zeus,user_zeus,pwd_zeus,db_zeus)
df_maestra=df_maestra.join(df_quitar,['NUMERO_DOCUMENTO'],how='left_anti')

In [40]:
df_maestra=df_maestra.withColumn("estado",F.lit('ACTIVO'))
df_maestra=df_maestra.withColumn("cl_estado",F.lit('1'))
df_maestra=df_maestra.drop('PILOTO_RETENCION', 'REP1', 'marca3', 'SERVICIO', 'FLAT2', 'ACCION', 'REP2', 'RETIRO', 'marca1', 'marca2', 'AÑO_DURACION_BASE', 'CAMP_BONO')
df_maestra=df_maestra.fillna(0)

In [41]:
df_maestra_pd=df_maestra.toPandas()

c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:348: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  [PACKAGE_NOT_INSTALLED] PyArrow >= 18.0.0 must be installed; however, it was not found.
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)
c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\types.py:778: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\types.py:778: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

In [42]:
df_maestra_pd["NUMERO_DOCUMENTO"] = (
    df_maestra_pd["NUMERO_DOCUMENTO"]
    .astype(str)
    .str.zfill(8)
)

df_valentian["NUMERO_DOCUMENTO"] = (
    df_valentian["NUMERO_DOCUMENTO"]
    .astype(str)
    .str.zfill(8)
)
df_maestra_pd=df_maestra_pd[~df_maestra_pd['NUMERO_DOCUMENTO'].isin(df_valentian['NUMERO_DOCUMENTO'])]
df_regular=df_maestra_pd[df_maestra_pd['lote'] != 'INVENTARIO'].copy()

In [52]:
['NUMERO_DOCUMENTO', 'TIPO_DOI', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'proveedor', 'lote', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'PILOTO_PLAZAS', 'INTENSIDAD_MAX', 'MES_DURACION_BASE', 'estado', 'cl_estado']use

SyntaxError: invalid syntax (2536623707.py, line 1)

In [59]:
df_nuevo = df_regular[
    (df_regular['USER_V3'].isin(['7. Peers','3. MES + PLD Peers'])) &
    (df_regular["FRESCURA"].isin(['0','1', '4'])) &
    (df_regular["PROPENSION_IC"].isin(['1', '2','3']))
].copy()
df_nuevo.shape

(12023, 174)

In [53]:
df_regular["USER_V3"].unique()

<StringArray>
[                      '7. Peers',         '14. Otros Bancarizados',
             '3. MES + PLD Peers',              '8. Tarjetero Cash',
          '4. MES + PLD No Peers',                       '6. MES B',
           '2. sunedu & sunarp B',                       '5. MES A',
          '11. Dependiente Banca',              '9. Dependiente BN',
           '1. sunedu & sunarp A',            '12. Independiente A',
 '13. No dependiente + Convenios',    '10. Dependiente + Convenios']
Length: 14, dtype: str

In [49]:
df_regular.shape

(161861, 174)

In [29]:
vale=set(df_valentian.columns.to_list())
maestra=set(df_maestra.columns)

In [ ]:
qwdasdsñasd

In [36]:
df_regular.shape

(175755, 174)

In [ ]:
df_maestra_pd['']

In [33]:
df_maestra_pd.count()

TIPO_DOI                  0
NUMERO_DOCUMENTO     240557
NOMBRES              236947
APELLIDO_PATERNO     175755
APELLIDO_MATERNO     175685
                      ...
PILOTO_PLAZAS        240557
INTENSIDAD_MAX       240557
MES_DURACION_BASE    233259
estado               240557
cl_estado            240557
Length: 174, dtype: int64

In [ ]:
['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'lot', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']lot

['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']

In [ ]:
df_nuevo['cl_base']=='agosto 2026'

0         True
1         True
2         True
3         True
4         True
          ...
238801    True
238802    True
238803    True
238804    True
238807    True
Name: cl_base, Length: 161861, dtype: bool

In [62]:
engine_mysql.dispose()

In [67]:
df_nuevo=df_nuevo.fillna(0)

In [68]:

df_nuevo.to_sql(
    name="alfin_clientes",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

12023

In [32]:
query = f"""
    SELECT * from crm_target.alfin_clientes
    where cl_base='agosto 2026'
    and cl_estado=1
    and cl_telf1<>0
"""
df_valentiana_01 = pd.read_sql(query, engine_mysql)

In [9]:
filename='TARGET.txt'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_target_desembolso = pd.read_csv(ruta_archivo,sep='|')
df_target_desembolso = df_target_desembolso[['DNI']].copy()
df_target_desembolso['CANAL']='CANAL'
filename='ACUM_DESEM.txt'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_fugas = pd.read_csv(ruta_archivo,sep='|')
df_fugas = df_fugas[['DNI','CANALVENTA']].copy()
df_target_desembolso['DNI'] = (
    df_target_desembolso['DNI']
    .astype(str)
    .str.replace(r'\D', '', regex=True)   
    .replace('', pd.NA)                     
    .str.zfill(8)                           
)
df_fugas['DNI'] = (
    df_fugas['DNI']
    .astype(str)
    .str.replace(r'\D', '', regex=True)   
    .replace('', pd.NA)                     
    .str.zfill(8)                           
)

df_desembolso=df_fugas.merge(
    df_target_desembolso,
    on=['DNI'],
    how='left'
)
df_desembolso = df_desembolso.fillna("OTROS")
df_desembolso.rename(columns={'DNI': 'dni_cliente'}, inplace=True)


filename='RetiroDefinitivo_BlackList.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_def_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_BlackList.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_Telefonos.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_telf = pd.read_csv(ruta_archivo,sep='|')
filename='retiro_correo_alfin.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_retiro_correo = pd.read_csv(ruta_archivo,sep=',')

# filename='desembolso.csv'
# ruta_archivo = os.path.join(ruta_alfin, filename)
# df_des = pd.read_csv(ruta_archivo,sep=';')

df_def_blacklist = df_def_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_blacklist = df_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_telf= df_telf.rename(columns={'TELEFONO': 'celular'})
df_retiro_correo= df_retiro_correo.rename(columns={'DNI': 'dni_cliente'})

# Blacklists de DNI
# df6 = df_des.copy()
# df6["celular"] = None
# df6 = df6[["dni_cliente", "celular"]]

# Blacklists de DNI
df1 = df_def_blacklist.copy()
df1["celular"] = None
df1 = df1[["dni_cliente", "celular"]]

df2 = df_blacklist.copy()
df2["celular"] = None
df2 = df2[["dni_cliente", "celular"]]

# Blacklist de teléfonos
df3 = df_telf.copy()
df3["dni_cliente"] = None
df3 = df3[["dni_cliente", "celular"]]

# Archivo con DNI y celular
df4 = df_retiro_correo[["dni_cliente", "celular"]].copy()

# Unir todo
df_retiros = pd.concat(
    [df1, df2, df3, df4],
    ignore_index=True
)

In [7]:
df_valentian.columns

Index(['count(*)'], dtype='str')

In [10]:

dni_retiro = set(df_retiros['dni_cliente'].dropna())
cel_retiro = set(df_retiros['celular'].dropna())
dni_desembolso = set(df_desembolso['dni_cliente'].dropna())


df_valentian=df_valentian[
    ~df_valentian['NUMERO_DOCUMENTO'].isin(dni_retiro)&
    ~df_valentian['cl_telf1'].isin(cel_retiro)&
    ~df_valentian['NUMERO_DOCUMENTO'].isin(dni_desembolso)
    ].copy()
df_valentian.shape

(7007, 178)

In [36]:
df_valentiana_01=df_valentiana_01[
    ~df_valentiana_01['NUMERO_DOCUMENTO'].isin(dni_d)
    ].copy()
df_valentiana_01.shape

(22984, 178)

In [37]:
dni_d = set(df_quitar_pd['NUMERO_DOCUMENTO'].dropna())

In [8]:
query = """
	SELECT Dni as NUMERO_DOCUMENTO FROM THOTH.dbo.Tmp_LLamadas_Alfin 
    where list_description<>'provicional'
    """
df_quitar=obtener_tabla_sql(spark,query,server_zeus,user_zeus,pwd_zeus,db_zeus)

In [74]:
df_vale1=df_valentiana_01.merge(df_nuevo[['NUMERO_DOCUMENTO']], on='NUMERO_DOCUMENTO', how='inner')

In [9]:
df_quitar_pd=df_quitar.toPandas()

c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Users\Data\Documents\lazo_fernando\target_script_01\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:348: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  [PACKAGE_NOT_INSTALLED] PyArrow >= 18.0.0 must be installed; however, it was not found.
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)

In [75]:
df_vale1 = df_vale1.drop_duplicates(
    subset=["NUMERO_DOCUMENTO"]
).copy()

In [ ]:
['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']cl_t

['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']

In [ ]:
from pyspark.sql.functions import lit

df1=df_prueba.select(
    'numero_documento',
    'TELEFONO',
    lit(12).alias('uno')
).join(
    df_base_p.select('cl_id',
    'nombres',
    'numero_documento'),
    ['numero_documento'],
    'inner'
)

In [45]:
df_nuevo = df_valentiana_01[
    (df_valentiana_01['USER_V3'].isin(['7. Peers','3. MES + PLD Peers'])) &
    (df_valentiana_01["FRESCURA"].isin(['0', '4'])) &
    (df_valentiana_01["PROPENSION_IC"].isin(['1']))
].copy()
df_nuevo.shape

(10184, 178)

In [ ]:
df_valentiana_01=df_valentiana_01[
    ~df_valentiana_01['NUMERO_DOCUMENTO'].isin(dni_retiro)&
    ~df_valentiana_01['cl_telf1'].isin(cel_retiro)&
    ~df_valentiana_01['NUMERO_DOCUMENTO'].isin(dni_desembolso)
    ~df_valentiana_01['NUMERO_DOCUMENTO'].isin(dni_d)
    ].copy()
df_valentiana_01.shape

In [ ]:
['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']

['cl_id', 'TIPO_DOI', 'NUMERO_DOCUMENTO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO', 'SUCURSAL', 'TIENDA', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'FEC_NACIMIENTO', 'OFERTA_MAX', 'OFERTA_REEN', 'Tipo_verificacion', 'GRUPO_RIESGO', 'PILOTO_PLAZAS', 'proveedor', 'lote', 'estado', 'Tasa_1', 'Tasa_2', 'Tasa_3', 'Tasa_4', 'Tasa_5', 'Tasa_6', 'Tasa_7', 'segmento', 'Campana', 'PLAZO', 'TEM', 'PROPENSION_IC', 'Desgravamen', 'CUOTA', 'Edad', 'Oferta_12M', 'Tasa_12M', 'Desgravamen_12M', 'CUOTA_12M', 'Oferta_18M', 'Tasa_18M', 'Desgravamen_18M', 'CUOTA_18M', 'Oferta_24M', 'Tasa_24M', 'Desgravamen_24M', 'CUOTA_24M', 'Oferta_36M', 'Tasa_36M', 'Desgravamen_36M', 'CUOTA_36M', 'Validador_Telefono', 'Prioridad', 'Nombre_prioridad', 'Deuda_1', 'Entidad_1', 'Deuda_2', 'Entidad_2', 'Deuda_3', 'Entidad_3', 'sucursal_comercial', 'Agencia_comercial', 'Region_comercial', 'Ubicacion', 'OfertaMaximaSinSeguro', 'color', 'color_final', 'PROPENSION', 'OFERTA_FINAL', 'GARANTIA', 'Oferta_Minima_Paperless', 'RANGO_OFERTA', 'RANGO_SUELDO', 'CAPACIDAD_MAX', 'PEER', 'PROP_COMER', 'TIPO_GEST', 'CLIENTE_NUEVO', 'GRUPO_TASA', 'NUEVOS_3M', 'NUEVOS_6M', 'NUEVOS_9M', 'NUEVOS_12M', 'NUEVOS_4M', 'GRUPO_MONTO', 'TASA_VS_MONTO', 'USUARIO', 'incremento_monto_riesgos', 'FLG_DEUDA_PLUS', 'tipo_cliente_riegos', 'USER_V3', 'LEAD_CALIDAD', 'SEGMENTO_USER', 'RANGO_EDAD', 'RANGO_OFERTA2', 'PERIODO', 'RETIRO_GEST', 'MEJOR_TIPIFICACION', 'STATUS', 'FECHA_SOL', 'BASE', 'RESULTADO', 'NUM_ENRIQUECIDO', 'TIPO_CONTACTO', 'Q_VENTAS', 'LOCALIDAD', 'DESEMBOLSADO', 'MONTO_DESEMBOLSADO', 'SBI', 'CRUCE', 'PREST_PREVIO', 'ID_CLIENTE', 'RANGO_EDAD2', 'Fecha_Envio', 'TIPO_BD', 'COD_BD', 'NOMB_BD', 'MES_GESTION', 'TIPO_CLIENTE', 'GRUPO_TASA_REENGANCHE', 'SALDO_DIFERENCIAL_REENG', 'FLAG_REENG', 'RETIRO_DESEMBOLSO', 'FRESCURA', 'flag_deuda_v_oferta', 'MGNEG', 'PERFIL_RO', 'TIPO_BASE', 'cl_telf1', 'cl_telf2', 'cl_telf3', 'cl_telf4', 'cl_telf5', 'cl_telf6', 'cl_telf7', 'cl_telf8', 'cl_telf9', 'cl_telf10', 'cl_movil', 'cl_celular', 'cl_telefono', 'cl_turno', 'cl_gestor', 'cl_asesor', 'cl_accion', 'cl_gestion', 'cl_estado', 'cl_fecha_gestion', 'cl_hora_gestion', 'cl_hits', 'cl_fecha_llamar', 'cl_prioridad', 'cl_orden', 'cl_predictivo', 'cl_tiempo', 'cl_base', 'cl_mes', 'cl_carga', 'id_carga', 'cl_area', 'fecha_alimentacion', 'cl_base_ant', 'cl_accion_ant', 'cl_fecha_ant', 'campania', 'PROMOCION', 'PROMOCION2', 'nombre_base', 'NumEntidades', 'p_banco', 'tasa_minima', 'MES_DURACION_BASE', 'ANIO_DURACION_BASE', 'PERFIL_GLOBAL', 'FLG_AAHH', 'SCORE_TELEFONO', 'BLOQUE', 'INTENSIDAD_MAX']

In [11]:
df_valentian['uno']='12'

In [12]:
df_nuevo = df_valentian[
    ["cl_telf1", "cl_id", "uno", "NOMBRES"]
].copy()

In [17]:
df_nuevo.head(2)

    cl_telf1    cl_id uno                                NOMBRES
0  993411359  3495810  12  TEOFILO WELLINGTON SANCHEZSANCHEZ 0 0
1  982513634  3495812  12              MARIA HINOSTROZAGOMEZ 0 0

In [18]:
df_nuevo["NOMBRES"] = (
    df_nuevo["NOMBRES"]
    .astype(str)
    .str.replace(r"\s*0\.0$", "", regex=True)
    .str.strip()
)

In [19]:
df_nuevo["todo"] = (
    df_nuevo[["cl_telf1", "cl_id", "uno", "NOMBRES"]]
    .fillna("")
    .astype(str)
    .agg(",".join, axis=1)
)

df_nuevo = df_nuevo[["todo"]]

In [20]:
df_nuevo.head(2)

                                                todo
0  993411359,3495810,12,TEOFILO WELLINGTON SANCHE...
1     982513634,3495812,12,MARIA HINOSTROZAGOMEZ 0 0

In [22]:
df_nuevo=df_nuevo.head(1000)

In [23]:
ruta_archivo = os.path.join(ruta_alfin, 'subir_5.csv')
df_nuevo.to_csv(ruta_archivo, sep=';')