## actualizar retiro telef

In [1]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

import numpy as np

server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

engine_mysql = create_engine(
    f"mysql+pymysql://{user_envio}:{pwd_envio}@{server_envio}:{port_mysql}/{db_envio}"
)

In [6]:
query = f"""
	SELECT a.*
	FROM Alice.prospectos_correos_alfin a
	INNER JOIN Alice.prospectos_envio_alfin b
		ON a.dni_cliente = b.dni_cliente
	WHERE DATE(a.fecha_envio) IN ('2026-07-11', '2026-07-13')
	AND DATE(a.fecha_envio) = DATE(b.fecha_envio);
"""
df_prospectos_correos_alfin = pd.read_sql(query, engine_mysql)

df_prospectos_correos_alfin.shape
query = f"""
	SELECT a.*
	FROM Alice.prospectos_envio_alfin a
	INNER JOIN Alice.prospectos_correos_alfin b
		ON a.dni_cliente = b.dni_cliente
	WHERE DATE(a.fecha_envio) IN ('2026-07-11', '2026-07-13')
	AND DATE(a.fecha_envio) = DATE(b.fecha_envio);
"""
df_prospectos_envio_alfin = pd.read_sql(query, engine_mysql)
df_prospectos_envio_alfin.shape

(1123, 16)

In [8]:
df_prospectos_correos_alfin=df_prospectos_correos_alfin[['canal_campo', 'supervisor', 'ejecutivo_target', 'codigo_ejecutivo_id', 'cdv_alfin_banco', 'dni_cliente', 'nombre_cliente', 'color', 'monto_solicitado', 'celular', 'agencia_atencion', 'fecha_visita','hora_visita']]

In [10]:
df_prospectos_envio_alfin=df_prospectos_envio_alfin[['dni_vendedor', 'operador', 'dni_cliente', 'nombre_cliente', 'telefono_cliente', 'agencia_tienda', 'fecha_visita', 'monto_solicitado', 'tipo_gestion']]

In [ ]:
df_correo=df_formato[['canal_campo', 'supervisor', 'ejecutivo_target', 'codigo_ejecutivo_id', 'cdv_alfin_banco', 'dni_cliente', 'nombre_cliente', 'color', 'monto_solicitado', 'celular', 'agencia_atencion', 'fecha_visita','hora_visita']] .copy()
df_correo['tipo_carga']='MANUAL'

df_formulario=df_formato[['dni_vendedor', 'operador', 'dni_cliente', 'nombre_cliente', 'telefono_cliente', 'agencia_tienda', 'fecha_visita', 'monto_solicitado', 'tipo_gestion']].copy()

display(df_correo.head(2))
display(df_formulario.head(2))

In [11]:
df_prospectos_envio_alfin.head()

,dni_vendedor,operador,dni_cliente,nombre_cliente,telefono_cliente,agencia_tienda,fecha_visita,monto_solicitado,tipo_gestion
0,BOT,TARGET,15343243,JOSE LUIS SANCHEZ VELASQUEZ,940458253,732243 - CAÑETE,2026-07-09,14000,Derivacion
1,BOT,TARGET,23945463,NICOLAS HUGO CABANA HUAMANI,969259975,734299 - CUSCO LA CULTURA,2026-07-09,2000,Derivacion
2,BOT,TARGET,41807964,ELIZABETH ALBINA CAJALEON FLORES,991077480,734280 - PC HUANCAYO,2026-07-09,7100,Derivacion
3,BOT,TARGET,73947051,LIDALINA AUQUI ÑACAYAURI,929350308,732249 - VILLA EL SALVADOR 2,2026-07-09,3400,Derivacion
4,BOT,TARGET,22966170,JUAN CARLOS LOPEZ OMONTE,944481790,735996 - HUANUCO,2026-07-09,1600,Derivacion

In [12]:
df_prospectos_correos_alfin['tipo_carga']='MANUAL'
df_prospectos_correos_alfin['fecha_visita']='2026-07-17'
df_prospectos_envio_alfin['fecha_visita']='2026-07-17'

In [ ]:
set_correo = set(
    df_formato['agencia_atencion']
    .dropna()
    .drop_duplicates()
)

set_agencia = set(
    df_agencia['agencia_correo']
    .dropna()
    .drop_duplicates()
)
# print(set_correo & set_agencia)
print(set_agencia - set_correo)
print(set_correo -set_agencia )

In [15]:
df_validar_01 = df_validar_01.withColumn(
    "dni_cliente",
    F.right(
        F.concat(F.lit("00000000"), F.col("DNI")),
        F.lit(8)
    )
)
df_formato_01 = df_formato_01.withColumn(
    "dni_cliente",
    F.right(
        F.concat(F.lit("00000000"), F.col("dni_cliente")),
        F.lit(8)
    )
)

df_validar_01=df_validar_01.select('dni_cliente',F.col('COLOR_FINAL').alias('color'))
df_formato_01=df_formato_01.join(df_validar_01,['dni_cliente'],'left')

df_formato_01=df_formato_01.dropDuplicates(['dni_cliente'])

In [ ]:
['DNI', 'COLOR_FINAL', 'COD_USER_V3', 'USER_V3', 'PERFIL_RO', 'campaña', 'OFERTA_MAX', 'PLAZO', 'CAPACIDAD_MAX', 'FRESCURA', 'rango_deuda', 'numentidades', 'TOTAL_A_LIQUIDAR', 'TASA_CREDITO_ANTERIOR', 'TASA_1', 'TASA_2', 'TASA_3', 'TASA_4', 'TASA_5', 'TASA_6', 'TASA_7', 'MGNEG', 'MARCA_PD', 'AUTORIZACION_DATOS', 'FLAG_DEUDA_V_OFERTA', 'GRUPO_TASA', 'TIPO_BASE', 'PROPENSION_DISTRIBUCION', 'OFERTA_SS', 'TASA_1_SS', 'TASA_2_SS', 'TASA_3_SS', 'TASA_4_SS', 'TASA_5_SS', 'TASA_6_SS', 'TASA_7_SS', 'ALERTA_MAQUETA', 'FEN', 'PERFIL_ESPECIAL', 'TASA_MIN_DESCUENTO', 'TIPO']colo

In [ ]:
df_validar_01 = pd.read_excel(ruta_archivo,sheet_name='DB')
df_validar_02 = pd.read_excel(ruta_archivo,sheet_name='DB2')

In [ ]:
print(df_validar_01.columns.tolist())
print(df_validar_02.columns.tolist())

In [ ]:
# query = f"""
# 	select NUMERO_DOCUMENTO as dni_cliente,color_final from DANTALION.dbo.Base_Maestra_Alfin_bk_Vigente
# """
# df_maestra = pd.read_sql(query, engine_kishin)

# df_maestra["dni_cliente"] = (
#     df_maestra["dni_cliente"]
#     .astype(str)
#     .str.zfill(8)
# )
# print(df_maestra.columns.tolist())

['dni_cliente', 'color_final']

In [16]:
df_formato=df_formato_01.toPandas()

In [ ]:
# filename='fomato_agendas_alfin_credicash_2026.xlsx'
# filePath = os.path.join(ruta_csv, filename)
# df_formato = pd.read_excel(filePath)

agregando retiro

In [27]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

fecha_mes_base='2026-07-01'

filename='RetiroDefinitivo_BlackList.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_def_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_BlackList.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_Telefonos.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_telf = pd.read_csv(ruta_archivo,sep='|')

filename='retiro_correo_alfin.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_retiro_correo = pd.read_csv(ruta_archivo,sep=';')

df_def_blacklist = df_def_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_blacklist = df_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_telf= df_telf.rename(columns={'TELEFONO': 'celular'})
df_retiro_correo= df_retiro_correo.rename(columns={'DNI': 'dni_cliente'})

print(df_def_blacklist.columns)
print(df_blacklist.columns)
print(df_telf.columns)
print(df_retiro_correo.columns)
print(df_formato.columns.tolist())

Index(['dni_cliente'], dtype='object')
Index(['dni_cliente'], dtype='object')
Index(['celular'], dtype='object')
Index(['dni_cliente', 'celular', 'RETIRO'], dtype='object')
['dni_cliente', 'nombre_cliente', 'celular', 'cod_agencia', 'agencia_atencion', 'fecha_visita', 'monto_solicitado', 'color', 'supervisor', 'canal_campo', 'codigo_ejecutivo_id', 'ejecutivo_target', 'cdv_alfin_banco', 'hora_visita', 'telefono_cliente', 'dni_vendedor', 'agencia_tienda', 'operador', 'tipo_gestion']

In [28]:
df_def_blacklist["dni_cliente"] = (
    df_def_blacklist["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)
df_blacklist["dni_cliente"] = (
    df_blacklist["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)
df_retiro_correo["dni_cliente"] = (
    df_retiro_correo["dni_cliente"]
    .astype(str)
    .str.zfill(8)
)

In [29]:
dni_blacklist = set(df_def_blacklist["dni_cliente"]).union(
    set(df_blacklist["dni_cliente"])
).union(
    set(df_retiro_correo["dni_cliente"])
)


df_formato = df_formato[
    ~df_formato["dni_cliente"].isin(dni_blacklist)
]

telefonos = set(df_telf["celular"]).union(
    set(df_retiro_correo["celular"])
)

df_formato = df_formato[
    ~df_formato["celular"].isin(telefonos)
]

In [ ]:

server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

server_sql = server_zeus
db_sql = "SAMANTHA"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_samantha = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

In [13]:
df_formato.drop_duplicates(subset=["dni_cliente"], inplace=True)

In [7]:
df_formato.shape

(2191, 20)

In [20]:
# df_formato = df_formato[
#     df_formato['agencia_atencion'].isin([
#         'SAN JUAN DE LURIG',
#         'ENMANCIPACION',
#         'PC HUANCAYO',
#         'TRUJ CENTRO',
#         'PC TACNA',
#         'PC HUARAZ',
#         'TRUJ AMERICA',
#         'AREQ CAYMA',
#         'AREQ PAMPILLA'
#     ])
# ]

#### Validar el nombre de la agencia

In [32]:
query = f"""
	select * from Alice.agencias_alfin
"""
df_agencia = pd.read_sql(query, engine_mysql)

set_correo = set(
    df_formato['agencia_atencion']
    .dropna()
    .drop_duplicates()
)

set_agencia = set(
    df_agencia['agencia_correo']
    .dropna()
    .drop_duplicates()
)
# print(set_correo & set_agencia)
print(set_agencia - set_correo)
print(set_correo -set_agencia )

{'IQUITOS'}
set()

In [15]:
print(set_agencia - set_correo)
print(set_correo -set_agencia )

{'IQUITOS'}
{'TE'}

#### validar el codigo de agencia

In [31]:
equivalencias = {
    'SAN JUAN DE LURIG': 'SAN JUAN DE LURIGANCHO',
    'SAN JUAN DE LURIG': 'SAN JUAN DE LURIGANCHO',
    'ENMANCIPACION': 'EMANCIPACION',
    'PC HUANCAYO': 'HUANCAYO',
    'PC TACNA': 'TACNA',
    'PC HUARAZ': 'HUARAZ',
    'TRUJ CENTRO': 'TRUJILLO CENTRO',
    'TRUJ AMERICA': 'TRUJILLO AMERICA',
    'AREQ CAYMA': 'AREQUIPA CAYMA',
    'AREQ PAMPILLA': 'AREQUIPA PAMPILLA'
}

df_formato['agencia_atencion'] = (
    df_formato['agencia_atencion']
    .replace(equivalencias)
)

In [32]:
df_agencia[df_agencia['agencia_correo']=='SAN JUAN DE MIRAFLORES'].head()

,agencia_Formulario,agencia_base,agencia_base2,agencia_correo,correos
34,738224 - SAN JUAN DE MIRAFLORES,SAN JUAN DE MIRAFLORES,SAN JUAN DE MIRAFLORES,SAN JUAN DE MIRAFLORES,yolinda.huayca@alfinbanco.pe

In [30]:
df_correo[df_correo['agencia_atencion']=='SAN JUAN DE MIRAFLORES'].head()

,canal_campo,supervisor,ejecutivo_target,codigo_ejecutivo_id,cdv_alfin_banco,dni_cliente,nombre_cliente,color,monto_solicitado,celular,agencia_atencion,fecha_visita,hora_visita,tipo_carga
74,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,01236008,HERMENEGILDO CALSIN YUCRA,NaN,10000,952524186,SAN JUAN DE MIRAFLORES,2026-07-15,18:30:00,MANUAL
93,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,15627921,MARIZA OBDULIA ROSALES GIRIO DE CHINCHAY,VERDE OSCURO,9700,924119267,SAN JUAN DE MIRAFLORES,2026-07-15,12:00:00,MANUAL
132,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,16806886,VIDELMO YLATOMA BUSTAMANTE,NaN,8900,949886328,SAN JUAN DE MIRAFLORES,2026-07-15,14:45:00,MANUAL
192,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,00205546,ARTURO CRUZ CAMPAÑA,NaN,6000,962095319,SAN JUAN DE MIRAFLORES,2026-07-15,14:30:00,MANUAL
216,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,00214859,ENA ROSA BARRETO DIOSES,NaN,5200,922172667,SAN JUAN DE MIRAFLORES,2026-07-15,09:30:00,MANUAL

In [33]:

set_correo = set(
    df_formato['agencia_tienda']
    .dropna()
    .drop_duplicates()
)

set_agencia = set(
    df_agencia['agencia_Formulario']
    .dropna()
    .drop_duplicates()
)
# print(set_correo & set_agencia)
print(set_agencia - set_correo)
print(set_correo -set_agencia )

set()
{'VILLA MARIA 2', 'PC HUANCAYO', 'AREQUIPA PAMPILLA', 'CHIMBOTE', 'SAN JUAN DE MIRAFLORES'}

In [19]:
print(df_agencia["agencia_correo"].drop_duplicates().tolist())

['CAJAMARCA', 'CASTILLA', 'CHICLAYO BALTA', 'CHIMBOTE', 'MOSHOQUEQUE', None, 'HUARAZ', 'SULLANA', 'TRUJILLO AMERICA', 'TRUJILLO CENTRO', 'AREQUIPA CAYMA', 'AREQUIPA PAMPILLA', 'CAÑETE', 'CHINCHA', 'CUSCO LA CULTURA', 'HUACHO', 'HUANUCO', 'HUARAL', 'ICA', 'IQUITOS', 'JULIACA 2', 'HUANCAYO', 'TACNA', 'PISCO', 'PUCALLPA', 'TARAPOTO', 'ATE VITARTE', 'COMAS', 'EMANCIPACION', 'JESUS MARIA', 'LOS OLIVOS', 'MIRAFLORES', 'PUENTE PIEDRA', 'SAN JUAN DE LURIGANCHO', 'SAN JUAN DE MIRAFLORES', 'SAN MARTIN', 'SAN MIGUEL', 'SANTA ANITA', 'VENTANILLA', 'VILLA EL SALVADOR 2', 'VILLA MARIA 2', 'TUMBES']

In [ ]:
['CAJAMARCA', 'CASTILLA', 'CHICLAYO BALTA', 'CHIMBOTE', 'MOSHOQUEQUE', None, 'HUARAZ', 'SULLANA', 'TRUJILLO AMERICA', 'TRUJILLO CENTRO', 'AREQUIPA CAYMA', 'AREQUIPA PAMPILLA', 'CAÑETE', 'CHINCHA', 'CUSCO LA CULTURA', 'HUACHO', 'HUANUCO', 'HUARAL', 'ICA', 'IQUITOS', 'JULIACA 2', 'HUANCAYO', 'TACNA', 'PISCO', 'PUCALLPA', 'TARAPOTO', 'ATE VITARTE', 'COMAS', 'EMANCIPACION', 'JESUS MARIA', 'LOS OLIVOS', 'MIRAFLORES', 'PUENTE PIEDRA', 'SAN JUAN DE LURIGANCHO', 'SAN JUAN DE MIRAFLORES', 'SAN MARTIN', 'SAN MIGUEL', 'SANTA ANITA', 'VENTANILLA', 'VILLA EL SALVADOR 2', 'VILLA MARIA 2', 'TUMBES']MARIA

In [ ]:
    {'VILLA MARIA 2', 'PC HUANCAYO', 'AREQUIPA PAMPILLA', 'CHIMBOTE', 'SAN JUAN DE MIRAFLORES'}

equivalencias = {
    'SAN JUAN DE LURIG': 'SAN JUAN DE LURIGANCHO',
    'ENMANCIPACION': 'EMANCIPACION',
    'PC HUANCAYO': 'HUANCAYO',
    'PC TACNA': 'TACNA',
    'PC HUARAZ': 'HUARAZ',
    'TRUJ CENTRO': 'TRUJILLO CENTRO',
    'TRUJ AMERICA': 'TRUJILLO AMERICA',
    'AREQ CAYMA': 'AREQUIPA CAYMA',
    'AREQ PAMPILLA': 'AREQUIPA PAMPILLA'
}

df_formato['agencia_atencion'] = (
    df_formato['agencia_atencion']
    .replace(equivalencias)
)
# df_formato.drop_duplicates(subset=["dni"], inplace=True)

In [34]:
print(df_correo["agencia_atencion"].drop_duplicates().tolist())

['HUANUCO', 'HUANCAYO', 'SAN MIGUEL', 'CUSCO LA CULTURA', 'TACNA', 'TRUJILLO CENTRO', 'TARAPOTO', 'EMANCIPACION', 'CHIMBOTE', 'MIRAFLORES', 'TRUJILLO AMERICA', 'HUACHO', 'COMAS', 'CHICLAYO BALTA', 'SAN JUAN DE LURIGANCHO', 'CASTILLA', 'AREQUIPA PAMPILLA', 'SULLANA', 'VENTANILLA', 'MOSHOQUEQUE', 'JESUS MARIA', 'PUCALLPA', 'ATE VITARTE', 'LOS OLIVOS', 'VILLA MARIA 2', 'SANTA ANITA', 'CAJAMARCA', 'AREQUIPA CAYMA', 'PISCO', 'HUARAZ', 'SAN JUAN DE MIRAFLORES', 'CHINCHA', 'HUARAL', 'ICA', 'SAN MARTIN', 'JULIACA 2', 'VILLA EL SALVADOR 2', 'TUMBES', 'CAÑETE', 'PUENTE PIEDRA', nan, 'TE']

In [ ]:

df_correo[df_correo['dni_cliente']=='09704310'].head()

,canal_campo,supervisor,ejecutivo_target,codigo_ejecutivo_id,cdv_alfin_banco,dni_cliente,nombre_cliente,color,monto_solicitado,celular,agencia_atencion,fecha_visita,hora_visita,tipo_carga
2190,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,09704310,SALVADOR ALBERTO CHOQUE ALARCON,NaN,18000,930162239,MIRAFLORES,2026-07-15,13:30:00,MANUAL

In [ ]:
df_correo=df_formato[['canal_campo', 'supervisor', 'ejecutivo_target', 'codigo_ejecutivo_id', 'cdv_alfin_banco', 'dni_cliente', 'nombre_cliente', 'color', 'monto_solicitado', 'celular', 'agencia_atencion', 'fecha_visita','hora_visita']] .copy()
df_correo['tipo_carga']='MANUAL'

df_formulario=df_formato[['dni_vendedor', 'operador', 'dni_cliente', 'nombre_cliente', 'telefono_cliente', 'agencia_tienda', 'fecha_visita', 'monto_solicitado', 'tipo_gestion']].copy()

display(df_correo.head(2))
display(df_formulario.head(2))

,canal_campo,supervisor,ejecutivo_target,codigo_ejecutivo_id,cdv_alfin_banco,dni_cliente,nombre_cliente,color,monto_solicitado,celular,agencia_atencion,fecha_visita,hora_visita,tipo_carga
0,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,0000None,None,None,None,None,None,2026-07-16,15:15:00,MANUAL
1,CALL CENTER / TARGET OUTSOURCING,CARLOS ENRIQUE RAMIREZ CACHIQUE,BOT,00000001,ROSA HONOR,00002596,LILIA CACHIQUE LOPEZ,NARANJA OSCURO,3000,978024945,PUCALLPA,2026-07-16,18:15:00,MANUAL

,dni_vendedor,operador,dni_cliente,nombre_cliente,telefono_cliente,agencia_tienda,fecha_visita,monto_solicitado,tipo_gestion
0,BOT,TARGET,0000None,None,None,None,2026-07-16,None,Derivacion
1,BOT,TARGET,00002596,LILIA CACHIQUE LOPEZ,978024945,738334 - PUCALLPA,2026-07-16,3000,Derivacion

In [34]:
df_correo['fecha_visita']='2026-07-16'
df_formulario['fecha_visita']='2026-07-16'

In [13]:


df_prospectos_correos_alfin.to_sql(
    name="prospectos_correos_alfin",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

df_prospectos_envio_alfin.to_sql(
    name="prospectos_envio_alfin",
    con=engine_mysql,
    if_exists="append",
    index=False,
    chunksize=1000
)

C:\Users\DATA\AppData\Local\Temp\ipykernel_5428\3762344665.py:1: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df_prospectos_correos_alfin.to_sql(

1123

In [ ]:
from sqlalchemy import text

query = """
UPDATE crm_target.alfin_clientes a
INNER JOIN crm_target.tb_temporal b
    ON a.NUMERO_DOCUMENTO = b.col_01 
SET 
    a.estado = b.col_02,
    a.cl_estado= b.col_03
WHERE 
    a.cl_base = 'mayo 2026'
"""

with engine_mysql.begin() as conn:
    result = conn.execute(text(query))
    print("Filas afectadas:", result.rowcount)

In [35]:
df_correo.shape

(5060, 14)