


### Retiro Fugas

In [9]:
import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *

spark = SparkSession.builder \
    .appName("SparkExample") \
    .master("local[*]") \
    .config('spark.driver.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
    .config('spark.executor.extraClassPath', 'C:/spark/jars/mssql-jdbc-13.2.1.jre11.jar') \
    .config('spark.executor.memory', '8g') \
    .config('spark.driver.memory', '8g') \
    .getOrCreate()

In [10]:

filename='retiro_negocios_20260716_01.csv'
df_prueba_ppdplus=cargar_archivo_csv(spark,filename,';',True)
print(df_prueba_ppdplus.columns)

['DNI']

In [12]:
df_prueba_ppdplus = df_prueba_ppdplus.withColumn(
    "DNI",
    F.right(
        F.concat(F.lit("00000000"), F.col("DNI")),
        F.lit(8)
    )

)

In [14]:
overwrite_table_SQL(spark,df_prueba_ppdplus,f'harto_borrado',server_zeus,user_zeus,pwd_zeus,'odin')
overwrite_table_SQL(spark,df_prueba_ppdplus,f'harto_borrado',server_sa,user_sa,pwd_sa,'odin')
overwrite_table_SQL(spark,df_prueba_ppdplus,f'harto_borrado',server_kishin,user_kishin,pwd_kishin,'DANTALION')

In [2]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

In [3]:

server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

server_sql = server_zeus
db_sql = "SAMANTHA"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_samantha = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

In [5]:
fecha_mes_base='2026-07-01'

filename='RetiroDefinitivo_BlackList.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_def_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_BlackList.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_Telefonos.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_telf = pd.read_csv(ruta_archivo,sep='|')

filename='retiro_correo_alfin.csv'
ruta_archivo = os.path.join(ruta_alfin, filename)
df_retiro_correo = pd.read_csv(ruta_archivo,sep=';')

df_def_blacklist = df_def_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_blacklist = df_blacklist.rename(columns={'DNI': 'dni_cliente'})
df_telf= df_telf.rename(columns={'TELEFONO': 'celular'})
df_retiro_correo= df_retiro_correo.rename(columns={'DNI': 'dni_cliente'})


# Blacklists de DNI
df1 = df_def_blacklist.copy()
df1["celular"] = None
df1 = df1[["dni_cliente", "celular"]]

df2 = df_blacklist.copy()
df2["celular"] = None
df2 = df2[["dni_cliente", "celular"]]

# Blacklist de teléfonos
df3 = df_telf.copy()
df3["dni_cliente"] = None
df3 = df3[["dni_cliente", "celular"]]

# Archivo con DNI y celular
df4 = df_retiro_correo[["dni_cliente", "celular"]].copy()



# Unir todo
df_retiros = pd.concat(
    [df1, df2, df3, df4],
    ignore_index=True
)

dni_retiro = set(df_retiros['dni_cliente'].dropna())
cel_retiro = set(df_retiros['celular'].dropna())

C:\Users\DATA\AppData\Local\Temp\ipykernel_8256\3435753884.py:43: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_retiros = pd.concat(

In [7]:
server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
query = f"""
    select NUMERO_DOCUMENTO ,cl_telf1 as celular from DANTALION.dbo.Base_Maestra_Alfin_bk
    where FECHA_ENVIO>='2026-07-01'
"""
dfbae = pd.read_sql(query, engine_kishin)

In [8]:
dfbae = (
    ~(dfbae['NUMERO_DOCUMENTO'].isin(dni_retiro) |
    dfbae['celular'].isin(cel_retiro))
).copy()

In [9]:
filename='queda_alfin.csv'
ruta_archivo = os.path.join(ruta_csv, filename)

dfbae.to_csv(ruta_archivo,sep=';')

In [1]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

fecha_mes_base='2026-07-01'

filename='RetiroDefinitivo_BlackList.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_def_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_BlackList.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_Telefonos.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_telf = pd.read_csv(ruta_archivo,sep='|')


print(df_def_blacklist.columns)
print(df_blacklist.columns)
print(df_telf.columns)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DATA\\Documents\\datos\\05_subir_csv\\RetiroDefinitivo_BlackList.csv'

In [8]:
# df[f"{name_dni}"] = (
#     df[f"{name_dni}"]
#     .astype(str)
#     .str.zfill(8)
# )

# df = df.rename(columns={
#     f'{name_dni}': 'NUMERO_DOCUMENTO'
# })
# df=df[["NUMERO_DOCUMENTO"]]
# df.head()
server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
query = f"""
	select NUMERO_DOCUMENTO
	from DANTALION.dbo.Base_Maestra_Alfin_bk_Vigente
"""
df_alfin = pd.read_sql(query, engine_kishin)

In [7]:
print(df_credicash.columns.tolist())

['DNI']

In [ ]:
fecha_mes_base='2026-07-01'

filename='RetiroDefinitivo_BlackList.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_def_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_BlackList.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_blacklist = pd.read_csv(ruta_archivo,sep='|')
filename='RetiroDeGestion_Telefonos.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_telf = pd.read_csv(ruta_archivo,sep='|')

filename='retiro_correo_alfin.csv'
ruta_archivo = os.path.join(ruta_csv, filename)
df_retiro_correo = pd.read_csv(ruta_archivo,sep=';')

df_def_blacklist = df_def_blacklist.rename(columns={'DNI': 'NUMERO_DOCUMENTO'})
df_blacklist = df_blacklist.rename(columns={'DNI': 'NUMERO_DOCUMENTO'})
df_telf= df_telf.rename(columns={'TELEFONO': 'celular'})
df_retiro_correo= df_retiro_correo.rename(columns={'DNI': 'NUMERO_DOCUMENTO'})

print(df_def_blacklist.columns)
print(df_blacklist.columns)
print(df_telf.columns)
print(df_retiro_correo.columns)
print(df_formato.columns.tolist())

In [4]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

fecha_mes_base='2026-07-01'

filename='retiro_correo_alfin.csv'
name_dni='DNI'

ruta_archivo = os.path.join(ruta_csv, filename)
df = pd.read_csv(ruta_archivo,sep=';')
df.head()

        DNI    celular         RETIRO
0  29652447  958543530  RETIRO_CORREO
1  71126728  999142834  RETIRO_CORREO
2  46121953  959333262  RETIRO_CORREO
3   8699549  988028568  RETIRO_CORREO
4  71104707  935394527  RETIRO_CORREO

In [ ]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

fecha_mes_base='2026-07-01'

filename='blacklist_celulares.txt'
name_dni='DNI'

ruta_archivo = os.path.join(ruta_csv, filename)
df = pd.read_csv(ruta_archivo,sep='|')
df.head()

     CELULAR
0  900000202
1  900000323
2  900000531
3  900000910
4  900001728

In [15]:
query = f"""
	select cl_telf1 as CELULAR
	from DANTALION.dbo.Base_Maestra_ALFCC_Vigente
    WHERE cl_estado IS not NULL OR cl_estado =1
"""
df_credicash = pd.read_sql(query, engine_kishin)

In [16]:
df["CELULAR"] = (
    df["CELULAR"]
    .astype(str)
    .str.zfill(8)
)
df_credicash["CELULAR"] = (
    df_credicash["CELULAR"]
    .astype(str)
    .str.zfill(8)
)

In [17]:
df.merge(df_credicash, on='CELULAR', how='inner').count()

CELULAR    0
dtype: int64

In [ ]:
df.merge(df_credicash, on='CELULAR', how='inner').head()

        DNI
0  22960032
1  41364472

In [ ]:

list_dni = (
    df['DNI']
    .dropna()
    .drop_duplicates()
    .tolist()
)
in_clause = ",".join(f"'{x}'" for x in list_dni)

in_clause

In [ ]:

import sys 
sys.path.append('C:/Users/DATA/Documents/datos/01_script/inicio/funciones')
from funciones import *
from funciones_spark import *
from variables_inicio import *
from utils_sql import *
from sqlalchemy import create_engine
from sqlalchemy import text

fecha_mes_base='2026-07-01'

filename='RetiroDefinitivo_BlackList.csv'
name_dni='DNI'

ruta_archivo = os.path.join(ruta_csv, filename)
df = pd.read_csv(ruta_archivo,sep='|')
df.head()

        DNI
0  00013948
1  00015508
2  00031376
3  00035800
4  00036260

In [ ]:



df[f"{name_dni}"] = (
    df[f"{name_dni}"]
    .astype(str)
    .str.zfill(8)
)

df = df.rename(columns={
    f'{name_dni}': 'NUMERO_DOCUMENTO'
})
df=df[["NUMERO_DOCUMENTO"]]
df.head()
server_sql = server_kishin
db_sql = "DANTALION"
user_sql = user_kishin
pwd_sql = pwd_kishin

engine_kishin = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
query = f"""
	select NUMERO_DOCUMENTO
	from DANTALION.dbo.Base_Maestra_Diners_TC_Vigente
    WHERE RETIRO IS NULL OR RETIRO =''
"""
df_tc = pd.read_sql(query, engine_kishin)

In [18]:
df_tc.shape

(15332, 1)

In [6]:
campana='dinersTc'
query = f"""
    select FECHA as fecha_gestion,DNI as NUMERO_DOCUMENTO,
    PROMOTOR as promotor,
    ESTADO as estado_venta,
    TRAMA_HORA as tramo_venta,
    MONTO as monto_venta,
    DNIEjecutivo as dni_ejecutivo_venta,
    Producto as producto_venta,
    Producto as title,
    Celular as cel_venta,1 as venta,
    subcampana
    from SAMANTHA.dbo.Ventas_Target
    where campana='{campana}'
    and cast(fecha as date) between '{fecha_mes_base}' and EOMONTH('{fecha_mes_base}')
"""
df_ventas = pd.read_sql(query, engine_samantha)

In [16]:
df_ventas.count()

fecha_gestion          51
NUMERO_DOCUMENTO       51
promotor               51
estado_venta           51
tramo_venta            51
monto_venta             0
dni_ejecutivo_venta    51
producto_venta          0
title                   0
cel_venta              51
venta                  51
subcampana              0
dtype: int64

In [7]:
df = df[
    ~df["NUMERO_DOCUMENTO"].isin(df_ventas["NUMERO_DOCUMENTO"])
].copy()

In [8]:
df.merge(df_tc, on='NUMERO_DOCUMENTO', how='inner').count()

NUMERO_DOCUMENTO    0
dtype: int64

In [9]:

list_dni = (
    df['NUMERO_DOCUMENTO']
    .dropna()
    .drop_duplicates()
    .tolist()
)
in_clause = ",".join(f"'{x}'" for x in list_dni)

in_clause

"'45430231','40789975','46099939','75347511','73822062','00517831','74893815','45870423','71756439','29661693','76224741','43802335','46210758','80507642','45488385','46713995','74278103','25780353','10493240','77017172','71001134','40101852','43587345','72242431','16689437','25719415','47222574','10664118','73108124','42918633','03897961','08326458','73671498','74032468','71269972','25719677','44210437','70362663','76731883','40967222','72019934','72516586','44192315','40540834','33432547','42744395','72318000','70422399','71118755','76190783','72450169','72159782','25781210','40683623','41254338','46836584','45949570','42587313','75381780','48261107','74688040','74279262','47609634','46476351','07186103','75061201','47796338','76591509','41218453','48248727','75442136','40815447','44165132','70445682','41699113','47977001','71740655','25750955','42335385','04642001','42304877','29739186','71073282','77455849','00495438','46474205','44802668','31045146','73783524','72744592','75354783','40474117','71993831','76933992','46203109','40003392','72794683','73943396','47616626','09662440','76345763','42265238','72685917','42536489','40524873','46954343','73941974','70505832','73093175','46560976','70011779','72516802','40582055','42844500','46980425','74148925','76509564','70441135','71420564','70932092','74133297','07902676','70465295','73537666','41850929','75012628','10182365','70856210','71487158','72919779','45861405','73243544','09995865','42703856','72550862','09300113','43067154','73030220','71047742','72710017','08132126','70747458','70681500','42834911','41474217','41304279','06985313','72783817','08680598','42704359','40757292','47428053','74760555','75369172','70930583','47990596','72369715','74848271','72479361','46987681','21431188','72877625','45086414','70586202','75083953','41067777','42953642','73815976','47793808','72643519','46026893','45471902','71193700','29607742','73416180','48076990','10730067','01321815','72386284','42913024','47190072','40945697','72045223','46263971','09915686','71489256','07494742','48017753','72856654','43187770','76653296','06672277','44260166','02894754','42084102','76023620','70205504','41867575','74243746','71500194','45491443','42501072','71215198','76351411','46094420','70685185','08743599','10455333','70986036','41504830','71624712','70831667','09906388','43407444','16796838','46706311','25762598','44875277','70291747','72112364','42334922','41209899','43736943','41855838','46605938','72609108','07511823','43759276','71101698','72795104','74077106','31682309','07958420','74716792','41536838','72448320','25772260','42846649','43752945','48701092','20993726','48079842','73597840','72112193','76286862','77815418','77272337','47319013','41300920','45081848','41602333','46735020','44542609','48262172','09537325','74163135','73033056','10128432','16800495','40709721','46605922','29332721','45086166','44050103','72635470','47148250','45354554','45032709','40144978','15766216','48105683','47560922','72843969','71400781','46896334','72970592','09071580','47145868','47533749','71858231','07952767','46126369','71406357','74973305','71301521','73449830','46139829','74096237','71705371','42739770','09678915','43839143','76628549','43434329','46298749','72871866','73089120','76017064','72205789','03677793','44139677','72776787','10053931','70916959','41149528','09379511','73871007','44986261','22755837','41934937','07604565','41955087','71242609','10197367','70865545','40454773','42374120','75082800','10177692','70349417','42789239','44600635','09344372','07729315','47496227','41723755','40709611','08801767','10450532','70321837','44727861','10680823','06605728','45551160','46653323','42856324','75254057','46821005','29680817','40582172','73200596','76760898','77796144','41099076','41811504','74155136','41638519','46896140','48859465','46443851','29672133','70455075','44101377','09336217','03157912','74823248','44026496','46456077','09291398','10198873','40601285','72907938','43804581','43565794','71041126','73180356','10266850','72925776','47684730','00793202','18146435','47561971','43033914','74219919','44247955','46391867','41768583','47124147','42429630','06794947','72656843','40483683','44499194','42616062','10140634','72548650','47566447','10238605','45958314','44763527','46232525','47567063','10281527','42990706','40964558','43402976','46860817','72473793','74039836','72197501','72228377','43643393','47346583','10714891','72839834','42157732','10273053','29709369','44639072','72524861','72396932','41779937','48360090','45989498','45550835','45748313','47624812','43689546','40504800','46665815','46266519','45170691','48173752','45783359','75727032','71761801','78154990','72747567','70025856','71777251','77074028','71056500','43793100','10263689','48514980','42079504','43572024','18135503','47070261','45598432','45495331','41975184','44665097','32782172','09853980','74064030','43480067','47146610','43898302','70275338','72498917','33243040','44125755','72852035','42702769','73835897','70011539','76129840','80407017','73028773','43297771','72942163','07243528','72545473','70023988','73174475','73203305','73530708','45393916','18107798','43033389','41971691','73769404','44796873','45672702','48305440','08715848','72844929','40460804','71411074','44839408','73941777','72226793','40447286','70064626','47162763','07809022','46537624','49010969','70065411','07266069','74757425','40871152','41896266','07616447','70093574','25678883','71466291','10860385','47191394','74619633','46873394','21541070','46873909','74212759','73205419','70002216','40353117','70043563','75242561','10284534','41160310','47460730','74175291','25758059','73235541','26704130','72035385','45120516','25656714','47825662','41360738','46068046','43587643','47235796','41824559','70882409','72354967','09149948','10220621','71430286','70824910','09396773','70807034','47916858','44204176','47151397','78635439','46197920','72194346','70247435','75205998','47009356','43514816','72266656','42633596','70156061','42674108','21532446','25827753','46492041','47454835','73110083','40942691','70929953','44725267','70155150','73026151','16689883','03372768','43363364','71705402','42711333','41842050','71296271','75966514','70516966','45540462','45986875','44239658','41498391','42030107','10001034','77345435','43319550','40284290','41386074','71792612','40883751','42525217','76927249','40420852','07187713','47403888','40472971','46996900','08743830','77290437','40867109','73118813','74516372','76302447','44372088','70467659','25513187','70084200','72748183','74598604','25513188','72200696','42647150','72698260','44366614','74612907','09841704','43193700','41168789','46420421','70458545','74724026','76643957','07913017','06779999','23979214','73216084','10693852','75671429','47942900','45611025','43116460','44126914','48180114','41401338','07852849','42462456','72360203','42804655','45722746','72789400','45013363','08065612','70772779','42506806','47883694','47632695','09874191','72526695','76540456','73674433','41574838','71475090','16783420','72691481','72621243','45372854','44929200','70364822','46880399','08091482','41648136','60267853','70864309','45693829','40989415','72520362','70380674','32739081','76924379','70436982','44862852','46871041','70893105','47878187','45243884','72446195','41571443','70756140','48488455','41424367','70003206','72873298','41676611','70384724','42121563','10724908','09615269','08777136','72943676','45420317','45169303','74718862','43337455','07880456','46171909','47630864','75315942','72049302','73432251','47156073','75695772','48347608','41653867','40562063','45243593','10140434','77100227','45241934','44326239','43436172','43572679','45831428','43527893','20001445','70326242','43242919','09469945','10684854','72168047','15609038','74090866','44814878','46546661','72186805','70463393','47278502','29691877','71317885','70265471','44322242','45752330','46667129','73694864','45714873','07880558','15976086','47567324','46467398','46410115','46540655','72428428','76405515','43370456','09822893','06961125','74238010','71619030','74398943','40821707','45108638','15762158','75659407','10221293','16711638','70476661','72578764','41641217','44843767','40863150','46074438','71381007','47444901','41246953','76256648','75896924','74211429','07626818','72238940','48117372','70389450','71001400','72694687','72934199','72783582','10155896','08121268','74809814','71692632','44834548','44011942','45007293','40995405','71298848','10589120','09876040','74032969','70670320','72391887','71212231','73510763','07209999','70119876','42775650','25626041','43978804','40482500','71417929','72934065','40820248','41818980','72461338','46826047','09821570','74086958','76591254','71421129','73465400','70010652','07613540','71229423','73191140','72966935','24003862','08546326','29608438','46097200','43195096','77566998','73202565','73861346','48775754','29535990','73265802','42461627','70108285','76448392','76094732','70067955','43819501','73808788','72354758','47875633','09891020','40925732','47854773','47428717','75662209','73689819','73829101','44538465','47140077','08274649','43351899','10075039','48130812','77665528','09266227','44171857','41077894','26722515','76600649','17588480','45536317','74052119','07619908','70612223','75967878','44148180','42535518','70946749','43573012','46459975','44122052','70667595','42253870','02417810','44124350','48931959','40740064','02804844','41701733','75622502','45174828','43797206','72934559','04631560','23954443','45946935','40119701','45510216','70457222','46581623','10252753','43669443','47796465','72774415','10604352','06815423','29441149','06887465','15383751','77494851','42144025','48272135','44685488','41793912','47275721','46808734','48358960','46265673','45567134','07376069','40473210','17906718','73117099','43230855','41836962','72406597','45524829','10698305','47087815','71056056','46179979','48164548','73379186','77091977','47295281','46758995','07507182','70670690','72939896','10266556','70915505','48239156','45514512','46207238','46286132','10264366','47500557','76422080','40216372','09912632','75687220','71028888','76348945','09365549','73379425','47153773','07116920','71034323','47539038','08268939','44504872','45805953','74127247','46607270','72687053','06769769','46950443','47404100','21138946','73691384','41870440','73896480','47577206','44849266','09852735','71482620','70503745','72155722','46754234','47642459','74741525','77670919','72224190','75074433','70320500','09631018','10136944','10275042','45083174','73973472','10682038','72617655','46800658','41524713','72928558','10549769','43769478','41072241','47810305','07251164','25554572','70093675','70444731','44449247','29622595','29527408','70355985','41139085','10130687','71594873','73124232','48164789','08188253','08731261','73057831','71584163','44319972','70652602','44088765','74570378','08238828','74021216','43476559','44797065','71729878','08758018','73046205','48042456','45471995','47146501','47955399','43565727','75260900','45800913','74126808','43408793','40384569','44259992','72608071','10507519','72839091','74700180','71306808','73617663','74091585','71960515','42163551','41171512','07637190','41413243','46992267','77140885','76553980','70005398','72310950','10266038','76196289','74144307','09836679','70046250','08748931','08355027','70305100','43662324','06800411','70519709','01119927','77217107','70410662','44026872','46029373','47158601','76289598','08687395','09831884','23801640','70345640','44757698','46958567','08667587','80306819','71814887','46047251','45429517','44375591','07275091','08837125','06767117','47413682','70080436','40427069','46770318','46236404','70939383','44497800','61359128','46216698','44011533','72769628','06253870','08428921','43945443','73533228','70671272','71480326','73953022','02617685','43512180','40422606','72381991','42409052','47850032','07738540','46683050','07817939','07632079','44157080','75537263','72397666','02382180','10609713','46052420','72419260','75067001','46890799','43779150','45876423','40416462','40261305','72039296','40989191','45207539','41636499','42800931','09996151','19336838','10462123','70127967','70442277','41742354','41917526','10537733','73045038','73093633','76978901','46587392','43532243','73613182','43646932','72284771','70759212','45906497','74377042','74985298','72405644','07973679','48486506','20107528','71765998','43685906','07686261','16733399','71994322','44384038','72028473','46691248','45459306','72561745','74040159','10004993','07364465','43237683','07017664','10724643','47303711','08191689','10305809','15728540','44025368','46498834','48462938','44192704','09617653','42694226','42645504','21886428','47525962','18212625','71332054','45555021','70251565','46838899','75234139','17971834','18821973','73013602','48936854','72190579','75326310','21862307','70105418','09956289','09575840','70494026','72804949','72715738','46151395','75422134','72481615','46084180','73243611','42379304','43662646','10006040','70977236','71629140','76324912','44111971','46588894','71878277','09867384','72501818','44000193','73759282','40212421','42010051','76364589','73385163','45064903','42061539','77225699','76939959','42824639','46838674','47248574','44496744','70447733','72384334','48028494','72353206','44919869','75326397','70028745','44311615','41571876','00370400','73018846','70770239','74963143','09410646','45173037','48068200','71381547','48317339','73226555','72372864','71307655','40075047','46487318','76258489','76746164','43004095','31676998','43480262','78288795','77607488','73186298','40457048','10197645','09508855','73776727','48512080','08158276','40490679','70524925','71834042','72214388','70865392','70133591','16729563','72353365','75564363','74635202','73132823','74600612','76982258','07556959','47013424','74145738','70459825','42084794','72039292','72391400','71424581','80647100','72271818','42884817','44053683','75424601','19331237','72896768','72552394','72648104','42659446','40685127','10797404','47449865','07478204','75976153','43077172','48688277','45768481','44524910','44266079','71814012','70883721','43954026','07441752','71342690','47587122','41353087','40345765','47541224','45625732','70566931','48015357','74465046','46674132','72947017','47990513','71542086','17633023','41546935','76639855','41884890','02873220','43140574','73419621','71616832','44665086','46414743','06789187','43029415','47496238','47488051','10176071','74119975','42177973','45798334','46419585','41053531','42933950','70932220','77919137','45191060','72102403','74921989','16679571','40385402','75770333','48486419','41209896','73893451','74167307','48025452','40426277','43960118','47503991','45523210','70493266','47984275','10724224','47839838','73302621','45969809','17939289','46603242','73074399','45232899','09443854','72791270','47559044','48508115','45904850','71133062','09966555','40704704','74659554','44350777','07971765','72544700','70477161','08151952','43319436','76513396','41305315','47998675','08466201','70440152','47231919','41146441','44120402','43704012','44999622','44992257','45781426','45609747','72103484','72664573','70571874','48253217','74085128','44710092','44928012','74986143','71540026','16719215','71323449','70887958','21141322','43636572','46294375','40715785','16706872','40218033','40039618','45841329','71632134','73824738','40394173','75381677','47206505','40386031','73240421','70190063','70760229','45749188','45978558','45956276','76587136','71784290','75531531','70452121','45218920','43545555','74051112','74526738','75695046','72802770','42483937','42416602','07361163','42224085','45474836','43378034','42129816','16796386','44797732','48956212','45519894','48661587','70434003','44259789','72130708','74051118','71428416','45354037','44965800','71012183','46121954','70572100','10333639','46142908','40961925','45639790','47644185','46117105','43810238','45489646','71662007','06759717','43929675','44663171','71411211','07955757','10388884','43000035','73631912','46126647','48368216','45442631','45074845','47689818','43463642','74501145','70485860','46328810','47832652','40437514','75493625','48079322','71695917','73095335','42994051','43497837','47712797','78092058','45478633','43356933','25767128','15724444','47235920','08183832','43875741','72767067','41833100','09562704','46462606','26733725','45477673','46332014','07716860','45812537','15851670','23930121','47265366','47865105','75121912','47210494','71632132','46307864','45236433','45478818','76438666','70584126','71714562','44343229','41862800','10633853','76298433','42883226','09965610','10111181','40036325','75119975','76881921','75504590','46467281','70024925','10771632','70281834','07494309','47737382','08883549','06915680','10298410','40203354','09973655','46032892','09821577','07862663','43742764','16661173','47877444','29408732','41935156','73055111','47900338','40661222','72247625','71342122','45197364','41070921','09690072','42581698','74988837','45863718','73244286','70024451','07530064','06151167','10544568','72712178','42797321','76446642','08637080','70819004','76627940','10175154','47479574','74728641','41287193','07264314','74084689','41344818','45419830','09945795','07471796','45851899','20024289','73065094','45795811','71229378','76027073','72495494','08138673','47119351','08801994','72891407','45545742','72157155','43209547','75199875','46571396','77273166','75870313','72163535','70405618','16732149','40947225','44328746','74137606','47235476','45384760','70775200','72180382','46082933','70026564','71075593','45849243','74078866','72192371','73043005','71972740','45758559','45972864','73229573','77200116','74731402','72795750','46544389','70178589','73504035','71385715','70052318','70914145','74990731','44918484','72938241','70006926','71044434','70079967','72630758','72530330','71939209','46296809','76523524','72800162','10557439','43642400','70266931','42909040','46442505','70867285','18207835','45842977','16737928','71695998','44058535','70391222','41617026','72707027','10720401','46898532','70171872','73367195','75748874','76262292','74135115','77801520','40485197','45199388','44649021','41349801','41022455','46530145','70479425','40154705','45525541','71142947','03893949','41808733','09993706','40803944','45482554','10496290','70219632','72632340','09573484','70664877','46212586','71854740','70095924','76759111','09632746','70231075','40285150','74171561','43689219','72165030','47563222','25581925','74438751','47507708','74766959','47939458','48219402','72781650','41320418','72759065','46894251','70441586','72785204','08801612','72688951','45253845','71335985','72438375','46156157','42526701','75513296','10033595','75887167','02666615','73510506','04073114','74557078','72847477','73071138','72084376','75269445','46777768','44357751','41795636','47402146','46283264','70751158','44201774','09926343','70438671','72859635','47331948','09845729','71576601','76061124','08274597','48235665','70255717','74150246','48408720','70524179','77152736','72303238','74232366','42009222','46755783','73444508','43703430','43079363','70759123','46708234','70014634','43221750','70320723','45674204','04085544','73070814','46771452','70060269','09879631','41896502','44425693','43380617','47280250','74470834','75234320','42731580','22079996','75861665','46704381','77127705','44749274','45493265','40988170','73899794','40749381','72630189','09433764','10007844','46346074','71101487','43128736','45816039','75080601','10199005','42228466','48344045','47510616','74963499','47202868','48089532','29726515','00797117','42728978','47736883','74085751','08888976','49009739','46495421','72447406','29299934','09492458','72898221','46062148','74985023','73947664','76310080','71498639','72547316','43173604','70049750','72141776','75232287','44138776','72207802','40103435','72137852','40842664','45758813','44229732','70817949','72134000','43618468','07192085','08377652','75610428','70568470','

In [24]:
in_clause = ",".join(f"'{x}'" for x in list_dni)

In [9]:
df.count()

NUMERO_DOCUMENTO    2034
dtype: int64

In [32]:
try:
    with engine_kishin.begin() as conn:
        query = f"""
            UPDATE DANTALION.dbo.Base_Maestra_Diners_TC
            SET RETIRO = 'RETIRO_01'
            WHERE NUMERO_DOCUMENTO IN ({in_clause})
                and TRY_CONVERT(DATE, fecha_envio) >= TRY_CONVERT(DATE, '{fecha_mes_base}')
                AND TRY_CONVERT(DATE, fecha_envio) < DATEADD(MONTH, 1, TRY_CONVERT(DATE, '{fecha_mes_base}'))
        """
        result = conn.execute(text(query))
        print("Filas actualizadas:", result.rowcount)

except Exception as e:
    print(e)

Filas actualizadas: 215

In [ ]:

df_ventas.head()

,fecha_gestion,NUMERO_DOCUMENTO,promotor,estado_venta,tramo_venta,monto_venta,dni_ejecutivo_venta,producto_venta,title,cel_venta,venta,subcampana
0,2026-07-01,07259135,08728081,1.-VALIDADA,9,None,08728081,None,None,981260227,1,None
1,2026-07-01,07779510,44592143,6.-SIN VALIDAR,13,None,44592143,None,None,989371280,1,None
2,2026-07-01,40102384,44592143,1.-VALIDADA,10,None,44592143,None,None,932595948,1,None
3,2026-07-01,40552162,47202133,1.-VALIDADA,10,None,47202133,None,None,988594366,1,None
4,2026-07-01,41266190,44592143,1.-VALIDADA,9,None,44592143,None,None,940049145,1,None

In [33]:
exec_query_sql(server_kishin, db_kishin, user_kishin, pwd_kishin, "tNumeros_Diners_tc", "SP tNumeros diners TC")
exec_query_sql(server_zeus, "ODIN", user_zeus, pwd_zeus, "EXEC Sp_Actualizar_Diners_tc", "SP actualizar diners TC Zeus")
exec_query_sql(server_sa, "ODIN", user_sa, pwd_sa, "EXEC Sp_Actualizar_Diners_tc", "SP actualizar diners TC SA")

SP tNumeros diners TC | realizado | duración: 192.49 seg
SP actualizar diners TC Zeus | realizado | duración: 9.92 seg
SP actualizar diners TC SA | realizado | duración: 2.35 seg

In [8]:
query = f"""
	select NUMERO_DOCUMENTO,PROB_CONTACTO,concat('2026-07-',right(retiro,2)) as retiro
	from DANTALION.dbo.Base_Maestra_Diners_TC_Vigente
    WHERE RETIRO IS not NULL OR RETIRO <>''
"""
df_tc = pd.read_sql(query, engine_kishin)

In [9]:
df_tc.head()

  NUMERO_DOCUMENTO PROB_CONTACTO      retiro
0         47216152             D  2026-07-01
1         71561197             D  2026-07-01
2         42968074             C  2026-07-01
3         73473064             E  2026-07-01
4         46510882             C  2026-07-01

In [ ]:


server_sql = server_zeus
db_sql = "SAMANTHA"
user_sql = user_zeus
pwd_sql = pwd_zeus

engine_zeus = create_engine(
    f"mssql+pyodbc://{user_sql}:{pwd_sql}@{server_sql}/{db_sql}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)
fecha_mes_base='2026-06-01'
campana=fecha_a_nombre('2026-05-01')
query = f"""
select dni as NumDoc, 1 as venta_target from SAMANTHA.dbo.Ventas_Target
where CAMPANA='Diners'
and CONVERT(DATE, FECHA) >= CONVERT(DATE, '{fecha_mes_base}')
AND CONVERT(DATE, FECHA) < DATEADD(MONTH, 1, CONVERT(DATE, '{fecha_mes_base}'))
   
"""
df_venta = pd.read_sql(query, engine_zeus)

df_target = df_tc.merge(
    df_venta,
    on='NumDoc',
    how='left'
)
df_final = df_target.merge(
    df,
    on='NumDoc',
    how='inner'
)
df_final = (
    df_final[df_final['venta_target'].isnull()]
    .drop(columns=['venta_target'])
)
df_final.rename(
    columns={
        'Importe Solicitado': 'Monto'
    },
    inplace=True
)
print(df_final.columns.tolist())

c:\Users\DATA\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

['NumDoc', 'TIPO_PRODUCTO', 'RETIRO', 'Canal', 'Autor', 'Subcanal', 'Motivo', 'Monto', 'fecha', 'hora']

In [72]:
df_final=df_final[df_final['Monto'].notnull()]

In [78]:
df_final[['TIPO_PRODUCTO','Canal', 'Monto', 'fecha']].head()

  TIPO_PRODUCTO              Canal    Monto       fecha
0           PPD  CANALES DIGITALES  41100.0  2026-06-04
1           PPD  CANALES DIGITALES  13800.0  2026-06-04
2           PPD     CONTACT CENTER   6000.0  2026-06-04

In [ ]:

total_monto_ppd = df_final.loc[
    df_final['TIPO_PRODUCTO'] == 'PPD',
    'Monto'
].sum()

total_ope_ppd = df_final.loc[
    df_final['TIPO_PRODUCTO'] == 'PPD',
    'Monto'
].count()

print(f'PPD | Monto total: {int(total_monto_ppd)} |  Total operaciones {int(total_ope_ppd)} ')

PPD | Monto total: 60900 |  Total operaciones 3

In [ ]:
# ruta_archivo = os.path.join(ruta_csv, 'PPD_plus.xlsx')
# df_list_filtrada.to_excel(ruta_archivo, index=False)

In [ ]:
list_dni = (
    df_final.loc[df_final['RETIRO'].isna(), 'NumDoc']
    .dropna()
    .drop_duplicates()
    .tolist()
)

in_clause = ",".join(f"'{x}'" for x in list_dni)

try:
    with engine_kishin.begin() as conn:
        query = f"""
            UPDATE DANTALION.dbo.Base_Maestra_Diners
            SET RETIRO = 'RETIRO'
            WHERE NumDoc IN ({in_clause})
                and CONVERT(DATE, fecha_envio) >= CONVERT(DATE, '{fecha_mes_base}')
                AND CONVERT(DATE, fecha_envio) < DATEADD(MONTH, 1, CONVERT(DATE, '{fecha_mes_base}'))
        """
        result = conn.execute(text(query))
        print("Filas actualizadas:", result.rowcount)

except Exception as e:
    print(e)

In [77]:
exec_query_sql(server_kishin, db_kishin, user_kishin, pwd_kishin, "tNumeros_Diners", "SP tNumeros diners")
exec_query_sql(server_zeus, "ODIN", user_zeus, pwd_zeus, "EXEC Sp_Actualizar_Diners", "SP actualizar diners Zeus")
exec_query_sql(server_sa, "ODIN", user_sa, pwd_sa, "EXEC Sp_Actualizar_Diners", "SP actualizar diners SA")

SP tNumeros diners | realizado | duración: 5.48 seg
SP actualizar diners Zeus | realizado | duración: 5.54 seg
SP actualizar diners SA | realizado | duración: 1.5 seg

In [55]:
fecha_mes_base='2026-07-01'
tipi_cond1='diners'
tipi_cond2='plus'
# tipi_cond2='CD'
tipi_cond3='xx'
tb_tipolofia='tTipologia_Diners_PPD'
servidor_01=21
tipi_cod='cod'
tipi_resp_cod='C0'
tipi_descrip='[NIVEL 4]'
tipi_estado='[NIVEL 2]'
tipi_resp_estado='NO CONTACTO'
tipi_subdescripcion='[NIVEL 3]'
tnum_tb='tNumeroDiners'
tnum_dni='NumDoc'

tlista_generada='borrar_prestamo_diner'
get_base=since_base_maestra_pp_dinners

def resumen_vicidial(spark,fecha_mes_base,tipi_cond1,tipi_cond2,tipi_cond3,tb_tipolofia,servidor_01,tipi_cod,tipi_resp_cod,tipi_descrip,tipi_estado,tipi_resp_estado):
    query = f"""
        SELECT *
        FROM OPENQUERY([192.168.3.{servidor_01}], '
            SELECT        
            rtrim(ltrim(d.vendor_lead_code)) AS vendor_lead_code,        
            e.dial_method,
            a.campaign_id AS numero_campana,        
            a.user AS dni_ejecutivo,
            c.full_name AS ejecutivo,
            e.campaign_name AS nombre_campana,        
            a.call_date AS fecha_hora_llamada,        
            a.length_in_sec AS duracion,        
            b.status_name AS call_result,        
            f.list_description,        
            f.list_name,        
            a.phone_number as phone_number,        
            d.alt_phone as fecha_agenda,        
            d.comments as comentarios,        
            a.status AS codigo,
            a.term_reason,	
            a.alt_dial
            FROM asterisk.vicidial_log a         
            LEFT JOIN asterisk.vicidial_list d ON a.lead_id=d.lead_id        
            LEFT JOIN asterisk.vicidial_campaigns e ON a.campaign_id=e.campaign_id        
            LEFT JOIN asterisk.vicidial_lists f ON a.list_id=f.list_id        
            LEFT JOIN asterisk.vicidial_statuses b ON a.status=b.status        
            LEFT JOIN asterisk.vicidial_users c ON a.user=c.user        
            WHERE (e.campaign_name like "%{tipi_cond1}" or e.campaign_name like "%{tipi_cond2}" or e.campaign_name like "%{tipi_cond3}")
            AND a.call_date >= DATE_FORMAT(''{fecha_mes_base}'', ''%Y-%m-01'')
            AND a.call_date < 
            DATE_ADD(DATE_FORMAT(''{fecha_mes_base}'', ''%Y-%m-01''), INTERVAL 1 MONTH)
        ')

        """
    df_vicidial=obtener_tabla_sql(spark,query,server_zeus,user_zeus,pwd_zeus,db_zeus)

    df_vicidial = df_vicidial.withColumn(
        "vendor_lead_code",
        F.lpad(F.col("vendor_lead_code").cast("string"), 8, "0")
    )
    query = f"""
        SELECT {tipi_cod} as codigo
        , case
            when {tipi_cod}='CALLBK' then 'VOLVER A LLAMAR - call'
            else {tipi_descrip} 
        end as descripcion
        ,case 
            when {tipi_cod}='CALLBK' then 1200
            else peso 
        end as peso 
        ,[NIVEL 2] as estado
        FROM [ODIN].[dbo].{tb_tipolofia}
        where LEFT({tipi_cod},2)='{tipi_resp_cod}' or {tipi_estado}='{tipi_resp_estado}' or {tipi_cod}='CALLBK'
        """
    df_tipi=obtener_tabla_sql(spark,query,server_zeus,user_zeus,pwd_zeus,db_zeus)

    df_vicidial=df_vicidial.join(df_tipi,["codigo"],"left")

    return df_vicidial.select('fecha_hora_llamada','list_name','vendor_lead_code','phone_number','descripcion','dni_ejecutivo','ejecutivo','dial_method','term_reason','alt_dial','call_result','duracion','codigo','nombre_campana','peso','estado')

df_vici=resumen_vicidial(spark,fecha_mes_base,tipi_cond1,tipi_cond2,tipi_cond3,tb_tipolofia,servidor_01,tipi_cod,tipi_resp_cod,tipi_descrip,tipi_estado,tipi_resp_estado)
# df_vici.filter(F.col('vendor_lead_code')=='45914692').orderBy(F.col('fecha_hora_llamada').desc()).show(truncate=False)

In [64]:
query = f"""
    SELECT *,NumDoc as vendor_lead_code FROM [DANTALION].[dbo].Base_Maestra_Diners_vigente
    """
df_ssff=obtener_tabla_sql(spark,query,server_kishin,user_kishin,pwd_kishin,db_kishin)

In [57]:

window_spec = Window.partitionBy("vendor_lead_code").orderBy(F.col("peso").asc_nulls_last(),F.col("fecha_hora_llamada").desc_nulls_last())
df_vici = df_vici.withColumn("orden", row_number().over(window_spec))
df_vici=df_vici.filter(F.col('orden')==1)

In [60]:
df_vici=df_vici.withColumn('me_resultado_cet',when((F.col('estado')=='CONTACTO EFECTIVO')&(F.col('orden')==1),1).otherwise(F.lit(0)))

In [65]:
df_ssff_1=df_ssff.join(df_vici,['vendor_lead_code'],'left')

In [30]:
df_vici.select('estado').distinct().show()

+--------------------+
|              estado|
+--------------------+
|CONTACTO NO EFECTIVO|
|         NO CONTACTO|
|   CONTACTO EFECTIVO|
|                NULL|
+--------------------+

In [ ]:



df_ssff_1=df_ssff_1.withColumn('me_resultado',when(F.col('orden')==1,1).otherwise(F.lit(0)))
df_ssff_1=df_ssff_1.withColumn('me_resultado_cet',when((F.col('estado')=='CONTACTO EFECTIVO')&(F.col('me_resultado')==1),1).otherwise(F.lit(0)))


window_spec = Window.partitionBy("vendor_lead_code").orderBy(F.col("vendor_lead_code").asc_nulls_last())
df_ssff_1 = df_ssff_1.withColumn("unico", row_number().over(window_spec))
df_ssff_1=df_ssff_1.withColumn('unico',when(F.col('unico')==1,1).otherwise(F.lit(0)))

In [66]:
df_list_filtrada = df_ssff_1.toPandas()
ruta_archivo = os.path.join(ruta_csv, 'validar_base_ssff3.xlsx')
df_list_filtrada.to_excel(ruta_archivo, index=False)

In [21]:
df_vici.show()

+-------------------+---------+----------------+------------+--------------------+-------------+--------------------+--------------------+------------+--------+--------------------+--------+------+--------------+
| fecha_hora_llamada|list_name|vendor_lead_code|phone_number|         descripcion|dni_ejecutivo|           ejecutivo|         dial_method| term_reason|alt_dial|         call_result|duracion|codigo|nombre_campana|
+-------------------+---------+----------------+------------+--------------------+-------------+--------------------+--------------------+------------+--------+--------------------+--------+------+--------------+
|2026-07-01 12:00:39|      AB_|        10799771|   998667811|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       1|    AA|2026-07 DINERS|
|2026-07-01 12:00:40|      AB_|        07876095|   920361561|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:00:41|      AB_|        25740058|   998604947|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:00:45|      AB_|        43791012|   987735585|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:00:45|      AB_|        42956491|   994458018|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:00:47|      AB_|        08691879|   965799080|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:00:55|      AB_|        44112734|   961510193|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:00:58|      AB_|        10358852|   993842645|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       1|    AA|2026-07 DINERS|
|2026-07-01 12:01:00|      AB_|        06040466|   995070199|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:01:03|      AB_|        08664113|   974272296|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       1|    AA|2026-07 DINERS|
|2026-07-01 12:01:04|      AB_|        08115899|   939170663|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:01:05|      AB_|        40271012|   999926487|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:01:11|      AB_|        09391082|   993051595|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:01:12|      AB_|        73580864|   959175748|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:01:14|      AB_|        07459664|   992849783|         NO CONTESTA|         VDAD|  Outbound Auto Dial|RATIO            ...|CALLER      |    NONE|Answering Machine...|       0|    AA|2026-07 DINERS|
|2026-07-01 12:00:35|      AB_|        45762998|   950822513|         NO CONTESTA|       TCD055|MARCO ESTEFANO CA...|RATIO            ...|CALLER      |    MAIN|                NULL|      10|  C039|2026-07 DINERS|
|2026-07-01 12:00:19|      AB_|        42076730|   996046706|TELEFONO APAGADO ...|         VDAD|  Outbound Auto Dial|RATIO            ...|ABANDON     |    NONE| Agent Not Available|       1|  DROP|2026-07 DINERS|
|2026-07-01 12:00:19|      AB_|        18107455|   997303066|SOCIO CORTÓ SIN E...|       TCD070|OSCAR EDUARDO MAR...|RATIO            ...|CALLER      |    MAIN|                NULL|       6|  C034|2026-07 DINERS|
|2026-07-01 12:01:11|      AB_|        71123403|   958038019|SOCIO CORTÓ SIN E...|       PFD023|JULY MARGOT SALAZ...|RATIO            ...|CALLER      |    MAIN|                NULL|      39|  C034|2026-07 DINERS|
|2026-07-01 12:01:00|      AB_|        40960580|   942866193|SOCIO CORTÓ DESPU...|       PFD022|ANDY ALONSO TORIB...|RATIO            ...|CALLER      |    MAIN|                NULL|      27|  C033|2026-07 DINERS|
+-------------------+---------+----------------+------------+--------------------+-------------+--------------------+--------------------+------------+--------+--------------------+--------+------+--------------+
only showing top 20 rows